### ISSUE TITLE
Disable skins in teams gamemode

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#10]
As this isn't used in the official client.

Agar.io:

![image](https://cloud.githubusercontent.com/assets/11600822/15802203/be3ad09a-2aa2-11e6-8616-691c6f559453.png)

MultiOgar:

![image](https://cloud.githubusercontent.com/assets/11600822/15802209/ee1a9d22-2aa2-11e6-901f-2b25f55afaee.png)

An evidence to make sure i'm not in the wrong gamemode:

![5](https://cloud.githubusercontent.com/assets/11600822/15802223/59af39f8-2aa3-11e6-8394-c36246047614.png)

**Comment by F0RIS** [comment]
how you deal with error https://github.com/Barbosik/MultiOgar/issues/7 ??

**Comment by Barbosik** [comment]
fixed
