### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#102]
How to disable/changevalue of autosplit ?
_Sorry bad inglish_

**Comment by NatsuTheGreat** [comment]
change ```playerMaxSize``` to whatever you want.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Not it,when up to 25000 mass(I think)

**Comment by NatsuTheGreat** [comment]
1500*1500/100 = 22500.

**Comment by NatsuTheGreat** [comment]
You'll have to follow that formula.

**Comment by GhostShot3** [comment]
@NatsuTheGreat How much is 100k ?

**Comment by NatsuTheGreat** [comment]
3162 sounds good.

**Comment by Barbosik** [comment]
GhostShot3: you can calculate size with SQRT ( mass * 100 ).

For example to set max mass = 100000, you're need to set size = SQRT ( 100000 * 100 ) = 3162

Also you can use massToSize, for example:
```
playerMaxSize = massToSize(100000)
```

**Comment by GhostShot3** [comment]
@Barbosik there are converters for it?, I do not understand, do not speak fluent English :(

**Comment by Barbosik** [comment]
yes just use `massToSize(100000)` instead of `100000`

**Comment by GhostShot3** [comment]
@Barbosik You are owner ?

**Comment by Megabyte918** [comment]
you should add how to do that in gameserver.ini so people wont get confused

**Comment by NatsuTheGreat** [comment]
I think there are already instructions there :)

**Comment by Megabyte918** [comment]
not how to use `massToSize`

**Comment by NatsuTheGreat** [comment]
Cool.
