### ISSUE TITLE
PLS ADD...

### ISSUE THREAD

**Issue by inxlio** [Barbosik/MultiOgar#103]
Hello , pls add:

- Cellborders 
- POPSPLIT NOT WORKING TOTALLY
- LINESPLIT NOT WORKING TOTALLY 
- MINIONS
- DOUBLE SPLIT NOT WORKING TOTALLY

**Comment by Barbosik** [comment]
* Cell border - it's a client issue, use client with cell borders
* Pop split works, you can find video here
* Double split works, the same as tripple split, etc

**Comment by inxlio** [comment]
Linesplit not working --

Minions--

why the cellborders not working some that agario?

**Comment by Barbosik** [comment]
inxlio: Because it's your client bug. The MultiOgar server does not affect the cell outline. It even don't know that your client drawing it.

**Comment by MastaCoder** [comment]
> Minions--

no. just no.
