### ISSUE TITLE
Cellborders , looks like DECAGON

### ISSUE THREAD

**Issue by inxlio** [Barbosik/MultiOgar#106]
![image](https://cloud.githubusercontent.com/assets/20158370/16546575/58df33c8-4125-11e6-84a1-4aabc1295e54.png)

WITH CELLBORDERS , It seems a decagon

![image](http://decagono.com/img/decagono.png)

**Comment by nulcearc** [comment]
It's because of client, not server

**Comment by inxlio** [comment]
safe? , 
I think it's the speed of splits

**Comment by Megabyte918** [comment]
lolwat

**Comment by NatsuTheGreat** [comment]
Dude, if you want everything like agar.io, USE THE AGAR.IO CLIENT! Otherwise MultiOgar will pick the appropriate protocol for the client you're using, you're using an older protocol as I see.

**Comment by Barbosik** [comment]
it's client issue and not related to the server
