### ISSUE TITLE
I can't popsplit/tricksplit bots

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#107]
Popsplit works,but when i try to popsplit bots,I can not because the bot split before.

**Comment by NatsuTheGreat** [comment]
That is very annoying, sometimes they completely reverse your Popsplit. But hey, Smarter AI = more fun to play.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Yes they reverse but i never can popsplit :(

**Comment by NatsuTheGreat** [comment]
I've popsplit one, only once.

**Comment by Prime55** [comment]
It's almost impossible to tricksplit them too though lol. They're so pro.

**Comment by NatsuTheGreat** [comment]
Naw, I can tricksplit them easy.

**Comment by GhostShot3** [comment]
@NatsuTheGreat Update ?

**Comment by GhostShot3** [comment]
@NatsuTheGreat And vanish.

**Comment by NatsuTheGreat** [comment]
Vanish yes.

**Comment by MastaCoder** [comment]
Jeez you guys know all the tricks lol.

**Comment by NatsuTheGreat** [comment]
Yep :P

**Comment by GhostShot3** [comment]
@NatsuTheGreat Thanks,but is not posssible to disable tricksplit/popsplit reverse ?

**Comment by NatsuTheGreat** [comment]
You'll have to mess up mass calculations in the bot AI.

**Comment by Prime55** [comment]
@GhostShot3 But anyways, i don't think its possible to popsplit even if they dont reverse you...**(popsplitting doesn't work the same as vanilla)**

**Comment by GhostShot3** [comment]
@Prime55 "popsplitting doesn't work the same as vanilla" ???? what ?
