### ISSUE TITLE
Can you implement ejectSizeLoss so it's configurable?

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#109]
Subj.

**Comment by ZfsrGhS953** [comment]
It's already implemented in my clone @ [http://www.agarserv.com/forums/topic/some-petridish-pw-modes-in-ogar/](url) . It also has some petridish.pw modes and anti-teaming.

**Comment by Barbosik** [comment]
**ZfsrGhS953**: links which consists of code with replaced copyright header is not allowed here. 
You posted a link with code which violates clause 4 (c) of Apache 2 license.

You can modify and redistribute the code. But you're not allowed to remove all copyright, patent, trademark, and attribution notices from the Source form of the Work.

By distributing source code with removed copyright you make criminal offense and legislative actions can be applied to you, and it's not a joke. Please apply Apache 2 license requirements and return copyright headers back.

**Comment by Barbosik** [comment]
ItzLevvie: implemented
