### ISSUE TITLE
lag

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#111]
my server lags every 2 mins lag(freezes) for 3-5 seconds I dont know why Server has High specs but lag HELP!

**Comment by DTMClanDeveloper** [comment]
Is it just you or everyone? Also are

**Comment by Barbosik** [comment]
may be it's because server has some crontab job or network provider has some issues with network

**Comment by Barbosik** [comment]
can you show st command output at that moment?

**Comment by David1ali12** [comment]
my server is public server  well console dont output anything the server lags for 3-5 secs I tested with all client same issue its fine before I last time updated Its really wired never happened every1 notice the lag Ip:http://agar.io/?ip=134.119.17.230:443 it happens like every 2 mins really wired

**Comment by Barbosik** [comment]
you can connect with SSH to your server and execute commands st and debug from game server console.

You can use tmux to run server in background console.

For example: 
1) run `tmux`
2) start the server from tmux console `node src/index.js`
3) detach from tmux console with Ctrl+B and then D
4) Now you can disconnect from SSH, your server will continue to run

After that you can connect with SSH again and attach to the game server console with `tmux attach`.
You can use several tmux consoles and attach to it by it's name

**Comment by David1ali12** [comment]
st 
```
Connected players: 10/200
Players: 10 - Bots: 0
Server has been running for 0 minutes
Current memory usage: 21.8/33.7 mb
Current game mode: Free For All
Current update time: 1.216 [ms]  (perfectly smooth)
```

**Comment by Barbosik** [comment]
looks good, at the moment when you executed st command there is no lags from MultiOgar side.

**Comment by David1ali12** [comment]
thanks bro it dont lags now :)
