### ISSUE TITLE
I made official server tracker for MultiOgar

### ISSUE THREAD

**Issue by lulzyyy** [Barbosik/MultiOgar#112]
http://c0nsume.me/tracker.php Working fine, tested. I'm using php + mysql.

Could you add this tracker to your code?
Just add new request with options, data are same as from ogar.mivabe.nl. Server is removed from list after 35 seconds of shut down

      host: 'c0nsume.me',
      port: '80',
      path: '/tracker.php',
      method: 'POST',

**Comment by lulzyyy** [comment]
After you add this code, I'll add buton on my site to my tracker, because I don't want people to download old version of MultiOgar

**Comment by Barbosik** [comment]
added

**Comment by lulzyyy** [comment]
Thanks. You can also update readme if you want.
