### ISSUE TITLE
Add variables on gameserver , ALL NEED

### ISSUE THREAD

**Issue by inxlio** [Barbosik/MultiOgar#114]
add: You can add this variables on gameserver.ini ?

VirusFeedAmount = 7
splitSpeed 
splitDistance
virusSpeedShoot
VirusDistanceShoot

**Comment by Barbosik** [comment]
No, it ruins physics. You can change virus feed amount with change virusMasSize.
Change split speed will leads to physics bugs.
Split distance can be configured, but I don't see the reason for it, because it ruins split-run and pop-split tricks
