### ISSUE TITLE
I can not play with my friends.

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#116]
I use hamachi for host my multiogar server, my friends can not come in and they're disabled firewall and are in my network more when sending the link for them to play example "http://agar.io/?ip=(hamachi ipv4):(serverport)"they say they can not enter.
_Sorry bad inglish._

**Comment by Barbosik** [comment]
did you used string "(hamachiipv4):(serverpot)" or real ip:port?

**Comment by GhostShot3** [comment]
@Barbosik Ipv4.

**Comment by MastaCoder** [comment]
@GhostShot3 I think you're supposed to use the ones provided by Hamachi.

**Comment by Barbosik** [comment]
you need to use real numbers instead of string. for example "http://agar.io/?ip=192.168.1.5:443"

**Comment by GhostShot3** [comment]
@Barbosik Real numbers ?,I use "/?ip=(HamachiIPV4):(ServerPort).

**Comment by GhostShot3** [comment]
@Barbosik Idk it "Real Numbers"?

**Comment by Barbosik** [comment]
I don't know how hamachi works. But even if it possible to define system variable which will be visible in browser URL string (is it really possible?), I recommend to use numeric ip and port instead of these strings. Because I have no idea how this variable will be synchronized with other computers connected to hamachi.

**Comment by GhostShot3** [comment]
@Barbosik Hamachi is a vpn service.

**Comment by GhostShot3** [comment]
@Barbosik Give me exempla to "numeric ip and port".

**Comment by Barbosik** [comment]
when you connected to hamachi, your computer obtains hamachi ip, for example 192.168.1.5. You should use this ip. Port is defined in gameserver.ini. By default it's 443

**Comment by GhostShot3** [comment]
@Barbosik I use 567 in my port

**Comment by GhostShot3** [comment]
@Barbosik What ip you recommend use ?

**Comment by GhostShot3** [comment]
@Barbosik Look [here](https://en.wikipedia.org/wiki/LogMeIn_Hamachi) for more info about hamachi

**Comment by Barbosik** [comment]
Look at hamachi window on computer where server is started. You should find IP. All your friends should use the same IP from computer where server runs.

**Comment by GhostShot3** [comment]
@Barbosik I do not understand, I am using translator

**Comment by GhostShot3** [comment]
@Barbosik Tell me step by step what i have to do.

**Comment by DTMClanDeveloper** [comment]
you can try hosting on c9.io its pretty simple

**Comment by GhostShot3** [comment]
@DTMClanDeveloper Heard from that danger has to be banned or something to do.

**Comment by GhostShot3** [comment]
@DTMClanDeveloper And idk how to host using c9...

**Comment by GhostShot3** [comment]
Fixed!

**Comment by Barbosik** [comment]
**GhostShot3**: could you please explain how you fixed it, may be it will helps other people with the same issue

**Comment by David1ali12** [comment]
@GhostShot3 I giveaway servers maybe 24/7 but you must follow the mind configs , skype:david12ali9

**Comment by Faris90** [comment]
use c9.io

**Comment by ItzLevvie** [comment]
C9 is not recommended for hosting Agar.io servers. 

It's a IDE meant for development purposes.

**Comment by GhostShot3** [comment]
Not remember sorry now i see you comment.
