### ISSUE TITLE
Ban doesnt work??

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#118]
i host my server off c9.io and i have multiple users and one person is not following the rule so when i try to ban him he just gets kicked but he can still come back on??

**Comment by NatsuTheGreat** [comment]
Last time I checked, bans were fine. If the ban system is really broken, that needs to be fixed. Otherwise, I probably know what the person is using. I don't want to talk about it because more people could start using this.

**Comment by DTMClanDeveloper** [comment]
Alright.

**Comment by Barbosik** [comment]
they can connect from different IP. You can ban his sub-network if he using IP renewal. But if you ban his sub-network, no one from his sub-network will not be able to connect

**Comment by NatsuTheGreat** [comment]
How do we ban his sub-network though?

**Comment by Barbosik** [comment]
currently you can use * to mask all values from 1 to 254. 
For example, to ban IP range from 192.168.1.1 to 192.168.1.254, just execute:
```
ban 192.168.1.*
```

Later I will add support for standard (unix like) IP mask

**Comment by NatsuTheGreat** [comment]
Oh, I didn't know MultiOgar can get your local IP.

**Comment by Barbosik** [comment]
ban for localhost isn't works, to prevent self ban :)

**Comment by NatsuTheGreat** [comment]
Local IP address could also be 192.168.1.* It's like a local computer IP.

**Comment by MastaCoder** [comment]
@NatsuTheGreat I think he was using that as an example :+1: (or it could be actually done ;-;)

**Comment by Barbosik** [comment]
IP starting with 127 is used as loopback interface. All connections for such IP will be loopback on the same machine. IP starting from 192 is a network IP for other machines.
