### ISSUE TITLE
Popsplit not working really

### ISSUE THREAD

**Issue by nobsterr** [Barbosik/MultiOgar#119]
The popsplit and linesplit not working 100% , 
most of the time the popsplit not work

**Comment by nobsterr** [comment]
ANYONE CAN HELP ME?

**Comment by Influxx** [comment]
Popsplit and linesplit is working.

**Comment by Megabyte918** [comment]
popsplit doesn't work half the time and not at all when you are big, and linesplits dont stay in a line

**Comment by liomessip** [comment]
YEP POPSPLIT AND LINESPLIT doesn't work half the time

**Comment by Barbosik** [comment]
duplicated: https://github.com/Barbosik/MultiOgar/issues/62

**Comment by David1ali12** [comment]
no its woks maybe you dont know how to popsplit 
 EXAMPLE: your cell have 8000 mass you can popsplit around 3500 to 3800 mass 95% works you should abit far from cell to popsplit
