### ISSUE TITLE
Issue with boardreset command.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#12]
I get this bug when I use ```boardreset```

>board Testing for bug.
[Console] Successfully changed leaderboard values
>boardreset
[Console] Successfully reset leaderboard

>TypeError: item.getName is not a function
    at UpdateLeaderboard.build49 (C:\Users\Downloads\Ogar-master-Barbosik\Ogar-master\src\packet\UpdateLeaderboard.js:54:19)
    at UpdateLeaderboard.build (C:\Users\Downloads\Ogar-master-Barbosik\Ogar-master\src\packet\UpdateLeaderboard.js:15:30)
    at WebSocket.sendPacket (C:\Users\Downloads\Ogar-master-Barbosik\Ogar-master\src\GameServer.js:1121:29)
    at PlayerTracker.update (C:\Users\Downloads\Ogar-master-Barbosik\Ogar-master\src\PlayerTracker.js:202:17)
    at GameServer.updateClients (C:\Users\Downloads\Ogar-master-Barbosik\Ogar-master\src\GameServer.js:469:39)
    at GameServer.mainLoop (C:\Users\Downloads\Ogar-master-Barbosik\Ogar-master\src\GameServer.js:420:9)
    at Timer.listOnTimeout (timers.js:92:15)

**Comment by Barbosik** [comment]
cannot reproduce. This issue is not related with MultiOgar code, probably it's related to other ogar branches or custom mods. So, please post it into appropriate branch.

**Comment by NatsuTheGreat** [comment]
Welp, fixed it with typeof.

**Comment by Barbosik** [comment]
**NatsuTheGreat**: can you reproduce it on clean MultiOgar? (with no mods, just checkout the latest version)
If you can reproduce it, then write steps to reproduce. I don't see such errors.

**Comment by NatsuTheGreat** [comment]
I already fixed it with a typeof statement. It doesn't appear to be on clean OgarMulti (strange because the only difference between our UpdateLeadboard.js is the highlighting which did not cause the error.

**Comment by Barbosik** [comment]
typeof statement is bad for performance. Can you expain please where did you placed this statement?
I just want to understand - is your error caused by your mods or it's hidden bug?

**Comment by NatsuTheGreat** [comment]
Sorry for late response, I placed the state before ```var name = item.getName();```

**Comment by NatsuTheGreat** [comment]
So am I good to go?

**Comment by Barbosik** [comment]
I have no such issue with non-modified MultiOgar.
I just execute command:
```
board aaa bbb
```

and leaderboard shows aaa and bbb. I don't see any error

**Comment by NatsuTheGreat** [comment]
You said typeof is bad for performance.

**Comment by Barbosik** [comment]
yes. it's better to just check for null

This is bad:
```
   if (typeof node == "undefined")
```

This is good:
```
   if (node == null)
```

**Comment by NatsuTheGreat** [comment]
I checked for a function. And isn't null for objects? If remember correctly. You could also have ```if(node === undefined)```

**Comment by Barbosik** [comment]
may be, actually I'm not so good in JS

**Comment by NatsuTheGreat** [comment]
You're awesome man! You got the protocol fixed and OgarMulti came to life cause of you!
