### ISSUE TITLE
Can you add something so people know that im owner?

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#120]
Can you add something so people know that im owner? people think im fake

**Comment by NatsuTheGreat** [comment]
Sure can, can you tell me what I could make that would tell that you're owner?

**Comment by lotfis** [comment]
@NatsuTheGreat you can add Cigar features wehre you have acces like admin, they where added to ogarUL...
serverAdminPass = ""
adminConfig = 0
adminNames = "" 
adminNewNames = ""
adminStartMass = ... 
adminBlockNames = ..... 
chatMaxMessageLength = ....
chatIntervalTime = ..... 
chatBlockedWords = "fuck;bitch.........."
chatBlockedWordsTo = "****"
specChatAllowed = .......

**Comment by NatsuTheGreat** [comment]
May I know what client you are using, DTMClanDeveloper?

**Comment by DTMClanDeveloper** [comment]
yes im using c0nsume.me i was using ogar.mibale but im switching to c0nsume do to lag issues.

**Comment by DTMClanDeveloper** [comment]
idk what there iss i mean can you make it so like Moderator is in rainbow text next to my name? can u do anything? to make it look like im owner

**Comment by DTMClanDeveloper** [comment]
http://c0nsume.me/private4.php?ip=agar-practice-clanpractice.c9users.io

**Comment by DTMClanDeveloper** [comment]
can you make it so like Moderator is in rainbow text next to my name?

**Comment by MastaCoder** [comment]
I swear to god OgarUL is taking features from every single Ogar clone and not giving shit credit to the original developers.

> serverAdminPass = "" | adminStartMass = ... | adminBlockNames = ..... 

Those were all in Cigar and the code is literally the same..

**Comment by DTMClanDeveloper** [comment]
Natsu you here?

**Comment by NatsuTheGreat** [comment]
Yes, not for long though. I will be leaving very soon. I'll try to work on it when I get back.

**Comment by DTMClanDeveloper** [comment]
ok ty

**Comment by NatsuTheGreat** [comment]
I have thought of a way, got it, tested it. I can't pull request though, the system is being retarded and pulling all MultiOgar commit and publishing my pull requests on Ogar/OgarProject :/

**Comment by DTMClanDeveloper** [comment]
Natsu can you add me on skype? my skype is party.pete2

**Comment by David1ali12** [comment]
how the fuck you made ur server work 24/7 ?

**Comment by DTMClanDeveloper** [comment]
Btw Natsu im new to this so once u make the pull request what do i do....

**Comment by NatsuTheGreat** [comment]
IF i can get the pull request to actually commit to MultiOgar, we'll wait for @Barbosik to merge it and you can just redownload.

**Comment by DTMClanDeveloper** [comment]
like how will it work will it be in the settings? and what will the thing be like to represent me as an owner?

**Comment by NatsuTheGreat** [comment]
Since you use c0nsume.me, you have a chat. Your name would be black, because everyone else has a random color.

**Comment by DTMClanDeveloper** [comment]
can you make it rainbow? because most people use dark theme :/

**Comment by NatsuTheGreat** [comment]
You could change to whatever color you want. What rainbow might do it, generate a random color everytime. (not what you want) I haven't tested it though.

**Comment by DTMClanDeveloper** [comment]
no i mean can each letter be a different colour?

**Comment by NatsuTheGreat** [comment]
Oh, sorry I didn't know what you exactly mean :) I'll work on it :)

**Comment by DTMClanDeveloper** [comment]
thanks buddy :D

**Comment by DTMClanDeveloper** [comment]
will this work only for me? or can i make other people owner too and stuff

**Comment by NatsuTheGreat** [comment]
I was only going to add the ability for one owner, but I can make it multiple :/

**Comment by NatsuTheGreat** [comment]
I am working on chat moderation too. I have stuff on my plans too :/

**Comment by DTMClanDeveloper** [comment]
thanks bro btw when do you think it will be finished?

**Comment by NatsuTheGreat** [comment]
I am not very sure. Considering the fact I have to go now, sadly :( maybe it'll be finished around evening. (for me)

**Comment by DTMClanDeveloper** [comment]
k bro cya

**Comment by Barbosik** [comment]
Look at gameserver.ini 
You can write in serverWelcome1 or serverWelcome2 owner of server.
For example:
```
serverWelcome1 "This server is owned by DTMClanDeveloper"
```

**Comment by NatsuTheGreat** [comment]
Anyone could steal the name.

**Comment by Barbosik** [comment]
I will add login command soon, but it will works if you have chat in your client, because there is no way to login with vanilla client which has no chat support

**Comment by David1ali12** [comment]
@Barbosik  I used OgarConsole but now its broken dont work with MultiOgar you know how pain its to always open Ssh then open screen ............... it really annoying can you add Something like OgarConsole running on a port and has a password :) please  it will be easier to use

**Comment by DTMClanDeveloper** [comment]
eveyrone is using server owner name and they are all fake i want something to represent me.

**Comment by lulzyyy** [comment]
I already have this feature in my client, but only my public servers use this. Barbosik, just add something like 'adminPassword = xxxxx' to the gameserver.ini and add 'isAdmin' boolean variable to the PlayerTracker.. Then, with command '/login xxxxxx' and correct password, player becomes admin, and can execute commands. I will add client console soon.

**Comment by David1ali12** [comment]
That's Great I hope you add it, please PR it

**Comment by lulzyyy** [comment]
I made a few Pull Requests . But Barbosik must do the logging system.

**Comment by DTMClanDeveloper** [comment]
how do i update my server for the admin name thing.

**Comment by NatsuTheGreat** [comment]
I am pretty good on my chat moderation, I got the admin thing completely working. Now all I need to is change the colors to random colors, since you say most of the people use dark these on your server.

**Comment by DTMClanDeveloper** [comment]
rem lulzyyy now c0nsume me chat box doesnt work at all.

**Comment by NatsuTheGreat** [comment]
Okay, I have finished. I couldn't get rainbow colors to work, instead I made it more grey, so it's closer to being in between of light theme and dark theme. I can pull request it if I get the problem solved. :/

**Comment by DTMClanDeveloper** [comment]
the problem is c0nsume me chat stopped working i think lullzy did something, and also when u pull request what do i do? do i just re install the thing

**Comment by NatsuTheGreat** [comment]
Revert Lulzy's changes. Then IF pull reuqest doesn't commit all the changes from MultiOgar to OgarProject, and Barbosik merges it, you can safely redownload it.

**Comment by MastaCoder** [comment]
@NatsuTheGreat Which he shouldn't because it literally says if the connection is from c0nsume then the user is admin, what type of work is this lol. (Also added a random variable as well, moved the client check too..)

Don't use the new pr, it's pretty much useless.

**Comment by NatsuTheGreat** [comment]
I am making my own :) Pretty much compatible with client of all sort supporting chats. But the problem is, I am having trouble Pull Requesting.

**Comment by MastaCoder** [comment]
Make a fork of this repo, upload your changes, hit pull request on your repo :)

**Comment by NatsuTheGreat** [comment]
I click fork, my only options are OgarUL and Ogar.

**Comment by NatsuTheGreat** [comment]
I can't seem to make a fork of MultiOgar :(

**Comment by Barbosik** [comment]
**NatsuTheGreat**: it seems like github bug with forked branch. Probably there is need to remove fork dependency from MultiOgar to fix it.

**Comment by lulzyyy** [comment]
Chat on c0nsume.me is working properly now with MultiOgar 1.2.20. Server messages are orange, admin messages - red, moderator messages - green, user messages - grey.

**Comment by MastaCoder** [comment]
k.
