### ISSUE TITLE
THE PERFECT IDEA

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#124]
can we add next to the owners name [Administrator] in rainbow text? people think that i am a fake

**Comment by MastaCoder** [comment]
> in rainbow text?

not possible in vanilla.

**Comment by DTMClanDeveloper** [comment]
not in vanilla im using c0nsume.me

**Comment by MastaCoder** [comment]
Even on that, you'll need much more changes. I would highly recommend not even trying it if you don't know much JavaScript.

**Comment by Barbosik** [comment]
what is purpose for that?

**Comment by Barbosik** [comment]
duplicated: https://github.com/Barbosik/MultiOgar/issues/120

**Comment by lulzyyy** [comment]
I changes c0nsume.me chat a bit. Now server messages are orange, admin messages - red, moderator messages - green, user messages - grey. But you have to update your MultiOgar.

**Comment by Megabyte918** [comment]
people from the ogarul issues are moving here oh god why

**Comment by MastaCoder** [comment]
@Megabyte918 Yesh, guess they don't understand the consequences that are in place for every feature added.

**Comment by NatsuTheGreat** [comment]
Sadly it's because people advertise and talk about MultiOgar on OgarUL. So now he have this :/
