### ISSUE TITLE
Please add minion feature :)

### ISSUE THREAD

**Issue by MineMooreALT** [Barbosik/MultiOgar#126]
ola

**Comment by ItzLevvie** [comment]
No.

**Comment by MineMooreALT** [comment]
Please (Insert beging emoji here)

**Comment by lotfis** [comment]
i don't inderstand why they don't want add minion???!!!!!
it can make it even more popular,

**Comment by ItzLevvie** [comment]
^^ I didn't say that we could use their code.

**Comment by David1ali12** [comment]
![sdsddsd](https://cloud.githubusercontent.com/assets/17472593/16597687/e79bdfb0-4302-11e6-9693-3400121e4eac.PNG)
do you mean this

**Comment by Tmuru321** [comment]
the latter would be fine, but not be programmed  :sob: 
sorry for my English

**Comment by danielhoset27** [comment]
@David1ali12 yes where can we download this?

**Comment by David1ali12** [comment]
its made by NuclearC  we are not sharing soon will work on agario servers :D

**Comment by danielhoset27** [comment]
can you please share it to me atleast? i promise i will not give it to anyone

**Comment by David1ali12** [comment]
srry first of all I'm not owner of this second it can be used on ppl servers thats why we dont share :/

**Comment by danielhoset27** [comment]
but i am not going to use this on other servers only on my own server. you can trust me if you want

**Comment by Tmuru321** [comment]
@David1ali12 what did you study? that I wanted to learn to program

**Comment by David1ali12** [comment]
-_- I said I did not coded it
but to learn coding codecademy.com is the best

**Comment by DTMClanDeveloper** [comment]
david i was afk so i couldnt reply to your skype can u unblock me ill tell you how i got my server 24/7

**Comment by MastaCoder** [comment]
Bots won't work on servers with serverscramb- wait nope they do. Ogar-Unlimited's code is nasty. I tried to read that thing to get the rainbow out, took me 20 minutes to figure out I was looking at the wrong variables.

**Comment by David1ali12** [comment]
Ogar-unlimited sucks

**Comment by Barbosik** [comment]
please do not post duplicated issues: https://github.com/Barbosik/MultiOgar/issues/56
