### ISSUE TITLE
Current player isn't highlighted on the leaderboard

### ISSUE THREAD

**Issue by Barbosik** [Barbosik/MultiOgar#13]
Steps to reproduce:
1) join the game and play until get into leaderboard
2) check leaderboard content

Expected result: current player should be highlighted to make difference with other players

Actual result: highlight isn't applied to the current player.

**Comment by Barbosik** [comment]
fixed

**Comment by NatsuTheGreat** [comment]
I used player ID. :P

**Comment by Barbosik** [comment]
player ID was used in protocol 4. Also it was used in early protocol 5. But procol 5 and 6 uses 1 or 0 to indicate current player

**Comment by Barbosik** [comment]
looks like protocol 5 clients using cell ID, so I fixed it to send cell ID for protocol 4 and 5 and to send isMe flag for protocol 6+
