### ISSUE TITLE
Upgrade Required

### ISSUE THREAD

**Issue by ravimca49** [Barbosik/MultiOgar#130]
When i install the multiogar on my windows machine it give the Upgrade Required

![2016-07-06_145557](https://cloud.githubusercontent.com/assets/6623815/16613450/c52b2580-4389-11e6-9cd3-cf8299d168e5.png)
![2016-07-06_145637](https://cloud.githubusercontent.com/assets/6623815/16613464/d691ec3c-4389-11e6-943b-c51826c84a06.png)

How to fix this issue

**Comment by Influxx** [comment]
You need to connect to your server using a client:
https://github.com/Barbosik/MultiOgar#ogar-clients

**Comment by lulzyyy** [comment]
omfg.

**Comment by David1ali12** [comment]
go to agar.io/?ip=127.0.0.1:443

**Comment by Barbosik** [comment]
:)
