### ISSUE TITLE
Anyone can help me for decode a encrypted code !

### ISSUE THREAD

**Issue by nobsterr** [Barbosik/MultiOgar#135]
;var serverip=$(_0x1ce8[1])[_0x1ce8[0]]();function checkServer(){var _0xf6b7x3;var _0xf6b7x4=$(_0x1ce8[1])[_0x1ce8[0]]();switch(_0xf6b7x4){case _0x1ce8[3]:_0xf6b7x3= _0x1ce8[2];break;case _0x1ce8[5]:_0xf6b7x3= _0x1ce8[4];break;case _0x1ce8[7]:_0xf6b7x3= _0x1ce8[6];break;case _0x1ce8[9]:_0xf6b7x3= _0x1ce8[8];break;default:_0xf6b7x3= _0x1ce8[10]};$(_0x1ce8[12])[_0x1ce8[11]](_0xf6b7x3)}setInterval(checkServer,2000);function pingServer(){ping(serverip[_0x1ce8[27]](5))[_0x1ce8[26]](function(_0xf6b7x7){$(_0x1ce8[17])[_0x1ce8[11]](+_0xf6b7x7+ _0x1ce8[16]);if(_0xf6b7x7>= 0&& _0xf6b7x7<= 30){$(_0x1ce8[17])[_0x1ce8[20]](_0x1ce8[18],_0x1ce8[19])};if(_0xf6b7x7> 30&& _0xf6b7x7<= 60){$(_0x1ce8[17])[_0x1ce8[20]](_0x1ce8[18],_0x1ce8[21])};if(_0xf6b7x7> 60&& _0xf6b7x7<= 90){$(_0x1ce8[17])[_0x1ce8[20]](_0x1ce8[18],_0x1ce8[22])};if(_0xf6b7x7> 90&& _0xf6b7x7<= 120){$(_0x1ce8[17])[_0x1ce8[20]](_0x1ce8[18],_0x1ce8[23])};if(_0xf6b7x7> 120&& _0xf6b7x7<= 1000){$(_0x1ce8[17])[_0x1ce8[20]](_0x1ce8[18],_0x1ce8[24])};$(_0x1ce8[25])[_0x1ce8[11]](_0xf6b7x7)})[_0x1ce8[15]](function(_0xf6b7x6){console[_0x1ce8[14]](_0x1ce8[13],_0xf6b7x6)})}setInterval(pingServer,2000);function serverPlayers(){var _0xf6b7x9;var serverip=$(_0x1ce8[1])[_0x1ce8[0]]();switch(serverip){case _0x1ce8[3]:_0xf6b7x9= _0x1ce8[28];break;case _0x1ce8[5]:_0xf6b7x9= _0x1ce8[29];break;case _0x1ce8[7]:_0xf6b7x9= _0x1ce8[30];break;case _0x1ce8[9]:_0xf6b7x9= _0x1ce8[31];break;default:_0xf6b7x9= _0x1ce8[10]};$[_0x1ce8[37]](_0x1ce8[32]+ _0xf6b7x9,function(_0xf6b7x3){$(_0x1ce8[36])[_0x1ce8[11]](+_0xf6b7x3[_0x1ce8[33]]+ _0x1ce8[34]+ _0xf6b7x3[_0x1ce8[35]])})}setInterval(serverPlayers,1000);function serverPlayersButtons(){$[_0x1ce8[37]](_0x1ce8[38],function(_0xf6b7xb){$(_0x1ce8[39])[_0x1ce8[11]](_0xf6b7xb[_0x1ce8[33]]+ _0x1ce8[34]+ _0xf6b7xb[_0x1ce8[35]])});$[_0x1ce8[37]](_0x1ce8[40],function(_0xf6b7xb){$(_0x1ce8[41])[_0x1ce8[11]](_0xf6b7xb[_0x1ce8[33]]+ _0x1ce8[34]+ _0xf6b7xb[_0x1ce8[35]])});$[_0x1ce8[37]](_0x1ce8[42],function(_0xf6b7xb){$(_0x1ce8[43])[_0x1ce8[11]](_0xf6b7xb[_0x1ce8[33]]+ _0x1ce8[34]+ _0xf6b7xb[_0x1ce8[35]])});$[_0x1ce8[37]](_0x1ce8[44],function(_0xf6b7xb){$(_0x1ce8[45])[_0x1ce8[11]](_0xf6b7xb[_0x1ce8[33]]+ _0x1ce8[34]+ _0xf6b7xb[_0x1ce8[35]])})}setInterval(serverPlayersButtons,6000);function hideSkinUrl(){$(_0x1ce8[49])[_0x1ce8[48]](_0x1ce8[46],_0x1ce8[47]);$(_0x1ce8[52])[_0x1ce8[51]](_0x1ce8[50])}function showSkinUrl(){$(_0x1ce8[49])[_0x1ce8[48]](_0x1ce8[46],_0x1ce8[53]);$(_0x1ce8[55])[_0x1ce8[51]](_0x1ce8[54])}function hideTeam(){$(_0x1ce8[56])[_0x1ce8[48]](_0x1ce8[46],_0x1ce8[47]);$(_0x1ce8[58])[_0x1ce8[51]](_0x1ce8[57])}function showTeam(){$(_0x1ce8[56])[_0x1ce8[48]](_0x1ce8[46],_0x1ce8[53]);$(_0x1ce8[60])[_0x1ce8[51]](_0x1ce8[59])}deletead();function deletead(){$(_0x1ce8[62])[_0x1ce8[61]]()}$(_0x1ce8[64])[_0x1ce8[63]]();$(_0x1ce8[65])[_0x1ce8[61]]();$(_0x1ce8[66])[_0x1ce8[61]]();$(_0x1ce8[67])[_0x1ce8[61]]();$(_0x1ce8[68])[_0x1ce8[61]]();$(_0x1ce8[70])[_0x1ce8[69]]();$(_0x1ce8[70])[_0x1ce8[61]]();$(_0x1ce8[71])[_0x1ce8[61]]();$(_0x1ce8[72])[_0x1ce8[61]]();$(_0x1ce8[73])[_0x1ce8[61]]();$(_0x1ce8[74])[_0x1ce8[61]]();$(_0x1ce8[75])[_0x1ce8[61]]();$(_0x1ce8[77])[_0x1ce8[51]](_0x1ce8[76]);$(_0x1ce8[80])[_0x1ce8[79]](_0x1ce8[78]);$(_0x1ce8[81])[_0x1ce8[79]](_0x1ce8[78]);$(_0x1ce8[1])[_0x1ce8[83]](_0x1ce8[82]);$(_0x1ce8[85])[_0x1ce8[83]](_0x1ce8[84]);$(_0x1ce8[1])[_0x1ce8[51]](_0x1ce8[86]);$(_0x1ce8[87])[_0x1ce8[51]](_0x1ce8[76]);$(_0x1ce8[88])[_0x1ce8[61]]();$(_0x1ce8[89])[_0x1ce8[83]](_0x1ce8[84]);$(_0x1ce8[49])[_0x1ce8[83]](_0x1ce8[84]);$(_0x1ce8[92])[_0x1ce8[91]](_0x1ce8[90]);$(_0x1ce8[94])[_0x1ce8[83]](_0x1ce8[93]);$(_0x1ce8[54])[_0x1ce8[91]](_0x1ce8[49]);$(_0x1ce8[59])[_0x1ce8[91]](_0x1ce8[89]);$(_0x1ce8[97])[_0x1ce8[96]](_0x1ce8[95]);$(_0x1ce8[97])[_0x1ce8[96]](_0x1ce8[98]);$(_0x1ce8[93])[_0x1ce8[96]](_0x1ce8[99]);$(_0x1ce8[93])[_0x1ce8[96]](_0x1ce8[100]);$(_0x1ce8[93])[_0x1ce8[96]](_0x1ce8[101]);$(_0x1ce8[103])[_0x1ce8[96]](_0x1ce8[102]);$(_0x1ce8[105])[_0x1ce8[96]](_0x1ce8[104]);$(_0x1ce8[107])[_0x1ce8[96]](_0x1ce8[106]);$(_0x1ce8[105])[_0x1ce8[96]](_0x1ce8[108]);$(_0x1ce8[110])[_0x1ce8[96]](_0x1ce8[109]);$(_0x1ce8[110])[_0x1ce8[96]](_0x1ce8[111]);$(_0x1ce8[110])[_0x1ce8[96]](_0x1ce8[112]);$(_0x1ce8[107])[_0x1ce8[96]](_0x1ce8[113]);$(_0x1ce8[107])[_0x1ce8[96]](_0x1ce8[114]);$(_0x1ce8[107])[_0x1ce8[96]](_0x1ce8[115]);$(_0x1ce8[80])[_0x1ce8[20]](_0x1ce8[116],_0x1ce8[117]);$(_0x1ce8[56])[_0x1ce8[48]](_0x1ce8[118],_0x1ce8[119]);$(_0x1ce8[94])[_0x1ce8[83]](_0x1ce8[105]);$(_0x1ce8[121])[_0x1ce8[48]](_0x1ce8[120],$(_0x1ce8[49])[_0x1ce8[0]]());window[_0x1ce8[127]](function(){$(_0x1ce8[126])[_0x1ce8[11]](function(_0xf6b7x11,_0xf6b7x12){return _0xf6b7x12[_0x1ce8[125]](_0x1ce8[124])[_0x1ce8[123]](_0x1ce8[122])})},20);$(_0x1ce8[49])[_0x1ce8[129]](function(){$(_0x1ce8[121])[_0x1ce8[48]](_0x1ce8[120],(this[_0x1ce8[128]]))});$(_0x1ce8[130])[_0x1ce8[0]](_0x1ce8[3]);connect(_0x1ce8[3]);localStorage[_0x1ce8[132]](_0x1ce8[131]);document[_0x1ce8[133]]= _0x1ce8[134];$(document)[_0x1ce8[135]](function(){serverPlayersButtons()})

**Comment by MastaCoder** [comment]
Pretty sure if it's encrypted, the developer doesn't want you to find out what it is in the first place. Use JXBeutifier, it's the furthest you can go.

**Comment by nobsterr** [comment]
its agarlist.com/agarlist.js

**Comment by NatsuTheGreat** [comment]
http://pastebin.com/NJBwhBFS

**Comment by nobsterr** [comment]
http://agarlist.com/agarlist.js ? anyone can give me full code decode? is so hard for me

**Comment by nobsterr** [comment]
@NatsuTheGreat @MastaCoder  Can help me?

**Comment by MastaCoder** [comment]
> Pretty sure if it's encrypted, the developer doesn't want you to find out what it is in the first place.

**Comment by David1ali12** [comment]
why you want the code of it -_-

**Comment by liomessip** [comment]
I love this client , and only just learning javascript :(

**Comment by David1ali12** [comment]
I hate those who use Multi Accounts to make issues 
this code is for stats only,

**Comment by NatsuTheGreat** [comment]
If they'd know :/

**Comment by Barbosik** [comment]
not relevant for the project

**Comment by NatsuTheGreat** [comment]
>not relevant for the project

Thank you.
