### ISSUE TITLE
Place your request here

### ISSUE THREAD

**Issue by nobsterr** [Barbosik/MultiOgar#136]
Request:

Pattern:

- Request 
 reason

Add minions 

reason : For More Funny

**Comment by nobsterr** [comment]
- Add Minios

Reason : For More Funny

**Comment by inxlio** [comment]
- Minimap 

Reason : This would help much

**Comment by liomessip** [comment]
- SkinChanger

Reason : Really good

**Comment by liomessip** [comment]
- Plugins

Reason : More features

**Comment by MastaCoder** [comment]
> Add Minions

no.

> Minimap

Client.

> SkinChanger

Supported.

> Plugins

Debatable.

**Comment by NatsuTheGreat** [comment]
>SkinChanger
Unfortunately, this will malfunction. Skins won't change, unless a new cell is created.

**Comment by Barbosik** [comment]
skin change for existing cell is not supported because it will leads to high server lags and will confuse players

**Comment by NatsuTheGreat** [comment]
>skin change for existing cell is not supported because it will leads to high server lags and will confuse players

100% agreed. The lag will only increase because of the interval to change skins. Not what MultiOgar wants :)
