### ISSUE TITLE
they can add Skinchanger ?

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#138]
title^^

**Comment by MastaCoder** [comment]
?

Skin protocol is supported.

**Comment by liomessip** [comment]
SkinCHANGER , LIKE PLUGIN OGARUNLIMITED SKINCHANGER

**Comment by fodse** [comment]
Oh boy, the autistic unecessary issues plague is taking over MultiOgar. First OgarUl, now here. The world is in danger.

**Comment by NatsuTheGreat** [comment]
:/ today we went from about 15 issues to 30 :/

**Comment by MastaCoder** [comment]
@liomessip Do some research.

**Comment by Barbosik** [comment]
skins already supported

**Comment by liomessip** [comment]
AUTOSKINCHANGER !!

**Comment by liomessip** [comment]
SKIN CHANGE AUTOMATICALLY .. THIS I MEAN

**Comment by MastaCoder** [comment]
client sided

**Comment by liomessip** [comment]
not client , in ogarUL IS A PLUGIN !! SKINCHANGERRR

**Comment by NatsuTheGreat** [comment]
Chill.

**Comment by MastaCoder** [comment]
@liomessip Still useless if you ask me. MultiOgar isn't for you if you're looking for useless features.

**Comment by Barbosik** [comment]
if you want something like skinchanger, use ogarul. The goal of MultiOgar is a fast and smooth physics. skinchanger is incompatible with MultiOgar, because it needs to remove optimizations and make server more laggy.

**Comment by NatsuTheGreat** [comment]
^^ True. Both of you I agree.
