### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#14]
It sometimes lag slowly.
Please fix it.

**Comment by NatsuTheGreat** [comment]
Can you specify? Like when it happens? Pretty sure Barbosik has done refactoring to make performance better.

**Comment by Chancerst** [comment]
@NatsuTheGreat When it lag, game is slow.
sometimes it return, But it lag again.

**Comment by Barbosik** [comment]
I'm working on performance, but first I want to fix game physics.
There are at least two physics things that should be fixed:
- split/eject movement;
- mass/inertia dependency

**Comment by Chancerst** [comment]
@Barbosik oh.. thank you!

**Comment by Chancerst** [comment]
@Barbosik Maybe i think you should see a short lag video for know this problem.
[bandicam 0054.zip](https://github.com/Barbosik/MultiOgar/files/304045/bandicam.0054.zip)

**Comment by F0RIS** [comment]
@Chancerst it's from bots using

**Comment by Barbosik** [comment]
I think it's fixed now. Current MultiOgar has a fairly good performance for private servers.

**Comment by Chancerst** [comment]
@Barbosik um.. This is weird. Still it lag and slow again.
i don't know this problem..
[bandicam 0056.zip](https://github.com/Barbosik/MultiOgar/files/306249/bandicam.0056.zip)

**Comment by Barbosik** [comment]
It lags because GameServer.getCellsInRange consumes almost all cpu time, it's slow.
So, if you want, you can rewrite it. It lags when there are a lot of colliding cells.
Just don't use too many bots and it will works fine.
10 bots works ok.

**Comment by Chancerst** [comment]
@Barbosik i use 16 bots.
size vanilla agar.io size (14142).
i use FoodStartamount: 1500, Max: 2000.
I use cpu AMD FX(tm)-8300 Eight-core Proccessor.

**Comment by Barbosik** [comment]
do you have lags with no bots?
What is your gameserver.ini?

**Comment by Chancerst** [comment]
@Barbosik My gameserver.ini is

// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// serverStatsPort: Port for the stats server. Having a negative number will disable the stats server.
// serverStatsUpdate: Amount of seconds per update for server stats
// serverLogLevel: Logging level of the server. 0 = No logs, 1 = Logs the console, 2 = Logs console and ip connections
// serverScrambleCoords: Toggles scrambling of coordinates. 0 = No scrambling, 1 = scrambling. Default is 1.
// serverMaxLB: Controls the maximum players displayed on the leaderboard.
serverMaxConnections = 64
serverPort = 443
serverGamemode = 0
serverBots = 16
serverViewBaseX = 1920
serverViewBaseY = 1080
serverStatsPort = 88
serverStatsUpdate = 60
serverLogLevel = 1
serverScrambleCoords = 1
serverMaxLB = 10

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 14142.135623730952)
borderLeft = 0
borderRight = 14142
borderTop = 0
borderBottom = 14142

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 20
foodSpawnAmount = 50
foodStartAmount = 1500
foodMaxAmount = 2000
foodMass = 1
foodMassGrow = 1
foodMassGrowPossiblity = 50
foodMassLimit = 5
foodMassTimeout = 120
virusMinAmount = 20
virusMaxAmount = 35
virusStartMass = 100
virusFeedAmount = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassCooldown: Tick count until a player can eject mass again (1 tick = 40 ms)
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 13
ejectMassCooldown = 3
ejectMassLoss = 14
ejectSpeed = 100
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerBotGrowEnabled: If 0, eating a cell with less than 17 mass while cell has over 625 wont gain any mass
// playerMassAbsorbed: Fraction of a player cell that gets absorbed upon eating (i.e., 1 = 100%, 0.8 = 80%, etc)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur
// playerDisconnectTime: The amount of seconds it takes for a player cell to be removed after disconnection (If set to -1, cells are never removed)
// playerSpeed: Player speed multiplier (1=normal speed, 2=twice faster)
playerStartMass = 155
playerBotGrowEnabled = 1
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 35
playerMaxCells = 16
playerRecombineTime = 30
playerMassAbsorbed = 1.0
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15
playerSpeed = 1
playerDisconnectTime = 5

// [Gamemode]
// Custom gamemode settings
// tourneyTimeLimit: Time limit of the game, in minutes.
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyTimeLimit = 20
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1


And I'll test When no bots it doesn't have lag.

**Comment by Barbosik** [comment]
try the latest version. I missed some detail from documentation about buffer allocation, so I fixed it.
I'm not sure if it helps

**Comment by Chancerst** [comment]
@Barbosik ok. I will try new version

PS. When i remove bot, it didn't lag :0..

**Comment by Chancerst** [comment]
@Barbosik it Also lag ..

**Comment by Barbosik** [comment]
check the latest version, please let me know if it resolve your issue

**Comment by Chancerst** [comment]
@Barbosik It looks like fixed.
Thank you!
But if it have lag again, I'll tell you.
