### ISSUE TITLE
input for skin in custom client

### ISSUE THREAD

**Issue by Dramex** [Barbosik/MultiOgar#145]
Hi, 
how can i put an input for skin beside the nickname, and how i link it with the server
and how its get the skin after all for the player without any change with the nickname

what the changes i could made to do that
Thank you!

**Comment by MastaCoder** [comment]
Get the server packet sent and handle it to change the players skin based on the value received.

**Comment by Dramex** [comment]
@MastaCoder Example please, which codes i can use to send and receive

**Comment by MastaCoder** [comment]
``var skinText = "";
            if (flags & 4) {
               for (; ;) { // skin name
                   t = view.getUint8(offset, true) & 0x7F;
                   offset += 1;
                   if (0 == t) break;
                   skinText += String.fromCharCode(t);
               }
            }``

Based on what @Barbosik used in his protocol tutorial.

**Comment by Barbosik** [comment]
you can send chat command
```
/skin %kraken
```

**Comment by Dramex** [comment]
@Barbosik could you check your email please :)

Thank you.

**Comment by Barbosik** [comment]
ok
