### ISSUE TITLE
UserRoles whattt ?

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#146]
Hello , Users Roles is useless

Administrators have no difference with users

not have commands or identifier

**Comment by Barbosik** [comment]
It useless for you, but someone may want to make player commands which is not available for all players, but don't want to allow some commands for these users

**Comment by Barbosik** [comment]
Currently there is no player commands which require some permission. But you can add your own commands

**Comment by ZiityV** [comment]
@Barbosik How i do that
