### ISSUE TITLE
i need a really sick cozy client 

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#147]
title

**Comment by Barbosik** [comment]
not relevant to the project

**Comment by lulzyyy** [comment]
omfg. what's wrong with these people...

**Comment by Megabyte918** [comment]
@DTMClanDeveloper why do you keep making issues for stupid stuff this wasn't even issue-worthy, you could have just commented it on a closed issue or something. this is like your 5th issue jesus christ
