### ISSUE TITLE
SplitDistance and SplitSpeed not same than agar.io ACTUALLY IN MULTIOGAR

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#148]
I can change splitDISTANCE and splitSPEED ? ACTUALLY IN MULTIOGAR NOT SAME THAN AGARIO

where i can change?

what is the configuration of agar.io?

**Comment by liomessip** [comment]
i believe that playerSpeed = 1.4 it is more like agario that playerSpeed = 1

**Comment by Barbosik** [comment]
split distance is exactly the same as on vanilla.

**Comment by liomessip** [comment]
and splitspeed ?

**Comment by Barbosik** [comment]
yes

**Comment by NatsuTheGreat** [comment]
I changed my splitting, a lot of it.
