### ISSUE TITLE
Cannot connect to server.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#15]
Okay, so today I tried opening MY server (which does work) but it wouldn't let me connect. I thought it was my port messing up, tried it with localhost... Still no connection. Just "Connecting..." Then I tried it with a very fresh MultiOgar. Still doesn't work... Any help please?

**Comment by Barbosik** [comment]
they changed protocol to 8 and enabled encryption for /?ip=127.0.0.1
May be they just forgot to disable encryption for private servers. If so, they will fix it soon.

Anyway you can use MultiOgar with a big variety of ogar clients.

**Comment by NatsuTheGreat** [comment]
Dangit! Really?! A new protocol change? What else does the protocol change include?

**Comment by Barbosik** [comment]
You can use MultiOgar with a big variety of different ogar clients.
For example you can use http://ogar.mivabe.nl/?ip=127.0.0.1:50000

Also, here is private server list: http://ogar.mivabe.nl/master
I will add automatic support for this master server in MultiOgar.
So, if you want, your server will be automatically published on http://ogar.mivabe.nl/master

**Comment by NatsuTheGreat** [comment]
Alright, but may I please know the changes applied in protocol 8?

**Comment by Barbosik** [comment]
at a glance the protocol is the same as 6, just a little change in key generation and disabled support of private servers. I think that disable private servers is a bug, if so, they will fix it soon.

**Comment by NatsuTheGreat** [comment]
I really hope so.

**Comment by NatsuTheGreat** [comment]
Can you report back if you find anything?

**Comment by Barbosik** [comment]
Actually protocol 8 is the same as protocol 7, but they added a new message 0xE2 (3 byte length). 
Currently I have no idea what it means.

**Comment by NatsuTheGreat** [comment]
Could that be the reason servers aren't working?

**Comment by Barbosik** [comment]
no, they just disabled private servers. I hope they will fix it soon

**Comment by NatsuTheGreat** [comment]
I really hope too, don't want to have to play over crowded agar.io parties or nothing again.

**Comment by Barbosik** [comment]
I added fix to use protocol 8 without encryption. So if their client will be fixed it will works.
I can add encryption just to bypass all these protections, but this fix will reveal info which can be used by botters, so they return back again.

**Comment by NatsuTheGreat** [comment]
It seems that I am unable to connect to Official Agar.io.

**Comment by NatsuTheGreat** [comment]
K, connected now.

**Comment by NatsuTheGreat** [comment]
@Barbosik It's not the fact that private servers aren't supported anymore, it's our code. This is [OgarProject/Ogar](http://prntscr.com/bdmuck) Works fine.

**Comment by Barbosik** [comment]
how did you make it to work?

**Comment by NatsuTheGreat** [comment]
Just downloaded OgarProject man. I am not a pro in packets like you.

**Comment by Barbosik** [comment]
hm, nice finding, need to fix it :)

**Comment by NatsuTheGreat** [comment]
Very upsetting that my private server is yet again gone.

**Comment by Barbosik** [comment]
lol, I just forgot to update condition for UpdateNodes packet :)

fixed, now it works

**Comment by NatsuTheGreat** [comment]
Thank you very much :D
