### ISSUE TITLE
All IPs are displayed in IPv6 Format and Breaks Banning Feature

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#151]
I wanted to ban myself, so I banned my IP address.  However, the IP list is listing only in IPv6 format regardless of the IP format.

```
 ID     | IP              | P | NICK            | CELLS | SCORE  | POSITION
-------------------------------------------------------------------------------
      1 | ::ffff:181.xx.xx.xxx | 5 | [REDACTED]      |     1 |  14070 | -8264,  3372
```

All the IPs starts with `::ffff:`, and it breaks the table format.

This scares me because it can allow bot providers to connect to the server and throw bots around once again.

P.S. OVH (the VPS server I use) only gave me IPv4 address, so IPv6 is basically useless for this server as of now.

**Comment by Barbosik** [comment]
hm, it's a bug

**Comment by Barbosik** [comment]
fixed
