### ISSUE TITLE
Border Source

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#152]
This is old border source:
        // Find center
        var width = gameServer.config.borderRight - gameServer.config.borderLeft;
        var height = gameServer.config.borderBottom - gameServer.config.borderTop;
        this.centerPos.x = gameServer.config.borderLeft + width / 2;
        this.centerPos.y = gameServer.config.borderTop + height / 2;
        // Player id
        this.pID = gameServer.getNewPlayerID();
        // Gamemode function
        gameServer.gameMode.onPlayerInit(this);
        // Only scramble if enabled in config
        if (gameServer.config.serverScrambleCoords == 1) {
            // avoid mouse packet limitations
            var maxScrambleX = Math.max(0, 32767 - 2000 - width / 2);
            var maxScrambleY = Math.max(0, 32767 - 2000 - height / 2);
            this.scrambleX = Math.floor(maxScrambleX * Math.random());
            this.scrambleY = Math.floor(maxScrambleY * Math.random());
        }
        this.scrambleId = (Math.random() * 0xFFFFFFFF) >>> 0;

![default](https://cloud.githubusercontent.com/assets/19770308/16679184/7ef3c4e4-4520-11e6-942f-2fbd3a11c7fb.png)
![1](https://cloud.githubusercontent.com/assets/19770308/16679183/7ef0b6d2-4520-11e6-94a4-e38ff372591c.png)

it works agarplus.io and other source correctly.

But now, i think you rewritten border code, so it doesn't work other clients.

can you fix it, please?
I opened 24 hours server, but it is old serverpack.. so it has some bug and lag.

(i think you deleted border top, left, right, bottom, so it doesn't work)

**Comment by Barbosik** [comment]
current MultiOgar implementation works correctly. If you have issue in some client, it's because border calculations in your client is incorrect.

**Comment by Chancerst** [comment]
@Barbosik umm
is coords 3 have border top,left,right,bottom source?

**Comment by Barbosik** [comment]
yes, but it's not available in configuration. 
You can configure border with borderWidth and borderHeight.
Other things will be calculated by server to prevent user mistakes and mouse control bugs.

**Comment by Chancerst** [comment]
@Barbosik uu.. i use old serverpack scramble coords 0. it's work correctly
but now when i try coords 0, it doesn't work.
must i use old pack forever?

**Comment by Barbosik** [comment]
no, your client works with old ogar server because it used shifted map with top=left=0.
It's incorrect and leads to mouse control bugs.

**Comment by Chancerst** [comment]
@Barbosik Pleader fix them the correct calculations XD
[agarplus_v2m6.zip](https://github.com/Barbosik/MultiOgar/files/353726/agarplus_v2m6.zip)

i will wait you.. ㅠㅠ

**Comment by Barbosik** [comment]
it's not relevant to this project

**Comment by Chancerst** [comment]
@Barbosik it's not agarplus developer,
Just i have only one way..
So i use old pack :)
Thank you for answer this issue

**Comment by MastaCoder** [comment]
https://github.com/Barbosik/MultiOgar/issues/66

**Comment by Chancerst** [comment]
@MastaCoder I don't know what they are talking..
But i think to fix way is add scramble 4 level. ( older than rewritten border structure)

**Comment by Barbosik** [comment]
There is nothing to fix in the server code, because it works as expected.
The bug in your client and you cannot fix client bug in the server code.

**Comment by Chancerst** [comment]
@Barbosik Yes, your Server is perfect pack. :)
i didn't wish fix, just i wanted border top, left, right, bottom source with scramble 4.
old serverpack (before rewritten border structure) was good for my client.
if you think don't have to add it, i will use old.
now i think you were very tired.
Sorry

**Comment by Barbosik** [comment]
MultiOgar sends border left, top, right and bottom with any serverScrambleLevel

**Comment by Chancerst** [comment]
It works scramble 0 with old pack.
but now it doensn't work with level 0.
i think when you rewritten code, you rewrited border calculation code differently.

old: 
var width = gameServer.config.borderRight - gameServer.config.borderLeft;
var height = gameServer.config.borderBottom - gameServer.config.borderTop;
this.centerPos.x = gameServer.config.borderLeft + width / 2;
this.centerPos.y = gameServer.config.borderTop + height / 2;
// Player id
this.pID = gameServer.getNewPlayerID();
// Gamemode function
gameServer.gameMode.onPlayerInit(this);
// Only scramble if enabled in config
if (gameServer.config.serverScrambleCoords == 1) {
// avoid mouse packet limitations
var maxScrambleX = Math.max(0, 32767 - 2000 - width / 2);
var maxScrambleY = Math.max(0, 32767 - 2000 - height / 2);
this.scrambleX = Math.floor(maxScrambleX * Math.random());
this.scrambleY = Math.floor(maxScrambleY * Math.random());
}
this.scrambleId = (Math.random() * 0xFFFFFFFF) >>> 0;


now: 
if (!this.gameServer.config.serverScrambleLevel) {
        this.scrambleId = 0;
        this.scrambleX = 0;
        this.scrambleY = 0;
    } else {
        this.scrambleId = (Math.random() * 0xFFFFFFFF) >>> 0;
        // avoid mouse packet limitations
        var maxx = Math.max(0, 32767 - 1000 - this.gameServer.border.width);
        var maxy = Math.max(0, 32767 - 1000 - this.gameServer.border.height);
        var x = maxx * Math.random();
        var y = maxy * Math.random();
        if (Math.random() >= 0.5) x = -x;
        if (Math.random() >= 0.5) y = -y;
        this.scrambleX = x;
        this.scrambleY = y;
    }
    this.borderCounter = 0;

it works grid location > OgarServ, MultiOgar old version, Ogar unlimited...
it almost possible configure border top, left, right, bottom size.

Umm, i want to say good english, but i can't. So i say again.
Please add the old border source with scramble 4.

then, it works perfectly.

**Comment by Barbosik** [comment]
I cannot add bug which you're talking about, because it was fixed to remove random server crashes and mouse control bugs.

**Comment by Chancerst** [comment]
@Barbosik Thanks. I changed source. So it fixed :)

**Comment by MastaCoder** [comment]
is that the agarplus code on your website..?

**Comment by Barbosik** [comment]
@MastaCoder: he using agarplus script infected with spyware. It sends each your action, all your cell updates and other things to ws://agar-ss.ddo.jp:9655
Someone who added spyware hooks made it very inaccurate. For example, border is hardcoded. Some important parts of code commented and replaced with invalid alternatives.
