### ISSUE TITLE
I need change speed of splits

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#154]
title^^ pls need more faster , NO PLAYERSPEED , i need change only speedsplits , thx

**Comment by MastaCoder** [comment]
It's in the code. I remember working with the eject speed and it's something with boost. I'll find it and update this post.

**Comment by liomessip** [comment]
thx

**Comment by lulzyyy** [comment]
Your wrong @MastaCoder , there is the line to change https://github.com/Barbosik/MultiOgar/blob/master/src/entity/Cell.js#L169 

change this line to var speed = 700; (for example)

**Comment by lulzyyy** [comment]
To make it work, you have to change this function https://github.com/Barbosik/MultiOgar/blob/master/src/entity/Cell.js#L162 to

`Cell.prototype.move = function (border) {
    if (this.isMoving && this.boostDistance <= 0) {
        this.boostDistance = 0;
        this.isMoving = false;
        return;
    }
    var speed = Math.sqrt(this.boostDistance * this.boostDistance / 100);
    //var speed = Math.max(speed, 78);                // limit max speed with sqrt(780*780/100)
    speed = Math.min(speed, this.boostDistance);    // avoid overlap 0
	var customDistance = 2; // 1 - normal distance, 2 - two times longer distance etc.
    this.boostDistance -= speed/customDistance; // longer splits
    if (this.boostDistance < 1) this.boostDistance = 0;
    
    var v = this.clipVelocity(
        { x: this.boostDirection.x * speed, y: this.boostDirection.y * speed }, 
        border);
    this.position.x += v.x;
    this.position.y += v.y;
    this.checkBorder(border);
}`
