### ISSUE TITLE
Linesplit not working

### ISSUE THREAD

**Issue by inxlio** [Barbosik/MultiOgar#155]
title^^

**Comment by inxlio** [comment]
thanks for your help

**Comment by Barbosik** [comment]
please do not post duplicated issues. If you want to say something about it, use existing issue: https://github.com/Barbosik/MultiOgar/issues/62

**Comment by Megabyte918** [comment]
Im so sorry you have to deal with this

**Comment by NatsuTheGreat** [comment]
This guy has made like 20+ issues overall. He could be just like you mega, and list his issues in a list format. In ONE issue.

**Comment by NatsuTheGreat** [comment]
But I really do want linesplit fixed.
