### ISSUE TITLE
How to make fb skins and fb connect available?

### ISSUE THREAD

**Issue by bean07** [Barbosik/MultiOgar#16]
like title

**Comment by Barbosik** [comment]
fb token is not available for private servers with vanilla client. So, fb login impossible.
The same thing with skin and name. Such information stored on vanilla servers, and not available for private servers.

**Comment by bean07** [comment]
><shark> Bean07
<shark> Bean07
[Console] Invalid Command!
>

**Comment by bean07** [comment]
> < shark > Bean07
< shark > Bean07
[Console] Invalid Command!
>

**Comment by Barbosik** [comment]
it's not console command, it's player name which should be entered in the player name input box
