### ISSUE TITLE
mega split not working!

### ISSUE THREAD

**Issue by Dramex** [Barbosik/MultiOgar#162]
Hi, 

we used to use 
playerRecombineTime : -1000 
on ogar to make the server support very fast split as this video :
https://www.youtube.com/watch?v=6mmhgg0FOT0

when i tried MultiOgar its stops the split !! , i cant split anymore

so any help about this ?

same problem was on ogar-unlimited :
https://github.com/AJS-development/Ogar-unlimited/issues/1177

**Comment by Barbosik** [comment]
I don't recommend to set playerRecombineTime < 0. The minimum value is 0.

**Comment by Dramex** [comment]
i tried : playerRecombineTime = 0; its mega split :+1:  
it was not in other modifications of ogar

Thats awesome, thank you and sorry about that

**Comment by Dramex** [comment]
there a delay in playerRecombineTime = 0, like 1 second, its different from the youtube video i posted .
how i get a real instant merge .

another viedo : 
https://www.youtube.com/watch?v=6mxTeuSegA8

**Comment by Barbosik** [comment]
you can remove it by remove the following two code blocks:
1) https://github.com/Barbosik/MultiOgar/blob/master/src/GameServer.js#L873-L877
2) https://github.com/Barbosik/MultiOgar/blob/master/src/GameServer.js#L903-L907
