### ISSUE TITLE
Good Suggest

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#165]
Name: Split rigid Smoother = 1
(0: Smooth split rigid speed than vanilla. (it slow when restore than 1), 1: Agar.io Vanilla rigid speed when restore)
Older Vanilla Agar.io have some more smoother rigid than now. (See the april version agar.io split run movie)

So, i suggest you.

**Comment by NatsuTheGreat** [comment]
No just no...

**Comment by SimonOrJ** [comment]
What do you mean by "rigid"?

**Comment by Barbosik** [comment]
It's not so clear what you're talking about, and you didn't provided more details, so I'm closing the issue
