### ISSUE TITLE
Would it be possible?

### ISSUE THREAD

**Issue by XtremePlayzCODE** [Barbosik/MultiOgar#167]
Would it be possible to add these?

1. Minions

**Comment by MastaCoder** [comment]
> 2. Minions, duh!

I will take a shot for every time I have heard this and had to say no.

**Comment by XtremePlayzCODE** [comment]
true

**Comment by Megabyte918** [comment]
That </random> suggestion would actually be pretty cool, then I could have custom bot names and I wouldn't have to give each and every one a different skin =D

And btw skins do work

**Comment by XtremePlayzCODE** [comment]
Ah. I will take it off then

**Comment by David1ali12** [comment]
`</random>``/random` is easy If I have time to make it I will PR it

**Comment by NatsuTheGreat** [comment]
No lets not make MultiOgar like OgarUnlimited... PLEASE NO.

**Comment by David1ali12** [comment]
nvm its useless

**Comment by XtremePlayzCODE** [comment]
i just want minions now...

**Comment by DaAwesomeRazor** [comment]
yeah minions would be cool. If I have time I can make a pull request

**Comment by XtremePlayzCODE** [comment]
1. OMG RAZOR
2. Please do

**Comment by Megabyte918** [comment]
It wont be merged lol

**Comment by XtremePlayzCODE** [comment]
True, but i can download that version with the commit >:D

**Comment by NatsuTheGreat** [comment]
Also true, just download the branch of who ever makes the commit :)

**Comment by Barbosik** [comment]
You can use ogarul or other servers which supports minion.
MultiOgar is designed for multiplayer game, but not for botplayer game.
