### ISSUE TITLE
Small request.

### ISSUE THREAD

**Issue by MastaCoder** [Barbosik/MultiOgar#168]
Can you add my current client to the clients section? Currently only supports protocol 4, a bit broken on protocol 5 (as it can only support 5 on OgarServ). 

http://abs0rb.me/?ip=yourIP:port (same as Agar.io)

Planning on supporting protocol 5 very soon. :)

**Comment by XtremePlayzCODE** [comment]
OMFG ITS MAKAN!!!

**Comment by XtremePlayzCODE** [comment]
YOUAGAR???
