### ISSUE TITLE
Score is inconsistant

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#17]
When a player is split into many pieces, the score skyrockets.
```
>pl
[Console] Showing 4 players:
 ID         | IP              |   | NICK            | CELLS | SCORE  | POSITION
-----------------------------------------------------------------------------------
          2 |                 | 8 | TROLL           |     3 |  10008 |  1745,  4124
          3 |                 | 8 | ----------------------------DEAD OR NOT PLAYING
          4 |                 | 8 | x               |     3 |  25615 |  7413,  9706
          5 |                 | 8 | ----------------------------DEAD OR NOT PLAYING
>pl
[Console] Showing 4 players:
 ID         | IP              |   | NICK            | CELLS | SCORE  | POSITION
-----------------------------------------------------------------------------------
          2 |                 | 8 | TROLL           |    23 |  30385 |  6779,   525
          3 |                 | 8 | ----------------------------DEAD OR NOT PLAYING
          4 |                 | 8 | x               |    50 | 111298 |  6519, 16584
          5 |                 | 8 | ----------------------------DEAD OR NOT PLAYING
```

The two samples were taken less than 1 second apart.  Nobody was teaming.

**Comment by Barbosik** [comment]
nice finding, it's a bug :)

**Comment by Barbosik** [comment]
fixed

**Comment by SimonOrJ** [comment]
Thank you!  You're really on fire with MultiOgar! :o
Score was important not only for the leaderboard, but for a modified code that relies on the total mass of a player.  Thank you.

**Comment by F0RIS** [comment]
I am glad too see that people use my aliase "pl" )))) Agree wiith @SimonOrJ. Barbosik fix and write code very fast)

**Comment by Barbosik** [comment]
**SimonOrJ**: it seems that you're using some mod for ejected mass.

I'm planning to fix and optimize eject and split behavior, it will include removal of the following Cell properties:
- Cell.moveEngineTicks
- Cell.moveEngineSpeed
- Cell.angle

It will be replaced with another logic, which will use ejectDistance and ejectDirection instead of ticks/speed/angle.
How did it affect your mod?
