### ISSUE TITLE
How to implement OgarPlus on my server without download ? like agarlist

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#173]
Anyone can do a tutorial or help me ? please , like agarlist.com

**Comment by NatsuTheGreat** [comment]
What are you even talking about?

**Comment by Barbosik** [comment]
not relevant for the project

**Comment by MastaCoder** [comment]
The title sounds like "Can I run OgarPlus without downloading it?" :dancer:

**Comment by NatsuTheGreat** [comment]
Awesome right? :D
