### ISSUE TITLE
Banning by common name (and server connect time)?

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#175]
I've encountered an extremely unpleasantly annoying collection of bots that come from multiple IP addresses.  Their network was all different, but they all had the same name.  They all connected and disconnected at the same time, so I had to refine the IPs from the log to ban them.

How does banning by common name and server connect time sound?  It looks like bots in Agario is becoming more intrusive in finding ways around the official Agario's ban on bots.

**Comment by Barbosik** [comment]
I caught the same. Currently thinking on how to block it

**Comment by Barbosik** [comment]
implemented

**Comment by SimonOrJ** [comment]
Welp, it failed. ._.

**Comment by Barbosik** [comment]
Any details? 
You can tune `serverMinionThreshold` and `serverMinionInterval` values if default settings works bad.
serverMinionThreshold - is a count of connections in short time period (specified in serverMinionInterval) which will be treated as minion connections
will be treated as minions

**Comment by SimonOrJ** [comment]
I think the player can always get around it by increasing the interval everytime.  I think this is a fair idea, but I fancy banning by common names better.  It also gets false-positives.

**Comment by Barbosik** [comment]
by increasing interval they give you a time to ban the botter.

Kick by name from blacklist is also good idea, will be implemented soon. But it cannot help to fight against botters, because it's not so hard to make random name for bots.

**Comment by SimonOrJ** [comment]
All the bots originated from a common client, "cellcraft.io".  I think banning by client would be useful as well.

**Comment by Barbosik** [comment]
you can set any string in origin header. It's not a problem for botters to use "agar.io" string instead of "cellcraft.io" string. But as a "kid protection" it can works.

**Comment by SimonOrJ** [comment]
Big small private servers encounter the same problem, huh... ._.
