### ISSUE TITLE
Make different splitspeeds for different sizes

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#178]
splitspeed for 5000 of mass
splitspeed for 10k of mass 

something like :+1: 

if (cellMass => 5000)

splitspeed(58);

{

and so on

it is like ogarUL

**Comment by ItzLevvie** [comment]
No.

**Comment by liomessip** [comment]
why

**Comment by Megabyte918** [comment]
because the current split speed fits all sizes

**Comment by NatsuTheGreat** [comment]
No, we are not going to use what OgarUL, nor does anyone want all those annoying if statements.
@Barbosik Close, please?

**Comment by Barbosik** [comment]
I don't want to add a bunch of `if` statements and thousands of config variables just to support some stupid and useless features. Because it add lags, ruins physics and make server configuration too hard.

**Comment by NatsuTheGreat** [comment]
Thanks for speaking the truth. :)
