### ISSUE TITLE
More customization

### ISSUE THREAD

**Issue by liomessip** [Barbosik/MultiOgar#181]
Please make a version with more customization 

with a option say : CustomComands = 1 // if 1 the customcomands will activate , if 0 be original configuration

CUSTOMCOMANDS

SplitSpeed // change the velocity of splits
SplitDistance // change distance of splits
VirusShootDistance // change distance when at throw the virus
VirusSpeed //  change speed when at throw the virus
PlayerVelocity // Velocity of players
ExperimentalVirusSize // Size of experimental virus
ExperimentalVirusGiveMassPerMS // Amount of balls throw the experimental virus ( per ms)
Shrinks // The map shrinks
SplitSpeedVersion // Make a different splitSpeed for diferet sizes
EjectVirus // The player throw a virus instead of balls

**Comment by Megabyte918** [comment]
![capture](https://cloud.githubusercontent.com/assets/17245196/16779022/94354a5a-483e-11e6-907f-8e00b123ec7d.PNG)
Can you stop, please

**Comment by liomessip** [comment]
sorry

**Comment by David1ali12** [comment]
wtf's wrong with you

**Comment by liomessip** [comment]
sorry I just wanted to contribute

**Comment by Megabyte918** [comment]
@liomessip its alright but next time don't make an issue for every bug you encounter, if your question hasn't been answered, don't make a duplicate issue about it or it will be closed, just comment on the same issue and hope for a response. if its something small like the cells color is weird you don't have to make an issue about that either, just comment on an open issue. and if you have multiple bugs to report, dont make multiple issues just make one issue with all of the bugs

**Comment by David1ali12** [comment]
if I was @Barbosik  I would ban you ,

**Comment by NatsuTheGreat** [comment]
^^ He is trying to turn MultiOgar into OgarUL whilst thinking he is contributing. This guy is summing up 50% of the issues, and what for? "contributing". No one is going to add those configs, if you want them, either add them yourself or go back to OgarUL.

**Comment by darknight99x** [comment]
@liomessip I can understand you're frustrated with the amount of problems these builds of Agar.io can have.

Yes, it is good you're trying to reach out and have the problems solved, but spamming the issue box with problems is not going to get them solved, you need to back off for a bit, they can't continuously update things at the same pace you're wanting them, and we really don't understand half of the fixes you want, you need to clearly explain your problem.

**Comment by MastaCoder** [comment]
lol go easy on the poor guy :)
