### ISSUE TITLE
MasterServer?

### ISSUE THREAD

**Issue by ElMay0r** [Barbosik/MultiOgar#183]
Hello, i run Cigar on my server. and they have the "MasterServer" which allow you to run multiple GameModes at the time, would this build ever have that?

i run 6 gamemodes on my website, and i had to open 6 consoles to run all them all with this Build.

**Comment by Barbosik** [comment]
node.js running on single thread. So, hosting of several servers inside single node.js process will leads to lags and prevent to utilize multi-core cpu advantages.

**Comment by ElMay0r** [comment]
Cigar runs smooth on my server with 6 gamemodes.

**Comment by Barbosik** [comment]
it will run much more smooth if you run it separately

**Comment by Influxx** [comment]
You could spawn a child process for each game instance. I believe that's how Cigar does it, although not sure.
