### ISSUE TITLE
WebSocket crash!

### ISSUE THREAD

**Issue by ElMay0r** [Barbosik/MultiOgar#185]
Hi, i was the one who talked about the bots hosting that make server crash, they came back to www.Agar.Blue and there's a new error now in the New Build.

Take a look here; http://i.imgur.com/RjpcFA9.png

**Comment by ElMay0r** [comment]
Any suggestion?

**Comment by Barbosik** [comment]
What MultiOgar version did you used? 
Is it master branch clone or custom modded?

**Comment by Barbosik** [comment]
it seems that you're using outdated server version.
Update it and it should be resolved.
