### ISSUE TITLE
if i feed once i loose like 40 mass

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#187]
title

**Comment by NatsuTheGreat** [comment]
reduce ```ejectSizeLoss```

**Comment by Barbosik** [comment]
Your question is not clear. Can you explain it please?
What mass do you have when using eject?
What is your ejectSizeLoss?

Please add steps to reproduce (your step-by-step actions, expected result, and actual result). 
It's just impossible to understand what you're talking about without steps to reproduce.
