### ISSUE TITLE
PullRequest to OgarProject

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#19]
Your repo miles forawrd from OgarServer. Will you do pullrequest there or not. Did you even think about it? If you will not, i think many devs will migrate to this repo and OgarServer probably will die

**Comment by Barbosik** [comment]
I don't planning to make pull request into Ogar. It's just my fork.
But I'm monitoring for changes in Ogar and can apply good changes into MultiOgar.
