### ISSUE TITLE
A quick question.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#192]
Does anyone know how a cell gains mass when consuming a virus?

**Comment by SimonOrJ** [comment]
The game sets the size of a player cell by summing the mass of the virus and the player cell in `src/entity/Cell.js` -> `Cell.onEat` (which becomes `PlayerCell.onEat`) function.

https://github.com/Barbosik/MultiOgar/blob/master/src/entity/Cell.js#L134

**Comment by NatsuTheGreat** [comment]
That I know, but I am talking about virus consumption. How does it inherit mass from the virus?

**Comment by Barbosik** [comment]
Look into Cell.onEat

**Comment by NatsuTheGreat** [comment]
it controls how ```playercells``` eat viruses too?

**Comment by NatsuTheGreat** [comment]
I need onEaten. onEat is the wrong thing.

**Comment by NatsuTheGreat** [comment]
:/

**Comment by MastaCoder** [comment]
I remember, it's in the virus.js from what I can remember.

**Comment by NatsuTheGreat** [comment]
It's not in there, there's nothing like ```setSize```

**Comment by NatsuTheGreat** [comment]
I legit can't find it. How does it even add the mass :/

**Comment by NatsuTheGreat** [comment]
I got it to work!
