### ISSUE TITLE
Banned name feature

### ISSUE THREAD

**Issue by tveloper** [Barbosik/MultiOgar#195]
Like the ones in [CigarProject/Cigar](https://github.com/CigarProject/Cigar), is there a way to ban certain names, but to grant that ban name using an identifier (password)? 

For example, there is one guy who set his nickname to SERVER (like the welcome ones), and just typed random things, like 'YOU WILL ALL BE KICKED AND BANNED!'. Is there a way to ban those names?

`// adminConfig: Turn on or off the use of admin configurations. (1 is on - 0 is off)`
`// adminNames: The name a user would have to use to register as an admin.`
`// adminNewNames: The name you will be changed to when using adminNames.`
`// adminStartMass: Amount of mass admin players will spawn with.`
`// adminBlockNames: Rename people using adminNewNames to Unnamed cells. (1 is on - 0 is off)`
`adminConfig = 0`
`adminNames = "name1;name2"`
`adminNewNames = "newname1;newname2"`
`adminStartMass = 500`
`adminBlockNames = 0`

**Comment by Barbosik** [comment]
just add your names to badwords.txt, that's it.
