### ISSUE TITLE
¿Any config for instant merging gamemode?

### ISSUE THREAD

**Issue by polmp** [Barbosik/MultiOgar#198]
I'm trying to adapt Ogar Unlimited instant merge mode but it doesn't work (it's not compatible). ¿Anyone has this gamemode working?

Thx

**Comment by MastaCoder** [comment]
Duplicate. Instant merge doesn't work on MultiOgar.

**Comment by polmp** [comment]
This server is using it: http://agar.io/?ip=vps.simonorj.com:24270

And is running MultiOgar

**Comment by Barbosik** [comment]
MultiOgar code is incompatible with Ogar Unlimited parts. They very different.

If you want instant merge, just set `playerRecombineTime = 0` in gameserver.ini.
There is no need specific game mode to get instant merge.
