### ISSUE TITLE
Leaderboard time is always at 0:00 in Match Results.

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#2]
![image](https://cloud.githubusercontent.com/assets/11600822/15790992/b514044a-29cc-11e6-9e26-cf217d795f83.png)

**Comment by Barbosik** [comment]
Hm... strange. I don't see the reason why it may show 0 time, may be it's client issue. Needs to investigate it

**Comment by Barbosik** [comment]
fixed. I think it was related with this issue: https://github.com/Barbosik/MultiOgar/issues/13
