### ISSUE TITLE
Playerlist strange displaying

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#20]
It seems that lines too long
![image](https://cloud.githubusercontent.com/assets/10178982/15905383/5ce46d42-2dbd-11e6-8b85-808ca46c52b6.png)

**Comment by Barbosik** [comment]
The column after IP is a client protocol.
8 - it's vanilla client (agar.io), it uses protocol 8
5 - it's other client with protocol 5
4 - it's other client with protocol 4
1 - it's bad client with invalid protocol, such as ogarul.tk (it can join and play if it uses protocol compatible with 4)
0 - it's bad client with invalid protocol (it cannot join the game)

DEAD OR NOT PLAYING - means that the player isn't joined the game (it may displayed for some time even for disconnected players)

I will add fix to force disconnect clients with invalid protocol (records with protocol 0 in your list).
