### ISSUE TITLE
Server crash.

### ISSUE THREAD

**Issue by TheGoldenXY** [Barbosik/MultiOgar#202]
I recently updated my MultiOgar version to the latest version.

I was told by someone that "this version would never crash anymore". I guess that person was wrong.

Please fix this crash issue asap.

http://prntscr.com/bttefs

**Comment by Barbosik** [comment]
This issue is not related with MultiOgar. 
It's your mod error.

**Comment by NatsuTheGreat** [comment]
>I recently updated my MultiOgar version to the latest version.

**Comment by SimonOrJ** [comment]
> I don't know if he modified it after.

The error traces back to mysql package, which is not used on this project.

**Comment by NatsuTheGreat** [comment]
Okay then it's not the latest version, yet again. :/

**Comment by Barbosik** [comment]
The error happens in the code which is not a part of MultiOgar.
There is no such code in MultiOgar and this error impossible at all on any MultiOgar version.
