### ISSUE TITLE
I cant move

### ISSUE THREAD

**Issue by inxlio** [Barbosik/MultiOgar#204]
When I play often and die, then I can not move

**Comment by Barbosik** [comment]
If you're using minions, it's ok. Just a server protection from minions

**Comment by inxlio** [comment]
i using  the client for cigar , not using minions , when i play sometimes , i cant move ( only sometimes )

**Comment by Dramex** [comment]
same problem with latest version of MultiOgar, the old one works better

**Comment by Barbosik** [comment]
Looks like cigar client bug. Can you show the video with this issue?

**Comment by liomessip** [comment]
only i cant move my cell , is hard to understand?

**Comment by NatsuTheGreat** [comment]
You're seriously going to talk that way?

**Comment by Barbosik** [comment]
If you cannot provide detailed description (with step-by-step instruction, expected result and actual result, video which shows the issue), then this issue will be closed. Because no one can understand what you re talking about

**Comment by darknight99x** [comment]
@Barbosik his problem is with the client, when framerate drops, the mouse gives or something, and the cell is no longer able to move without a refresh of browser. He has a bugged client.
