### ISSUE TITLE
playerDisconnectTime Issue ?

### ISSUE THREAD

**Issue by Prime55** [Barbosik/MultiOgar#206]
Even when playerDisconnectTime is set to -1, player cells get disconnected instantly when you close the tab.

**Comment by Barbosik** [comment]
-1 is invalid value for playerDisconnectTime. You can use value 0 and above

**Comment by NatsuTheGreat** [comment]
It check if the time is more than ```playerDisconnectTime``` and zero right away would be more than -1.

**Comment by Barbosik** [comment]
if you want to disable disconnection on timeout, you need to change `serverTimeout` value.
To disable disconnection on timeout just set `serverTimeout = 0`

**Comment by NatsuTheGreat** [comment]
What can we use so that disconnected cells never disconnect except a high value?

**Comment by Barbosik** [comment]
you can just set very high value, for example set 3600 to keep disconnected cells for 1 hour. Or 86600 for 1 day.
But I don't recommend to set high values. Because each disconnected cell keeps server resources (memory, cpu time). So, if you will have a lot of disconnected cells, it will negatively affect server performance.

**Comment by NatsuTheGreat** [comment]
I'll add another condition to the if statement, it'll check if the value isn't below 0 :)

**Comment by Barbosik** [comment]
2NatsuTheGreat: such condition is invalid, because 0 is used to immediate remove player cells just after diconnection. You can use lage value, for example 1 year. But it will leads to memory leaks.

**Comment by NatsuTheGreat** [comment]
It worked. The cells don't get removed. ``` && this.gameServer.config.playerDisconnectTime > -1```

**Comment by Barbosik** [comment]
@NatsuTheGreat: this is hardcoded memory leak :)

**Comment by NatsuTheGreat** [comment]
Just don't use it then. :P I completely removed any cell removal on my server. Prevented updates going to disconnected cells, etc. Memory remains fine.
