### ISSUE TITLE
Can you fix this server's protocol?

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#208]
[Ogar-master.zip](https://github.com/Barbosik/MultiOgar/files/368387/Ogar-master.zip)

I love this split behavior.
But it doesn't work my client,
So i request you.

please fix only once.

**Comment by Barbosik** [comment]
Protocol is already works as expected.

**Comment by Chancerst** [comment]
@Barbosik It's not MultiOgar.
Your MultiOgar Server fixed all protocol, so it works my client perfectly.
But This Ogar fixed some protocol.
So it doesn't work my client.
i don't want to fix for official agar client,
i want to fix protocol 5.
but i don't know how to fix protocol.
so i request you.

**Comment by Barbosik** [comment]
You need to fix your client to support standard protocol
