### ISSUE TITLE
Add option skins

### ISSUE THREAD

**Issue by nobsterr** [Barbosik/MultiOgar#209]
Hi  , please add option for use skin without SKIN NAME on the nick

For ex :+1: 

without [shark] on the nick

**Comment by SimonOrJ** [comment]
You can lock onto a skin by using `<skin name>` in the name first.  You will keep that skin until you type in another `<skin name>` or just `<>`.

**Comment by Barbosik** [comment]
You can select skin with `<shark>` prefix in the name. Once is selected, you can use name without prefix, the skin will not disappears. To clear skin, just use name with empty prefix `<>`.

If your client has a chat, you can change skin much easier with player command. Just enter to spectate mode and type in the chat `/skin %shark`. The shark skin will be selected, you will see response from server about it. To clear skin, just type in the chat `/skin`.
If you already in the game, you can use command `/kill`, it allows you to die and don't wait while someone will eat you to enter into spectate mode.

**Comment by nobsterr** [comment]
the <skin> not work , only work [skin]

**Comment by MastaCoder** [comment]
Get off protocol 4.

**Comment by ItzLevvie** [comment]
^^ If you're using Cigar then you can edit the main_out, so you can use <skin> instead of [skin]

**Comment by nobsterr** [comment]
how to "get off protocol 4"?

**Comment by NatsuTheGreat** [comment]
Can't remember.. Is this the guy that made 2 issues concerning skins? But it'll tell you <> or [] won't make a difference, so update your protocol.

**Comment by Barbosik** [comment]
letters [ and ] is used for clan tags. There is no reason to duplicate <> with []. It's just useless and unwanted
