### ISSUE TITLE
how would i revert to the old spectate mechanism?

### ISSUE THREAD

**Issue by danielhoset27** [Barbosik/MultiOgar#214]
i don't like the new spectate mechanism

**Comment by Barbosik** [comment]
set `serverScrambleLevel = 1` but by using it you will make server more vulnerable for minion DDoS attacks

**Comment by danielhoset27** [comment]
I mean how do I revert back to the old mechanism where you can use Q for freeroam instead of other keys?

**Comment by SimonOrJ** [comment]
There's a 2 second delay before you can press the [q] key again.

**Comment by danielhoset27** [comment]
i want my spectate controls be like agar.io.
