### ISSUE TITLE
add instant merge gamemode

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#216]
i forgot where this was i think it was in ogarul there was an intant merge game mode, you would do 
/gamemode 5 or something and it would be instant merge

**Comment by Megabyte918** [comment]
just change the recombine time

**Comment by Barbosik** [comment]
Just set 'playerRecombineTime=0'. There is no needs for separate game mode for that.

**Comment by NatsuTheGreat** [comment]
I made an Instant merge gamemode. I made it do all the changing for me. 4 configurations change :P
