### ISSUE TITLE
Leaderboard (TEAMS) don't work.

### ISSUE THREAD

**Issue by DamianIsHere** [Barbosik/MultiOgar#222]
When placing the gamemode on my server using multiogar obviously , The leaderboard looks chopped in half.

**Comment by NatsuTheGreat** [comment]
Chopped in half? Teams mode leaderboard is supposed be like a pie, red, green, blue.

**Comment by Barbosik** [comment]
if I understand correctly you're talking about UI bug. It doesn't depends on server. It's just a bug in your client. I spent some time on investigation of existing clients code and found that a lot of them has a lot of bugs. Include leaderboard code. Too many people modifying it to add clan colors and other things. But they doing it with a lot of mistakes. So, it reduces client performance and add bugs. For example some clients cannot show leaderboard for Teams mode at all.

**Comment by NatsuTheGreat** [comment]
^^ I have seen that,

**Comment by Barbosik** [comment]
I even found some mod of agar plus which shows false FPS :smile:
It worked in such way if (fps > 20) fps += 5; if (fps > 40) fps += 10; if (fps > 50) fps += 20;  :smile:

**Comment by NatsuTheGreat** [comment]
Wow... That is some brilliant code... 20+ adds 5, 40+ adds 10, 50+ adds 20.... Really?..... This would end up giving high and inaccurate values :/ Every time it checks it, it gives you more and more false FPS. Who had such knowledge to code it that excellent way?

**Comment by Barbosik** [comment]
I don't know who coded it, but probably a lot of peoples modified it. This mod has a lot of code fragments which indicated that it was developed for ZT clan members.

**Comment by NatsuTheGreat** [comment]
Well whoever modified it, clearly did think it out.
