### ISSUE TITLE
Spawnmass Command

### ISSUE THREAD

**Issue by Prime55** [Barbosik/MultiOgar#223]
@Barbosik  Can you add a spawnmass command ? For example `spawnmass 9 500` and then player 9 will spawn with 500 mass. Vanilla agar.io has startmass boosts, so i think it would be cool.

**Comment by Barbosik** [comment]
it's already exist. just use 'change playerStartSize 224'

**Comment by Prime55** [comment]
@Barbosik I meant ingame with a console command. Because changing playerstartsize will affect all the other players/bots. I want to apply it only on me or on a specific player/bot.

**Comment by Barbosik** [comment]
you can use mass command: `mass <player_id> 500`

**Comment by Prime55** [comment]
@Barbosik But i have to do it everytime i spawn, which is annoying. The `spawnmass` command is supposed to be permanent until you change it again.

**Comment by Barbosik** [comment]
dude, if you need it then add it for yourself. I'm here not to add useless commands which will duplicate existing one

**Comment by Prime55** [comment]
@Barbosik I don't think it's useless. The point of it is just to simulate agar.io startmass boosts. It would be useless if it was something that don't exist in agar.io like **"press H and shoot 20K mass mothercells".** But alright, it's your project. Anyways, you said that commands eat server memory, then what a about a config that you can change in gameserver.ini ? For example :

`playerStartSize = 130`
`botStartSize = 43`

I don't understand about code, so if it causes the same forget it lol.

**Comment by Barbosik** [comment]
it's unfair for other players. It's just a toy for you, to play with it.
But it's completely useless for real server.

**Comment by NatsuTheGreat** [comment]
Damn Barbosik.

**Comment by Prime55** [comment]
@Barbosik If this `spawnmass` command is unfair, then pretty much the commands like `mass`, `tp`, `kill` are too. And people are not even able to execute these commands, only the owner of the server. And even if the owner decides to abuse of this command to get advantage by doing `spawnmass x 15000` for example, why wouldn't he do with the others commands. It's his decision, he created the server to people play on it, if he messes with everything making the game unfair, people simply wont play on it.

> And one one needs it.

If the point is to make the server balanced and fair, then there's no need for commands like `tp`, `kill` too. Unless they're playing on an empty server.

> It's just a toy for you

Well, MultiOgar is an Agar.io implementation, Agar.io is game, and games have the same purpose of toys, entertain and make you have fun. So not only this command is a toy, but also everything here.

> You want such commands just to play for 5 minutes on your empty local server.

I think that's what the majority of players who play Ogar do.

But it's ok, i'll stick with writing a phrase in the console everytime a spawn.

**Comment by SimonOrJ** [comment]
> If this spawnmass command is unfair, then pretty much the commands like mass, tp, kill are too.

That's why @Barbosik mentioned:
> In opposite, I think that there is need to remove half of the commands, because they completely useless and just eating server memory

**Comment by Prime55** [comment]
> If the point is to make the server balanced and fair, then there's no need for commands like tp, kill too. Unless they're playing on their empty server.

@SimonOrJ Idk if he meant those ones, but if he did, i disagree, because like i say up here ^, those commands are useless only in a real server because can cause disadvantage, but on a private server that you're playing just to have fun, which i think it's what the majority of people do, then they're useful to walk around the map, test things etc., and don't harm anyone. So removing those commands would be "unfair" with people who actually use them.

Like i said, it's the owner's decision to f*ck with everything and make people don't play on the server. So those commands could actually be used properly, like the `spawnmass` one. Making someone spawn with 200 mass when the others spawn with 50 doesn't make the game unfair.

**Comment by Barbosik** [comment]
@Prime55: _If this spawnmass command is unfair, then pretty much the commands like mass, tp, kill are too._

`mass` is actively used for debugging. `kill` sometimes needed for admins. `tp` is really useless

**Comment by Prime55** [comment]
@Barbosik 

> it's unfair for other players.

> If this spawnmass command is unfair, then pretty much the commands like mass, tp, kill are too.

**Making this cleaner:** If spawnmass command is unfair, then  `mass`, `kill` and `tp` can also be, cause the same way the admin could make someone spawn with 15K mass with the `spawnmass`command, he could give someone 15K with the `mass` command, or kill someone that have a highscore  with the `kill` one, making the game unfair. They can be used properly like you said up there and i said here: 

> Making someone spawn with 200 mass when the others spawn with 50 doesn't make the game unfair.

but also improperly, like i said in the first three lines. It's their decision to keep the server full or not. So i didn't say that the only thing those commands are is unfair/useless, what i meant was that depends on how people use them.

But it's alright if you don't want to add it, i already said, it's your project.

**Comment by Barbosik** [comment]
@Prime55: it's your decision to add such commands on your server or not. But it's useless for master branch

**Comment by MastaCoder** [comment]
I use the command mass and kill all the time on the server to test out physics, the gameplay, and stability. Those 2 commands really help in the debugging process of the server. Commands that are extra just to add more features for yourself doesn't mean they have to be added to MultiOgar, you can add them yourself and it isn't that hard.
