### ISSUE TITLE
Recent update is making spectate mode bounce up and down. (Custom Client)

### ISSUE THREAD

**Issue by darknight99x** [Barbosik/MultiOgar#225]
On any different variation of a client I try it keeps bouncing up and down. (or resetting itself over and over again.)

Example: http://agarprivate.ml/client

**Comment by Barbosik** [comment]
its a bug in the client which you're using

**Comment by darknight99x** [comment]
@Barbosik I promise you these are the same versions of a client I have used before and all of the sudden it's doing it. It's a change that has been made on your guys's end.

**Comment by Barbosik** [comment]
nothing is changed, just enabled scrambleLevel = 2 by default, it helps to reduce minions, because they cannot use navigation. If your client cannot show spectate mode properly, it means that your client has a bug. It's well known and very old bug very popular in modded clients.
