### ISSUE TITLE
Changeable Split-Speed of the Cell

### ISSUE THREAD

**Issue by overkil** [Barbosik/MultiOgar#226]
I was wondering if it was possible to change the splitting speed of the cells so you can actually make them split slower or faster? I am not talking about the cell base speed which is the speed with which the cell moves (which is slightly slower than vanilla) but the split speed of the cell. Is it possible? 
Also, is it possible to make the cell base speed as fast as vanilla? 
Thanks :)

**Comment by Barbosik** [comment]
Change split speed will break game balance, ruins split tricks and game physics.
Base cell speed is exactly the same as on old vanilla servers (before update).
It's possible to change base cell speed, but there is need to approximate speed formula for new vanilla servers.
