### ISSUE TITLE
Feeders bug?

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#23]
Is it normal that i can go through feeder cell? Also i cant feed feeders. Parts just go through feeder cell
![image](https://cloud.githubusercontent.com/assets/10178982/15925398/af97b77e-2e3f-11e6-90b9-f7bf41d8542e.png)

**Comment by Barbosik** [comment]
it's a bug, because virus cell has no owner. I will fix it

**Comment by F0RIS** [comment]
has no owner, funny)

**Comment by Barbosik** [comment]
just checked it, it's because Experimental mode has a broken code. it cannot check for collision with mother cell properly

**Comment by F0RIS** [comment]
Also sometimes collision with feeders work, but strange

**Comment by Barbosik** [comment]
yes, something is going wrong on Experimental game mode. It looks like code for this game mode didn't updated for a long period, so it's out of date.

**Comment by Barbosik** [comment]
with new physics engine it's fixed. But currently experimental game mode has some performance issues, because I didn't optimized it
