### ISSUE TITLE
Sorry for the inconvenience

### ISSUE THREAD

**Issue by caca123xd** [Barbosik/MultiOgar#230]
his has to do, I just wanted to thank

is the agar with multiogar with greater amount of users , thanks !!

please try fix lag at multisplitting faster

**Comment by Barbosik** [comment]
@caca123xd: could you please fix these things on your servers:
1) enable `serverTracker=1`
2) do not remove server version messages "MultiOgar 1.xx.xx"

Thanks

**Comment by caca123xd** [comment]
1) if i enable servertracker , this will cause lag?
2)  Ok thanks !

**Comment by Barbosik** [comment]
no it will not cause lag
