### ISSUE TITLE
Add tags for chat/minimap

### ISSUE THREAD

**Issue by henopied** [Barbosik/MultiOgar#231]
If enabled in the config:
- Player could send tag to server
- Server tracks players' tags
- Only send chat messages to players with the same tag as the sender.

**Comment by Barbosik** [comment]
No, because it will affect server performance dramatically, it's performance will significantly drops down and it will allows minions to get correct coordinate in easy way. In other words, it will reduce maximum player count with no lag and will make server very easy target for minion DDoS attacks

**Comment by henopied** [comment]
@Barbosik I opened a different issue about minimap and the minimap should never be enabled if coordinate scrambling is enabled also.

**Comment by Barbosik** [comment]
there is already problem with protocol performance. And you suggesting to add more things which will make server more slow and laggy

**Comment by Barbosik** [comment]
if you want such features, it's better to implement separate server to handle it. In such way how it worked in agarplus
