### ISSUE TITLE
Add minimap

### ISSUE THREAD

**Issue by henopied** [Barbosik/MultiOgar#232]
A minimap in multiogar would be better than other forms of current minimaps because:

- Player location can't be faked
- It can load banned ips from multiogar server
- It uses the existing websocket server

This added along with tags could create a minimap that could be used to play with friends without needing to use a separate minimap service.

**Comment by MastaCoder** [comment]
You mean as in client sided files for a minimap?

**Comment by henopied** [comment]
@MastaCoder Not really, the idea is that we could add a config option to enable minimap and that minimap would be hosted on the multiogar server itself.

**Comment by Barbosik** [comment]
Player location makes easy target for minion DDoS attack. It will kill the server, because it's performance will drops down and minions will just crash it
