### ISSUE TITLE
Domain name on server tracker

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#233]
Can this have a configuration option for sending domain names to the server trackers?  It would give the trackers the domain name field, and those that support the field would check if the domain name traces back to the IP address (For example, on [PHP](http://php.net/manual/en/function.gethostbyname.php)

``` php
$domaninName = $_PUT["whateverTheDomainNameFieldNameIs"];
if (gethostbyname($domainName) == $_SERVER["REMOTE_ADDR"]) {
    // Domain name points to the origin's IP address; put it on the server list
} else {
    // Domain name does not point to the IP address. Just display connection by IP address
}
```

I really wish server trackers use the domain name rather than the IP to save the Ogar server hosters some headache of having to announce people the new IP address.

**Comment by Barbosik** [comment]
tracker should automatically catch new IP, it will appears as a new server in 10 seconds (ping interval). Old one will be marked as offline in 30 sec after last ping packet (this flag is already available in json, but currently not highlighted on html). And it will be removed after several minutes.

The problem with sending DNS - it's vulnerable to spoofing. Tracker gets IP as remote address of ping packet sender. If tracker will take dns from ping packet, anyone will be able to send ping packet with any dns...

**Comment by SimonOrJ** [comment]
That's why I added:

> and those that support the field would check if the domain name traces back to the IP address

Which means the server should check if the domain name matches with the IP address using a DNS.  There's no way to spoof the domain name if the tracker server is using a good DNS server (For example, Google's: 8.8.8.8).  That's why I provided the whole PHP code snippet.

**Comment by SimonOrJ** [comment]
Also, when an IP has multiple domain names, then there's no one answer. All of 'em are correct as all points back to the same IP address.

With DNS server pointing at a reliable service, it's not vulnerable to spoofing.

**Comment by Barbosik** [comment]
There are several problems with using DNS: 
1) DNS may use several IP records. For example:
```
Name:    microsoft.com
Addresses:  23.96.52.53
          104.40.211.35
          191.239.213.197
          104.43.195.251
          23.100.122.175
```
how to identify unique server by DNS?

2) You can add your IP to DNS record and ping the tracker. After that you can remove IP from DNS record. In such way you can post fake server to the tracker. It will not be accessible, but there is no fast way for tracker to check if server is available

**Comment by SimonOrJ** [comment]
One benefit it'll give users is that you don't have to update everyone on the new server IP when you ever have to change the server host.  Another is that if someone's hosting the server with a dynamic IP address (common on houses), they will lose all the player base, who may think that the server is down forever.

It wouldn't be a problem for people who used the tracker to get on the server, but when a person (A) shares the server with the IP address to another person (B), that person (B) will not be able to come back to the right server when the server IP changes.

1) A domain name (DNS = Domain Name System, which gives clients the IP address(es) from a domain name; not the same as domain name) is able to have multiple A records.  However, the clients will just go with the first IP address from the list.  If anything, there can be a check on how many IPs a domain name returns, and it can just ignore the domain name part if the nameserver returns multiple IP address for a particular domain name.

2) Who would ever want to do such thing?

3) There's no real reason to change the A-record of a domain name if the IP address is not changed.  When the server host gets another server to host Ogar on, they can just update the A-record of the domain name, which is going to take some time (usually 5 to 20 minutes, but, yes, up to 24 hours) for all nameservers to update.  When someone relies just on the IP address, they will never be able to connect back to the same server until they check the server tracker.

I've been using domain name on my server because I don't want to give the players hard time getting on this server in case they shared just the IP address of the server.  IP address is just really annoying for me to deal with.

I administer a Minecraft server, and it has no problem connecting using a domain name.  When the host randomly changed the MC server's IP address and when I decided to move it over to another host, all I had to do was update the domain name's A-record instead of giving everyone the IP address out over again.

That's all I want.  I just don't like dealing with IP addresses.  I'm not looking for this feature for load balancing or DDoS protection.

**Comment by Barbosik** [comment]
ok, I can add it, but how to show it on the tracker? Show dns instead of IP?

**Comment by SimonOrJ** [comment]
One possible way is to make make the Server Name column a hyperlink to the server, and show the domain name on the IP column.  Then maybe you can assign `.hidden-xs` class to the first column of the table to conserve space for smaller displays.

**Comment by SimonOrJ** [comment]
By the way, DNS is not synonymous to domain name.  DNS is a service that matches an IP address with a domain name.
