### ISSUE TITLE
help me (add agarplus in server)

### ISSUE THREAD

**Issue by mrdogekr** [Barbosik/MultiOgar#237]
I want to add agarplus script(?) in my server like senpai agar or sakuramoti AGAR.
But i don't know how to do it
Can U guys teach me how to do it?

**Comment by David1ali12** [comment]
lol you dont need to add any script you can use http://agarlist.com/?ip=serverip:port 
MultiOgar is multiprotocol can work with any protocol :)

**Comment by mrdogekr** [comment]
thanks!!
