### ISSUE TITLE
The cell freeze

### ISSUE THREAD

**Issue by multa2** [Barbosik/MultiOgar#239]
the cell freeze sometimes, but if you can throw mass

**Comment by Megabyte918** [comment]
what

**Comment by Barbosik** [comment]
record video, because without it, I don't understand what you're talking about

**Comment by multa2** [comment]
the cell freezes sometimes ( i cant record this, because i cant know when will freze ) and only eject mass , but i cant move

**Comment by NatsuTheGreat** [comment]
Depends on what client you are using. I have noticed this happen on agarlist before, haven't seen it by far.

**Comment by Barbosik** [comment]
so, it's the client issue
