### ISSUE TITLE
splits are too far 

### ISSUE THREAD

**Issue by Yamanourani** [Barbosik/MultiOgar#24]
please help as i bought a vps to do this :/

**Comment by F0RIS** [comment]
@Yamanourani wtf?

**Comment by Barbosik** [comment]
Probably he talking about the physics of split. Currently it very different from vanilla.

**Comment by Yamanourani** [comment]
cant u fix it ? (:

**Comment by Yamanourani** [comment]
it was perfect now it broke

**Comment by Barbosik** [comment]
Sorry, but I have no idea what you're talking about.
Just write what is your issue? 
How to reproduce it? (steps to reproduce)
What is your expectations and what is the actual result of your steps to reproduce?

**Comment by Barbosik** [comment]
split and eject physics were fixed (rewritten)
