### ISSUE TITLE
Ready !! http://ogar-tracker.tk/

### ISSUE THREAD

**Issue by multa2** [Barbosik/MultiOgar#242]
My server is on the tracker !! top 1 - 5 :dancers:  (AGARIO.CITY)

**Comment by lulzyyy** [comment]
Hmm is this an issue that your servers are on tracker? Barbosik fix this!

**Comment by multa2** [comment]
why delete the original title in the tracker ?

**Comment by MastaCoder** [comment]
@Barbosik Close.

**Comment by Barbosik** [comment]
multa2: server name is not intended to show site urls. Server name is moderated and any kind of links, spam and other things will be added to filter.
I will add two new fiels soon, it will allows to add web site url for your server and DNS name.
