### ISSUE TITLE
More commands and admin personalization

### ISSUE THREAD

**Issue by multa2** [Barbosik/MultiOgar#246]
Example

a guest player with tag [guest] 

a mod player with [MOD] or personalizable tag

a admin player [ADMIN] or personalizable tag

more commands as ban , killall , kill id , mass , playerlist , etc

**Comment by NatsuTheGreat** [comment]
>more commands as ban , killall , kill id , mass , playerlist

Why in the world would we need commands such as the commands that we already have?

**Comment by multa2** [comment]
commands in the chat

**Comment by NatsuTheGreat** [comment]
Go add them to PlayerCommand.js this is not nearly important for the base branch.

**Comment by David1ali12** [comment]
code it ur self do not ask for it

**Comment by multa2** [comment]
@NatsuTheGreat  como agregar?

**Comment by NatsuTheGreat** [comment]
You take a command and you fkin add it

**Comment by F0RIS** [comment]
@multa2 make pull request, Barbosik will be only grateful for that)
