### ISSUE TITLE
Virus Bug

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#25]
![default](https://cloud.githubusercontent.com/assets/19770308/15956559/3e42b1e2-2f24-11e6-9043-0cb4ea022032.png)

Virus doesn't work.

**Comment by Barbosik** [comment]
it's not a bug. Virus count is limited by server settings in gameserver.ini
So, if this limit is reached, new virus will not be spawn and all your feeds to virus will not be consumed.
