### ISSUE TITLE
as I can make this public server in VPS c9.io please help :) and great work

### ISSUE THREAD

**Issue by JhairMorales** [Barbosik/MultiOgar#254]
as I can make this public server in VPS c9.io
please help :) and great work

I have VPS in c9.io and do not know how this fits server so that the server share. I do not like hamachi so I prefer to MultiOgar and VPS c9.io

**Comment by Megabyte918** [comment]
c9.io is not supposed to be used as a free VPS.

**Comment by JhairMorales** [comment]
I own cards and make an account c9.io FREE

**Comment by ItzLevvie** [comment]
You're not allowed to run servers / emulators on C9. Buy a VPS instead of using an development platform.

**Comment by David1ali12** [comment]
some ppl are sick you will get banned , c9 does not allow hosting games this post should be deleted 
Because you some kids some developer cant use c9 now You mad bro who cares you have cc every1 does already WTF IS WRONG WITH YOU ?

**Comment by Barbosik** [comment]
C9 is intended for development. Usual hosting on C9 is not allowed. So, please don't use C9 for such purposes.
