### ISSUE TITLE
[INVALID]

### ISSUE THREAD

**Issue by CalvinDKHD** [Barbosik/MultiOgar#257]
So the owner of agarlist has been discussing in here, his server is AMAZING.
Now i am trying to make a server like his but i need some help, ill gladly pay.
Or if anyone got a way i could contact him, that would be appreciated!
my skype: calvin.leonhardt

**Comment by NatsuTheGreat** [comment]
>Now i am trying to make a server like his 

Huh?

**Comment by CalvinDKHD** [comment]
Like I would like to make a client or something like agar list

**Comment by CalvinDKHD** [comment]
Like an agarplus client

**Comment by Peridax** [comment]
Hey there, founder of agarlist here. You can contact me via skype. **live:peridax**
