### ISSUE TITLE
How to run multiogar with git clone

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#258]

**Comment by Megabyte918** [comment]
*facepalm again*

**Comment by SimonOrJ** [comment]
Just do 
```sh
git clone https://github.com/Barbosik/MultiOgar.git
```

After you do that, `cd MultiOgar`, then
```sh
npm install
```

Rest of the steps are the same as shown in the main page.
https://github.com/Barbosik/MultiOgar

**Comment by GhostShot3** [comment]
@SimonOrJ Thx,solved.
