### ISSUE TITLE
About Other client.

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#26]
I want enjoy multiogar with agarplus.io.
But it doen't connect.
Are you able to make i can connect with agarplus.io?
else, Can you make multiogar's version agarplus.io?
please answer it :)

**Comment by Barbosik** [comment]
It seems that agarplus.io doesn't support connection to private servers.
It doesn't accept /?ip=

So, it's agarplus.io issue

**Comment by Chancerst** [comment]
@Barbosik I could connect ogar unlimited 10.6.3 with agarplus.io.
OGARio extension is no problem with connect.
So, I think agarplus.io not support new protocol.

Umm. But i'll try again.

**Comment by Barbosik** [comment]
I don't know what is your issue. Because I just tested it and agarplus.io woks OK with MultiOgar.

**Comment by Chancerst** [comment]
@Barbosik ok Thank you.
It fixed.
