### ISSUE TITLE
[DUPLICATED]

### ISSUE THREAD

**Issue by DTMClanDeveloper** [Barbosik/MultiOgar#260]
title

**Comment by multa2** [comment]
same issue

**Comment by multa2** [comment]
you can set ScrambleCoords = 3 and DisconnecTime to 1

**Comment by SimonOrJ** [comment]
I've been combatting botting by banning all the IP addresses related to the bot provider.  I'll probably make a repository dedicated to tracking bot providers' IP addresses if anyone is interested in it.

**Comment by multa2** [comment]
@SimonOrJ  please make it
