### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#263]
in the old protocol on agario client I was using connect("ws://serverip:port") to connect to server with console with new protocol it does not work what is the function to connect to server  thx

**Comment by ItzLevvie** [comment]
It's core.connect("ws://serverip:port")

**Comment by David1ali12** [comment]
Thxs

**Comment by David1ali12** [comment]
@ItzLevvie  lol I think its changed now 
![but](https://cloud.githubusercontent.com/assets/17472593/17419231/304c182e-5aa5-11e6-8314-e77b15cf7937.PNG)

**Comment by David1ali12** [comment]
some1 can help ?

**Comment by SimonOrJ** [comment]
`core` variable is undefined.  You need to assign a variable or function to `core` before you do anything with it.  I'm not sure if this will work, but it should be something like this:

```js
var core = new WebSocket("ws://ip:port");
```

... unless you're using an external library...  but if I wanted to make an Ogar client, I would start with something like that.  That's just me.

**Comment by ItzLevvie** [comment]
@David1ali12 You've to refresh the page for it to work.
