### ISSUE TITLE
Web Site 6 New Server Add / Thank You

### ISSUE THREAD

**Issue by bigstery** [Barbosik/MultiOgar#272]
Hello there
agarlove.com added your Homepage to 6 servers
website added servers
37.187.147.108:458
37.187.147.108:451
37.187.147.108:453
37.187.147.108:473
37.187.147.108:452
37.187.147.108:459

150 hard player and now all I have is playing in your server
I would ask you to support me in your
I'm glad if my website address at the forefront

Thank you. Good Work

**Comment by SupportCT** [comment]
These servers are not yours , loool
