### ISSUE TITLE
I cannot connect at all.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#279]
There seems to be a change in the protocols or something, because I cannot connect through my modified version, not the latest fresh MultiOgar version.

**Comment by nuclearc** [comment]
yeah it's now version 9

**Comment by ItzLevvie** [comment]
Yep ^^

**Comment by nuclearc** [comment]
looks like bots are not gone, they are back after 10 seconds :D

**Comment by ItzLevvie** [comment]
Going to decode the new agario core :D

**Comment by nuclearc** [comment]
btw nothing changed it can connect to my server

**Comment by ItzLevvie** [comment]
Kay

**Comment by nuclearc** [comment]
you must change this
```js
    if (this.handshakeProtocol < 1 || this.handshakeProtocol > 8) {
        this.socket.close(1002, "Not supported protocol");
        return;
    }
```
to this:
```js
    if (this.handshakeProtocol < 1 || this.handshakeProtocol > 9) {
        this.socket.close(1002, "Not supported protocol");
        return;
    }
```

**Comment by NatsuTheGreat** [comment]
Wow, thanks. At protocol 9 already :/
