### ISSUE TITLE
Bot Bug and map view

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#28]
Bot Stop Movement, And soon, Bot have Teleport.
This is the Problem video.
[Desktop 2016.06.11 - 10.16.57.08.zip](https://github.com/Barbosik/MultiOgar/files/310039/Desktop.2016.06.11.-.10.16.57.08.zip)
And you can see Map view is so far.
And I can see dead cells.
Please Fix it. :)

**Comment by Barbosik** [comment]
What game mode did you used? Note that experimental game mode currently has a broken code, so it has a bugs.

At a glance bots stops because there is too small amount of food. So, they don't see food

**Comment by Chancerst** [comment]
@Barbosik I used Gamemode 0.
No, I use Food amount 1800.
I think It's dead cells.
When i go to the dead cells,
I can through the cells.
And I can see dead foods.

**Comment by Barbosik** [comment]
it looks like it's because you're using client with protocol 5. It's related to clear message.
I will fix it.

**Comment by Chancerst** [comment]
@Barbosik Thank you,
I always Think, You are a Good Delveloper. :)

**Comment by Barbosik** [comment]
fixed, test it please

**Comment by Chancerst** [comment]
@Barbosik OK

**Comment by Chancerst** [comment]
@Barbosik Yes, it fixed
