### ISSUE TITLE
Rapid fire cheat doesn't works

### ISSUE THREAD

**Issue by JhairMorales** [Barbosik/MultiOgar#281]
on the server and not split double throw me the strip, PORFAVOR a solution and add splitspeed or something :)

Please.. :)

**Comment by NatsuTheGreat** [comment]
Can you clear that up?

**Comment by JhairMorales** [comment]
hmm .... when I give double space or more spaces to maximum 3, do not grab everyone and just throw me one space, no solution?

PS: I do not speak English very well : /

**Comment by NatsuTheGreat** [comment]
You mean cells fly through cells?

**Comment by JhairMorales** [comment]
no, the spaces do not respond well, rather, or if you can make video showing the error ...

**Comment by NatsuTheGreat** [comment]
Do you have any script running?

**Comment by JhairMorales** [comment]
no ¿how?

**Comment by Megabyte918** [comment]
Oh yeah :/ this has been happening to me too, when I press space/w fast, half the time it doesnt register that i pressed the key (or maybe it does and it blocks it to reduce multispliting lag?) and same with doublesplitting fast, it doesnt register the second space if i do it too fast. this makes it impossible to use macro's/extensions that have macro's as they get blocked after the server detects a key being pressed too fast. I think it might be linked to this commit : https://github.com/Barbosik/MultiOgar/commit/f4671291b02d3b50bace5d33af6d34f84369dc22

**Comment by JhairMorales** [comment]
yes, i get this script https://greasyfork.org/es/scripts/19863-best-tricksplit-doublesplit-and-feeding-macros-auto-settings-triplesplit-macro

**Comment by NatsuTheGreat** [comment]
Welp that is a protection against multisplitting, and I am pretty sure the only servers that have this are Barbosik's test servers, which are not something to worry about as they are for testing.

**Comment by Barbosik** [comment]
The server allows split and eject with limited speed specified in 'ejectCoolDown' variable in gameserver.ini config. If you pressing space with frequency 1000000 times per second, it doesn't means that server should process your command 1000000 times per one server tick. Because it will stop the server for long time
