### ISSUE TITLE
[INVALID]

### ISSUE THREAD

**Issue by mrzack506** [Barbosik/MultiOgar#282]
Hi, I've created a client with main_out.js lineWidth set to 9. But here's my problem:
lineWidth doesn't stay as it should be as you increase mass. Example 
![linewidthprob](https://cloud.githubusercontent.com/assets/19736068/17577472/1c49cb4a-5f4c-11e6-9b4b-e18cffa71bab.JPG)
but when you are smaller, it looks like this:
![linewidthgood](https://cloud.githubusercontent.com/assets/19736068/17577483/4545119e-5f4c-11e6-97eb-d73e15f660d3.JPG)

so can anyone help me? Would be extremely appreciated!

**Comment by Barbosik** [comment]
MultiOgar does't works with graphics at all. Please do not post client graphics issues here
