### ISSUE TITLE
What is the name of the variable of cell mass

### ISSUE THREAD

**Issue by supportAC** [Barbosik/MultiOgar#284]
is cell.Mass ?

i can use this var with client ?

**Comment by NatsuTheGreat** [comment]
cell._mass or cell.getMass()

And you can use it as long as 'cell' is a valid entity node. (food, virus, player cell, or ejected cell)

**Comment by supportAC** [comment]
is correct?

if (cell.getMass > 5000) {
					 ctx.lineWidth = 18;
					 }
					 else {
						 
						 ctx.lineWidth = 8;
					 }

**Comment by supportAC** [comment]
and "this.size"? what is this?

**Comment by NatsuTheGreat** [comment]
Replace ```cell.getMass``` with ```cell.getMass()``` as it's a function. Then you'll be good to go.

**Comment by supportAC** [comment]
the function of the score is declared on the client?

**Comment by supportAC** [comment]
i think this is better :+1: 

if (playerCells.length > 5000) {
					 ctx.lineWidth = 18;
					 }
					 else {
						 
						 ctx.lineWidth = 8;
					 }

**Comment by NatsuTheGreat** [comment]
No it's not. You do not have playerCells defined, and you have a server that allows 5000 cells per player?

**Comment by supportAC** [comment]
no, I want to find the function that collects the number of points

 i think is :  playerCells.nSize ?

or 

if (calcUserScore() > 5000) {
ctx.lineWidth = 18;
}
else {

                     ctx.lineWidth = 8;
                 }


I get to have 5000 points the line is 18

if not the linewidht 8

**Comment by NatsuTheGreat** [comment]
I know what you're trying to get... I can code... use cell.getMass()

**Comment by supportAC** [comment]
with this function the client dont working , why?
