### ISSUE TITLE
Linesplit working

### ISSUE THREAD

**Issue by supportAC** [Barbosik/MultiOgar#285]
Linesplit working with split macro on our server, LOL

**Comment by NatsuTheGreat** [comment]
Okay? Linesplit works on my server too, what does your issue have to do with the project?

**Comment by NatsuTheGreat** [comment]
And it doesn't work at all, so this was a complete waste of issue space.

**Comment by supportAC** [comment]
only work with faster splits

**Comment by Barbosik** [comment]
@supportAC: here is no support for those who come to steal something to capitalize it
