### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by PrinceDark9243** [Barbosik/MultiOgar#286]
before when i played with cousin in MultiOgar Server i used this http://agar.io/?ip=localhost:28 but after 5-7 day later i tried to connect to server but dosent connect is there a problem while have hamachi?
Can someone help me i cant able to connect!

Thanks!

**Comment by PrinceDark9243** [comment]
I tried these thing:
1 change port form config and url [NOT WORK]
2 before i dont have hamachi but when i install it server dosent work
3 i tried to connect with play.ogarul.tk and its works!

**Comment by Barbosik** [comment]
just update server to the latest version

**Comment by PrinceDark9243** [comment]
Thanks Worked!
