### ISSUE TITLE
You can change splitspeed to actual vanilla?

### ISSUE THREAD

**Issue by supportAC** [Barbosik/MultiOgar#287]
you can change slitspeed to actual vanilla and not to old smooth vanilla

**Comment by ZfsrGhS953** [comment]
@supportAC I agree, the speed should be changed. Current splitting is too "laggy"

**Comment by ZfsrGhS953** [comment]
@supportAC MultiOgar主书亪仍佇俸偌冊, 兣儹勶tricksplit厷哊填夛孈佇multisplit. 偌咑䒖䒁䌻䋊䋊Petridish MultiOgar 䈜䊪勶.

**Comment by PrinceDark9243** [comment]
yes guys tell me how i can make it slower @Barbosik Help plz :D

**Comment by supportAC** [comment]
invalid ? , suck support

**Comment by Megabyte918** [comment]
@supportAC The splitting speed is vanilla, I've even made some gifs comparing the splitting in vanilla to the splitting in multiogar and there was no difference whatsoever. I will put them here once I get back on my computer.

**Comment by Barbosik** [comment]
@Megabyte918: yes, MultiOgar uses exactly the same split speed as vanilla and it didn't changed on vanilla servers, it always used this speed.

**Comment by NatsuTheGreat** [comment]
I though it changed.. I guess the lag WAS somewhat fixed when I played after the protocol change.

**Comment by Barbosik** [comment]
from protocol 4 to protocol 8 it's exactly the same, I didn't tested it on new version with protocol 9 which released several days ago.

**Comment by NatsuTheGreat** [comment]
Can you please do test?
