### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by dinhduynhat** [Barbosik/MultiOgar#290]
![image](https://cloud.githubusercontent.com/assets/20450856/17647650/d76576d4-6223-11e6-9252-29079396841b.png)

**Comment by Barbosik** [comment]
disable stats server with setting `serverStatsPort = -1`

**Comment by SimonOrJ** [comment]
As for the meaning of the error, `EADDRINUSE` means "Error: Address in use", which means the specified port (88 in this case) is in use by another program.

**Comment by MastaCoder** [comment]
@Barbosik Isn't this solved now? :)

**Comment by Barbosik** [comment]
@MastaCoder: it's ok, because this error happens when the port is in use by other app
