### ISSUE TITLE
Problems with Hosting the Server on Google Cloud

### ISSUE THREAD

**Issue by overkil** [Barbosik/MultiOgar#293]
I am hosting the server on google cloud platform on compute engine where I created an instance with 4 vCPUs, 6 GB RAM and Ubuntu 16.04 LTS. What I don't get is, why is the game still lagging and has latency even when there is just one player in the server even though I'm hosting it on a capable virtual machine? The CPU and RAM are underutilized but it still lags and never has it once ran without lag and latency on google cloud.
I run the server on the instance via the instance's SSH which I open in another browser window. Could that be a problem? Further more, I use the client at agarlist.com to play since I don't have my own client for multiogar but I tested with the client at play.ogarul.tk too and it lags there too. Could the clients be a problem? I am in a mess...
Any help would be so much appreciated! Thanks for creating multiogar :)

**Comment by Barbosik** [comment]
here is a lot of possible issues, the most likely reason is that your virtual machine is shared with another and so it has high delays due to high load on the second vm. 
The second most possible reason is that your vm is accessible through some kind of proxy. For example if you're using cloudflare services. Or your vm just has a slow internet connection

**Comment by overkil** [comment]
Thank you for the reply. I will ask those questions on the google end and update this issue here if I find something out for anyone else that might want to use google cloud for hosting purposes.

**Comment by Barbosik** [comment]
@overkil: if it's 0.238 ms, then it's network issue, because there is no lag on server side

**Comment by overkil** [comment]
@Barbosik so I tested the connection of the VM and the download speeds fluctuate around 60Mbits/s and upload around 25Mbit/s so connection is not an issue. 
I asked google support if the VM's resources were being shared with someone else resulting in low hardware performance, they replied "no".
I asked google if there was a proxy/CDN between the players and the server/VM, they replied "no".
So I did a ping test and network diagnosis using mtr for windows (winmtr). The average ping was 436ms with minimum 403ms and maximum 523ms.
The network diagnosis result with winmtr was:
![image](https://cloud.githubusercontent.com/assets/20659549/17785511/8aee987e-659a-11e6-91d4-459174d18585.png)
The pings are too slow even though the server is located in the same region as me. I have asked more questions at google and sent them the results too. Thought I would update here too for any possible help. 
Thanks!

**Comment by Barbosik** [comment]
ping 400-500 is very slow and it will be completely unplayable with such high ping. 
Are you connected to internet through satellite? I never seen so high ping with usual connections :)

**Comment by NatsuTheGreat** [comment]
Lmao my internet has gotten about 3000 ping before. But all of it good now :)

**Comment by overkil** [comment]
@Barbosik It is not just me who is getting such slow pings but everyone who did the ping test are getting slow pings to the VM. 
I heard from google and they have two questions about the game server. If you could assist me with this, I would be able to answer them. The questions are;
1- Can you please provide us more details on how this game server works?
2- Also, is the game server composed of an app server plus database?
Thanks again :)

**Comment by Barbosik** [comment]
1- it opens http server to accept WebSocket connections from clients. Each client receive websocket messages with game world update in realtime (with 40 ms interval). Client also can send small websocket messages to the server with user actions.
2- no, the game server is node.js process with game world physics. It doesn't need database and file operations, it just running in memory, accept client connections and sends world update messages for each connected client.

**Comment by Barbosik** [comment]
Long ping response indicate that your server connection has high latency, it means that there is some network bottleneck. 
Ping more than 50-ms is almost unplayable for any online game with realtime physics. 
So, you need to fix ping issue in order to remove game lags.

**Comment by NatsuTheGreat** [comment]
20 - 25 MS is the most you can go without the user really noticing the slow speed.

**Comment by overkil** [comment]
Thank you for your help @Barbosik and @NatsuTheGreat. You guys were more help then the google support. I fixed the lag issue. As Barbosik mentioned that I need to fix the ping issue to remove the lag, I did exactly that and the server is completely lag free now.
What I did was take the google cloud VM away from where I am. I am in Asia and so I initially had the VM created in Asia for better ping but much to my dismay, when I tested the pings to many servers from everywhere in the world using different services and platforms like twitch servers among others, everytime I got very fast pings to servers in europe and got very slow pings to servers in Asia which is where I am. Pings to US and australia were slow too. So I moved the VM to europe and the server doesn't lag for me or my friends in europe anymore. 
However, what I dont understand is, why do I get better pings to europe than in asia itself which is where I am? 
This also explains me why the east asian servers on agar.io lag for me but the european doesnt. 
Anyways, problem resolved. And thank you for the awesome support! :)

**Comment by lulzyyy** [comment]
http://winmtr.net/

Check this program. It'll give you answer why you have high ping. Propably proxy servers are causing problems.

**Comment by overkil** [comment]
@lulzyyy yes I did try the network diagnosis using winmtr. Everything seems to be fine. I will ask my ISP about this for more information.
@Barbosik One little question before I close this issue. I want to keep the SSH session alive on my VM so the server is accessible by anyone anytime. I did this with tmux. Is this the right way to do it? And what would happen when no one is playing on the server for hours because the server will go idle for such a long time then and the SSH session could get disconnected? Could that happen or would tmux prevent that from happening?
Also, can I execute commands for the server like giving someone mass, merging someone, seeing the playerlist, killing someone, kick/ban someone etc., right from the server/game chat or do I have to keep going back to the SSH session?
Thank you :)

**Comment by Barbosik** [comment]
if you're run server in tmux terminal session. then you can close SSH session and server will continue to work in tmux session. 
At any time you can connect with SSH and attach to tmux session with running server by executing command `tmux attach-session -t 0`, where 0 - is session ID.
To detach from tmux session you can press <Ctrl>+<B> and then <D>.
To rename tmux session you can press <Ctrl>+<B> and then <$>, after that tmux will ask you for a new ID for the current session.

Commands like mass and other is available from server console only. In order to execute it from chat, you need to add appropriate commands to PlayerCommad.js
