### ISSUE TITLE
Anyone have a good client for MultiOgar?

### ISSUE THREAD

**Issue by mrzack506** [Barbosik/MultiOgar#294]
Would be very useful and would help me understand more about clients.

**Comment by Barbosik** [comment]
I'm working on the client for MultiOgar. Will be published soon. 

Here is screenshot how it looks now:
![Screenshot](http://i.imgur.com/IqUbj2D.png)

**Comment by mrzack506** [comment]
Thank you very much. This will help me create my own client, with my own features and once I'm done, I will release it. Cheers, and tell me when you're done with it,

**Comment by nuclearc** [comment]
@Barbosik can you make it for public servers?

**Comment by Barbosik** [comment]
@nuclearc: no, vanilla servers doesn't allow connections from non-vanilla clients

**Comment by nuclearc** [comment]
then how i connected once?

**Comment by CalvinDKHD** [comment]
Can i get a client please?

**Comment by firelightning13** [comment]
> I'm working on the client for MultiOgar. **Will be published soon.**

**Comment by CalvinDKHD** [comment]
ok fire! thanks, where will you post it? in the issues? otherwise send it to my email here - calvinleonhardt@gmail.com

**Comment by ItzLevvie** [comment]
^^ Please read the comment above.

**Comment by CalvinDKHD** [comment]
i did, but he doesnt say where.

**Comment by ItzLevvie** [comment]
^^ https://github.com/Barbosik/MultiOgar/issues/294#issuecomment-239910902

**Comment by CalvinDKHD** [comment]
Yeah i know, cool. but doesnt specify where.

**Comment by firelightning13** [comment]
lol
![2016-08-25_13h54_47](https://cloud.githubusercontent.com/assets/17120382/17958348/aa32f37a-6acb-11e6-9d36-06219182988e.png)

**Comment by nuclearc** [comment]
@Barbosik what font are you using for your client?

**Comment by Megabyte918** [comment]
i dont think its gonna be published :/

**Comment by nuclearc** [comment]
then i think i'm gonna make this thingy public:

![image](https://cloud.githubusercontent.com/assets/8341270/19019112/05ef7d50-888b-11e6-9dfa-b327f381b51e.png)

**Comment by CalvinDKHD** [comment]
Nuclear xD I'm gonna a publish the client you and I made and pls answer on
Skype!
