### ISSUE TITLE
borders

### ISSUE THREAD

**Issue by supportAC** [Barbosik/MultiOgar#297]
I trying making a border like agar.io , but have a problem
![image](https://cloud.githubusercontent.com/assets/20979049/17669860/b947ab46-62e5-11e6-9d94-3d9a226615b3.png)

what is this?

i mean wing green part of the cell that you can see

**Comment by NatsuTheGreat** [comment]
Don't make issues about OgarUL Clients HERE. ***THIS IS NOT OGARUL***

**Comment by supportAC** [comment]
IS A CIGAR CLIENT..

**Comment by supportAC** [comment]
agariocity use multiogar , check on ogar-tracker.tk

**Comment by NatsuTheGreat** [comment]
Well if it's a Cigar client *THEN ESPECIALLY WHAT ARE WE GOING TO GO*

**Comment by supportAC** [comment]
ok..

**Comment by NatsuTheGreat** [comment]
You need to understand that that graphics are not server side, therefore, you're in the wrong issue area. We can't do anything to help you with that graphic issue. Go to Cigar, and make an issue [there](https://github.com/CigarProject/Cigar/issues)

**Comment by supportAC** [comment]
ok thx
