### ISSUE TITLE
High Cpu

### ISSUE THREAD

**Issue by MertOtrk** [Barbosik/MultiOgar#30]
0-20 User => %40 - %60
20-60 User => %80 - %100
60 + => %100.5

How i can fix this ? My server is too laggy.( if 60 >USER ) İ have 128 GB game server. 

![screenshot_1](https://cloud.githubusercontent.com/assets/14320594/15984202/aca73322-2fcb-11e6-8a52-78a4d1671ae6.png)

**Comment by SimonOrJ** [comment]
You might just need a server with better CPU clock speed.  Ogar or MultiOgar is not so light as it stands now.  Even my VPS server suffers from lag with around 15 player online.

**Comment by Barbosik** [comment]
I found the root of cause. Currently working on fix for that. It also should fix memory leaks

**Comment by Barbosik** [comment]
fixed

**Comment by Barbosik** [comment]
you can use status command to get server performance info.
Now it shows current update time and lag level evaluation. 
Ideal time is smaller than 35 ms.

**Comment by Barbosik** [comment]
**SimonOrJ**: could you please update your server. 
The latest change should resolve lags. At least now it can run up to 100-200 bots with no lags and no memory leaks at all.
Let me know if you will have issue with "warning: recursive process.nextTick detected".

**Comment by MertOtrk** [comment]
Same problem :(
