### ISSUE TITLE
Eject mass and Virus Split

### ISSUE THREAD

**Issue by PrinceDark9243** [Barbosik/MultiOgar#302]
the eject mass go faster then vanilla in vanilla eject mass go slower to range and virus is too fast
excuse My English i am not an English GUY!

**Comment by Barbosik** [comment]
eject speed is exactly the same as vanilla

**Comment by PrinceDark9243** [comment]
no i mean going speed is very fast!

**Comment by Barbosik** [comment]
it's the same fast as vanilla

**Comment by firelightning13** [comment]
@PrinceDark9243 Can you be more specific?
