### ISSUE TITLE
text ???????????  

### ISSUE THREAD

**Issue by HEROx29** [Barbosik/MultiOgar#309]
http://prntscr.com/c98dr6
can I add another type

**Comment by nuclearc** [comment]
you can change everything to uint16 (unicode)

**Comment by SimonOrJ** [comment]
Just set ServerChatAscii https://github.com/Barbosik/MultiOgar/blob/master/src/gameserver.ini#L67 to 0.

**Comment by Barbosik** [comment]
just change 'serverChatAscii = 0', as suggested by @SimonOrJ
