### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nuclearc** [Barbosik/MultiOgar#311]
Why 'skin' command is not working when already spawned? Server just needs to add 'isSkinPresent' flag if that flag doesnt exist on current node and send 'addNode' again for that node. Here is what I got on my server:

![lol3](https://cloud.githubusercontent.com/assets/8341270/17918525/ba42d00a-69d6-11e6-8e5b-96e3c1c64f35.gif)

**Comment by Barbosik** [comment]
because it affects server performance dramatically and significantly increase network traffic

**Comment by nuclearc** [comment]
@Barbosik i mean just fix 'skin' command to change skin even when player already spawned. It'll not decrease server performance much, right? And network traffic won't be so much, just your 3,9 MB will be sent in one tick (it'll not be even 3 MB because not every player sees changed nodes). It also will fix 'name' command to change name in-game (how did old version of Ogar). But it's your project if you dont want to do that. Maybe you are right, because that server I showed above is written in C++ and is Running on localhost.

**Comment by Barbosik** [comment]
sending name and skin update in each update packet leads to high lags, the game will be completely unplayable due to extreme high lags. It works ok for single player and localhost, but it doesn't works ok for real server.

**Comment by nuclearc** [comment]
what about sending name and skin only when name or skin changed?

**Comment by Barbosik** [comment]
it requires algorithm to track what name/skin was sent to each client and to find if clients needs update or not. It will slow down the server and will not provide any benefit for server. I don't think it's good idea to add lags just to support some console commands which is actually don't needed for server.
