### ISSUE TITLE
Question for Barbosik

### ISSUE THREAD

**Issue by CalvinDKHD** [Barbosik/MultiOgar#312]
Sup! so i saw you said you would release a client soon!
https://gyazo.com/8a555a93b4d877c35ddadadf684c7e02
Is there anyway i can get the files? because it looks amazing!
Or any estimate when done?

Thanks from Calvin!

**Comment by Barbosik** [comment]
publish of source code is not planned, it will be available for playing, but not for copy-paste to another site.

**Comment by CalvinDKHD** [comment]
ohh ok, uhm. Is there a free one then?

**Comment by arxn** [comment]
barbosik what is your skype?

**Comment by overkil** [comment]
@Barbosik where will the client be available? And does this client improve the gameplay in anyway than the ones currently available that support multiogar?
