### ISSUE TITLE
Remove the Multiogar version message?

### ISSUE THREAD

**Issue by CalvinDKHD** [Barbosik/MultiOgar#316]
Hey so this message appears, and i see no option for it / https://gyazo.com/b6e98403e518a5193d5202592a01c495

can i change it or remove it?

**Comment by ItzLevvie** [comment]
You can change it on here: https://github.com/Barbosik/MultiOgar/blob/master/src/PacketHandler.js#L77

**Comment by CalvinDKHD** [comment]
Thanks!
