### ISSUE TITLE
Skins?

### ISSUE THREAD

**Issue by CalvinDKHD** [Barbosik/MultiOgar#317]
Hey so i opened my client and clicked play and did <al> and it didnt work. BUT! i did set the right directory and everything https://gyazo.com/fd8fd3cd0f031c8c4285b9e744137af8
https://gyazo.com/2f11ee426f9c4bff620a72348056dadd

anything i need to enable in multiogar?

**Comment by ItzLevvie** [comment]
If you're using Cigar's client then I believe it should be [skinname]

**Comment by lulzyyy** [comment]
var SKIN_URL = "./skins/co/";

**Comment by ItzLevvie** [comment]
try it without the ```<>``` or try it with ```[]```

**Comment by CalvinDKHD** [comment]
ok

**Comment by CalvinDKHD** [comment]
ok

**Comment by CalvinDKHD** [comment]
nope

**Comment by CalvinDKHD** [comment]
https://gyazo.com/1f8bdee1397102f85ac30edd9f223451

**Comment by CalvinDKHD** [comment]
And when i drag the client on the desktop... it has a white screen when i open the index.  https://gyazo.com/a96e1fc26d609d943b9e850804cf2b3e

**Comment by agariotips** [comment]
in `knownNameDict` , you need to put all of the skins' names. Example: 
![dgsg](https://cloud.githubusercontent.com/assets/19736068/18068174/1b211748-6e0e-11e6-80b9-b4373cd5a6fc.JPG)

**Comment by ItzLevvie** [comment]
^^ Oh yeah, I forgot about that xD

**Comment by CalvinDKHD** [comment]
lol ill try!

**Comment by CalvinDKHD** [comment]
doesnt work even if i put the name in the knownNameDict

https://gyazo.com/9d8440bd220e700a890e2843d50816ee
https://gyazo.com/f4673e23bcd4e8fea027ed59b54fcd86

**Comment by agariotips** [comment]
You're not supposed to use <>, you use  [skinname]

**Comment by agariotips** [comment]
Don't use <> use [skinname]
