### ISSUE TITLE
I want to increase player speed manually like in the ogarul

### ISSUE THREAD

**Issue by fayizan** [Barbosik/MultiOgar#318]
How could I increase player speed manually like in the ogarul.

The default player speed option in multiogar is option 1-deadly slow and 2-ultra fast.

**Comment by Megabyte918** [comment]
It doesn't have to be 1 or 2, it could be 1.1, 1.2, 1.3, etc

**Comment by Barbosik** [comment]
use 1.5 or 1.2 for example

**Comment by fayizan** [comment]
thank you so much @Megabyte918  and @Barbosik
