### ISSUE TITLE
About Eject.

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#32]
This is Multi-Ogar Master.
![multi](https://cloud.githubusercontent.com/assets/19770308/15984219/db7cf744-2ffe-11e6-89cc-a71cb734beb1.PNG)

And This is Vanilla Agar.io.
![vanilla](https://cloud.githubusercontent.com/assets/19770308/15984221/e29d94b6-2ffe-11e6-9ecf-bb7bad9095a7.PNG)

Yee, 
When Ejected,
You are able to see The Multi-Ogar can through eject cell and eject cell.
But Vanilla Agar Have regular distance eject cell and eject cell.

(I will find little bug forever!)

**Comment by Barbosik** [comment]
I know it. Currently ejected cells not processed with collision detector in order to get better performance.

**Comment by Chancerst** [comment]
@Barbosik Um.. OK.
So, You don't fix it?

**Comment by Barbosik** [comment]
it's not critical issue, I will fix it later

**Comment by Barbosik** [comment]
I implemented a new physics engine, and this issue were fixed
