### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by PrinceDark9243** [Barbosik/MultiOgar#328]
i want to make any entity does not bounce from the border like mobile agar.io can someone help plz!

**Comment by PrinceDark9243** [comment]
and when i reach the max limit of mass the server will set my mass to max mass does not split me!

**Comment by Megabyte918** [comment]
try reverting the edits in cell.js from this https://github.com/Barbosik/MultiOgar/commit/12617a30685b1c34d76b66908c562a7405ae8146
and for autosplit revert any edits you have made to the `updateMoveEngine` function in GameServer.js

**Comment by PrinceDark9243** [comment]
i dont know about codding can someone make that code for me?

**Comment by Megabyte918** [comment]
The code is already there, just do what I said and you'll be fine. Nobody can make it for you as your version seems to be different from the current one

**Comment by PrinceDark9243** [comment]
This Thing is out of my mind @Megabyte918 Can you do it for me and then send the server to me plz!

**Comment by Megabyte918** [comment]
send me your cell.js and gameserver.js

**Comment by PrinceDark9243** [comment]
Unfortunitly Github does not allow me to upload files so download the files from here http://www.4shared.com/zip/ib_fqGixce/MultiOgar.html?

**Comment by PrinceDark9243** [comment]
My bad English

**Comment by Megabyte918** [comment]
@PrinceDark9243 Do you have skype/discord? it would be easier to communicate and send files we wont have to do it on here. And i dont trust 4shared :P

**Comment by PrinceDark9243** [comment]
ok i have skype : zaidmemon37

**Comment by PrinceDark9243** [comment]
quickly add me then i will remove my comment!

**Comment by Megabyte918** [comment]
I added you, please close this =D

**Comment by PrinceDark9243** [comment]
Yea it is good to be have an Coding Pro Friend!
