### ISSUE TITLE
Start game bug

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#33]
Sometimes (rarely) when player join game server creates for him 2 cells with different colors. These cells appearing with distance between each other.

**Comment by SimonOrJ** [comment]
This happened to me on original Ogar.  It's happening when the cell spawn from an ejected mass and as a new cell at the same time.

**Comment by F0RIS** [comment]
Thx for additional information

**Comment by ItzLevvie** [comment]
The problem is to do with this code https://github.com/Barbosik/MultiOgar/blob/master/src/gamemodes/FFA.js#L63

**Comment by F0RIS** [comment]
no, i don't think that this will really solve the issue. I checked code, there are just 2 calls of gameServer.spawnPlayer(player, pos, startMass)  so we need leave one call or insert return operator in right place. That's all

**Comment by ItzLevvie** [comment]
Anyways the return or the code above works fine for me.

**Comment by Barbosik** [comment]
Strange, I never seen such issue, but I will check it

**Comment by Barbosik** [comment]
I think it should be fixed now, let me know if it will be reproduced again
