### ISSUE TITLE
thnx barbosik and ur team

### ISSUE THREAD

**Issue by hossem123** [Barbosik/MultiOgar#331]
i have pro c9 account if u want a hot workspace pm
hot workspace (Keeping a server running after closing the browser)
![capture](https://cloud.githubusercontent.com/assets/18426424/18281236/6df8ca16-745c-11e6-9e42-f23478e9cd15.PNG)

my server : 
warriors-bots-ogarioa.c9users.io:8081
warriors-ogarioa.c9users.io:8081
warriors-instan1-ogarioa.c9users.io:8081
warriors-team-ogarioa.c9users.io:8081
bigserver-ogarioa.c9users.io:8081
warriors-instan2-ogarioa.c9users.io:8081
i make website with edited c0nsume client http://agar.is-best.net 
thnx ;)

**Comment by ItzLevvie** [comment]
Read https://community.c9.io/t/can-i-use-cloud9-for-hosting/16. 

Anyways, I'll raise this issue to the Developers of C9 as it's unfair for other people.

**Comment by hossem123** [comment]
(-_-!

**Comment by hossem123** [comment]
![tumblr_ndlbkn0gd71rl38qso1_1280](https://cloud.githubusercontent.com/assets/18426424/18289853/6f56a6ba-7481-11e6-8eeb-9b7e8d55d909.jpg)

**Comment by ItzLevvie** [comment]
Just so you know I took a screenshot of the entire issue :)

**Comment by hossem123** [comment]
you destroyed my dream

**Comment by NatsuTheGreat** [comment]
How did she?
