### ISSUE TITLE
Help, my server is very Lageado

### ISSUE THREAD

**Issue by Jhair2015** [Barbosik/MultiOgar#335]
Help, my server is very Lageado

I give host c9.io and upon entry is very Lageado, until a few days ago was not so ...

PLEASE solution: =)

**Comment by ItzLevvie** [comment]
Don't use C9 for hosting servers.

**Comment by Jhair2015** [comment]
THX i am use a nitrous, is very complicated nitrous

**Comment by David1ali12** [comment]
rip c9 I was hosting 50 servers but now they did an update when run the server , the server will have crazy lag . rip

**Comment by MastaCoder** [comment]
Well they slowed it down because most people like you abuse the service. It was supposed to be for testing, not hosting.

**Comment by Barbosik** [comment]
c9 is not intended to be used for ogar servers hosting
