### ISSUE TITLE
Need help about the border problem!

### ISSUE THREAD

**Issue by siamkcs** [Barbosik/MultiOgar#336]
http://i.imgur.com/5bAPH7d.png
http://i.imgur.com/RDdY5xV.png

I get a border problem , need help!!
I use the agarplus client from sakuramoti and I use Multiogar v1.2.69
In this case , players can go outside the red line border but they can't go to the A3 ~ A5,B3 ~ B5 , C1 ~ C5 , D1 ~ D5 , E1 ~ E5

Sorry for my bad English

**Comment by nuclearc** [comment]
try to use scramble level 0

**Comment by siamkcs** [comment]
I tried it but it never works
http://i.imgur.com/jjRUnW1.png

**Comment by nuclearc** [comment]
then it's clients problem, not server's

**Comment by Barbosik** [comment]
it's a bug in your client
