### ISSUE TITLE
Why is it so?

### ISSUE THREAD

**Issue by Koarashi-SNkms** [Barbosik/MultiOgar#339]
I created myself website for agar.io
but, I spectate other people will be some question
watch is viedo: https://youtu.be/15Wu2K49eCM
Why is it so?

my english not good, sorry.
I am Taiwanese

**Comment by NatsuTheGreat** [comment]
This seems like OgarUL Client, not something that you created.

**Comment by dinhduynhat** [comment]
like this ugunz.info/nuotca

**Comment by dinhduynhat** [comment]
you can cooperate with me on agar.io ?

**Comment by agarowolf** [comment]
como puedo hacer un server para todos tengo mi agario pero me falta los servidores ayudame y tea ago parte de mi agario

**Comment by agarowolf** [comment]
as I can make a server for all I have my agario but I need help me and tea servers ago part of my agario
