### ISSUE TITLE
Can someone host a Server with these Config.

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#342]
We are 3 clans and we always play with these configs , alot of players 
any1 who host can gain alot of players and there should be auto restart every 15 mins

1- 32 split 
2- 2k start mass
3-no viruses 
4-eject size 70
5- eject lost 68
thx if you host it please comment below around 80 players 
and srry for asking Ik thisn't a place for this

**Comment by Jhair2015** [comment]
I can go and do MULTI OGAR bots for server :)

**Comment by NatsuTheGreat** [comment]
Not what he was asking for.

**Comment by MastaCoder** [comment]
I can set this up, give me 30 minutes.

**Comment by MastaCoder** [comment]
Added something close to this idea, not exactly it. 

http://abs0rb.me - Crazy Reverse
