### ISSUE TITLE
Need Minion Feature

### ISSUE THREAD

**Issue by fayizan** [Barbosik/MultiOgar#346]
I want the same Bot Gamemode which the agarlist.com having right now,please help me

![screenshot_295](https://cloud.githubusercontent.com/assets/19163419/18588758/696faad2-7c45-11e6-8fff-3a36817d80d3.png)

**Comment by Jhair2015** [comment]
@fayizan ayizanI think the creator of agarlist with Ogar Ogar combine multi Unlimited

For minions,

I'm looking minions temién for this server "MultiOgar", but found only minions that do not reappear and have no support skins and graphics RETINA

**Comment by AlexandriteErikParacelsus** [comment]
David Ali made that gamemode, and yes he won't give the code out.

**Comment by NatsuTheGreat** [comment]
Yeah I helped him make the minions a complete success. But that's not happening on MultiOgar, so this issue is just a waste.

**Comment by David1ali12** [comment]
not for share code ur self

**Comment by fayizan** [comment]
@David1ali12  ok np,thnks for that gamemode tho in agarlist.com I love it..!! thnk u @David1ali12
