### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by cowpits** [Barbosik/MultiOgar#352]
So far this is the best Ogar server I've ran, smooth and no lag. All the commands work, amazing. 
The only thing I request if chat can be moved from the anime client to the regular ogar client. On my server no one ever connects to ogar.mivabe.nl no one really likes it honestly. Otherwise, thank you.

**Comment by arxn** [comment]
as ogar.pw ?

**Comment by cowpits** [comment]
yes but using the agar.io client so it's vanilla but with chat.

**Comment by cowpits** [comment]
here's my server https://goo.gl/LcTLWs vanilla and this https://goo.gl/GgDIXD which has the anime and chat.

**Comment by MastaCoder** [comment]
no you can't.

**Comment by SimonOrJ** [comment]
I'm not sure if there's a "regular ogar client".  The common client is the official client, agar.io.

There is a way to prevent players from connecting to your server from "ogar.mivabe.nl", if that's what you're asking.

**Comment by cowpits** [comment]
Actually no one connects through ogar.mivabe.nl, my server is always busy on average there are at least 20 players and max it hit 59. Sometimes they want to chat me to give them mass and they can't but they won't use ogar.mivabe.nl either. They think it's weird. 
If it's not possible it's fine, I understand agar client restrictions.

**Comment by MastaCoder** [comment]
Just make your own client :)

**Comment by cowpits** [comment]
I wouldn't mind delving into making my own client but don't know where to start. 
What I realized is players don't like to connect through anything other than the Agar.io client. Players like to feel they're playing real agar and surprisingly enough my server is getting very popular. This weekend it was hitting up to 80 + players and no lag.
