### ISSUE TITLE
Can't run MultiOgar!

### ISSUE THREAD

**Issue by mhmdslah123** [Barbosik/MultiOgar#358]
when i launch it it just says : 
![default](https://cloud.githubusercontent.com/assets/22558032/19013349/b7414efe-87d6-11e6-9506-81422830f568.PNG)
please help

**Comment by nuclearc** [comment]
install dependencies

**Comment by mhmdslah123** [comment]
how? i cant find it

**Comment by mhmdslah123** [comment]
Ty Bro <3

**Comment by SimonOrJ** [comment]
@mhmdslah123 Consider closing the issue if it is resolved. :)

**Comment by ItzLevvie** [comment]
This error is based on Ogar-unlimited not MultiOgar

**Comment by NatsuTheGreat** [comment]
EXACTLY WHAT I NOTICED And these OgarUL kids coming to MultiOgar. -_-
