### ISSUE TITLE
[INVALID]

### ISSUE THREAD

**Issue by CalvinDKHD** [Barbosik/MultiOgar#361]
Sup community! Me and Nuclear made a client and tried to make it look like the agarplus client. It has a map (a little glitchy) and a chat. AND DONT CLAIM THIS AS YOUR OWN, GIVE US SOME CREDIT TOO!
BTW SKINS DONT WORK, i have no idea why.
But here!

**Comment by Xeeroo** [comment]
How to get that client to work?Simply put in the MultiOgar folder?

**Comment by Jhair2015** [comment]
lol :D

**Comment by Jhair2015** [comment]
YOU HAVE @CalvinDKHD a Tutorial :)?

**Comment by dinhduynhat** [comment]
Mini map error :)) not working

**Comment by CalvinDKHD** [comment]
Minimap should work, i mean the only thing you need to do is go into the
index and you will see where to place the IP in.

**Comment by CalvinDKHD** [comment]
Ill make tutorial soon!

**Comment by dinhduynhat** [comment]
are you have client Login Facebook or use skin name or Click to choose skin ?

**Comment by damin16** [comment]
@dinhduynhat I don't think it's possible to have Facebook login

**Comment by CalvinDKHD** [comment]
No, i can try making a client that does that!

**Comment by CalvinDKHD** [comment]
But i cant get skins too work.

**Comment by SimonOrJ** [comment]
You should create a GitHub project and put the code on it instead of bundling it as a .zip and uploading it on another project.  That'll give more control over your project.

**Comment by CalvinDKHD** [comment]
Alright, will do!

**Comment by agariotips** [comment]
[Main_OutFix.zip](https://github.com/Barbosik/MultiOgar/files/507094/Main_OutFix.zip)
Fixed skins. Protocol 5 fixed a bit too
