### ISSUE TITLE
Permission to Use

### ISSUE THREAD

**Issue by Andrews54757** [Barbosik/MultiOgar#362]
Hello, @Barbosik ,

I am thinking of using your code (GameServer.js:resolveRigidCollision()) in my project https://github.com/AJS-development/Project-Nehemiah. I am asking you because I believe that people shouldn't plagerise. If you accept, I will place the code in my project. But if you don't, I will seek alternative methods. I find your code interesting because it is simple yet effective. Here are my terms.

TERMS
1. No license required, although a comment will say your name and original source.
2. No special deals.
3. No monetary requirements

Andrews54757,
AJS Development

(note that this is generated from a saved response)

**Comment by MastaCoder** [comment]
.. The code is under the Apache2 license.. Pretty sure you're allowed to take code but need to leave credit.

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)

**Comment by Andrews54757** [comment]
"Term 1: No license required, although a comment will say your name and original source"

**Comment by MastaCoder** [comment]
My question is why are you asking him if you can use open source code, and why the heck do you have terms as well?

It's an open source project, take the code, it's literally right there. You can't be put into legal action for it or anything.

**Comment by Andrews54757** [comment]
I am an honest person. I do not like to plagerise. This is why I am asking this

**Comment by Barbosik** [comment]
it's already published under Apache 2 license. It means that you can use it as you wish. All what you need is to mention that your modification is based on this my code. And you can modify it as you wish, and you can publish it as you wish

**Comment by Andrews54757** [comment]
Ok
