### ISSUE TITLE
Extension ?

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#363]
What extent did you use for this?
![dddddddddd](https://cloud.githubusercontent.com/assets/18537420/19095340/8d809be6-8a6b-11e6-9654-a2292ebdaa97.png)

**Comment by SimonOrJ** [comment]
It's Barbosik's own client.  He programmed it himself.

**Comment by GhostShot3** [comment]
@SimonOrJ You have the dowload ?

**Comment by SimonOrJ** [comment]
I don't have it, and even if I had the code, I wouldn't post it without the coder's permission.

The client in the picture was made for demonstration/testing purposes, and it would require tweaking on the server side.

... though it would be a perfect tool to use for moderating the server.  Why do you want the program anyway?

**Comment by GhostShot3** [comment]
@SimonOrJ Im learning programming,this well if you can not publish here :)
