### ISSUE TITLE
"value is out of bounds" error

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#37]
Hello!  I run a somewhat modified instant-merge server.

After the server was running for 10 minutes, this error just spammed the server console.
```
TypeError: value is out of bounds
    at checkInt (buffer.js:823:11)
    at Buffer.writeInt16LE (buffer.js:991:5)
    at Array.<anonymous> (/home/simonorj/server/instantmultiogar/src/packet/BinaryWriter.js:42:16)
    at BinaryWriter.ToBuffer (/home/simonorj/server/instantmultiogar/src/packet/BinaryWriter.js:119:25)
    at UpdateNodes.build4 (/home/simonorj/server/instantmultiogar/src/packet/UpdateNodes.js:89:19)
    at UpdateNodes.build (/home/simonorj/server/instantmultiogar/src/packet/UpdateNodes.js:17:36)
    at WebSocket.sendPacket (/home/simonorj/server/instantmultiogar/src/GameServer.js:1177:29)
    at PlayerTracker.update (/home/simonorj/server/instantmultiogar/src/PlayerTracker.js:275:17)
    at GameServer.updateClients (/home/simonorj/server/instantmultiogar/src/GameServer.js:403:30)
    at GameServer.mainLoop (/home/simonorj/server/instantmultiogar/src/GameServer.js:490:10)
```

The status command:
```
>st
[Console] Connected players: 12/64
[Console] Players: 12 - Bots: 0
[Console] Server has been running for 11 minutes
[Console] Current memory usage: 20.8/56.2 mb
[Console] Current game mode: Free For All
[Console] Current update time: 16.000 [ms]  (perfectly smooth)
```
In between this output is a huge spam of the TypeError.  I had to stop the server because this was happening too much.

I got another set of error again after around 10 minutes into the restart, but that only lasted 9 ticks (nine TypeErrors).

Does anyone know what went wrong?

Update: I got another set of the same error, this time for around 300 ticks.  Then it disappeared again.  This happened at 65 minute mark with 10 players on (and 4 players playing).

(On the other note, it looks like the memory leak is fixed for good :D)

**Comment by Barbosik** [comment]
Probably it's because some value in the cell has invalid value. Did you used latest packet\* source? Because previously it has some mistakes which can raise this error even for good values. 
But I fixed it in this commit: https://github.com/Barbosik/MultiOgar/commit/73482c11056319396526f537435385be1dba6b9b

**Comment by SimonOrJ** [comment]
The server is running based on the latest commit.  That is really weird.

I updated the zip file link I sent you in through Reddit PM.

**Comment by Barbosik** [comment]
ok, need to catch it, at a glance it looks that some value (position or nodeId, or color for example) has invalid value which is out of range. Could you please show the line 89 of UpdateNodes.js from version which throws this error?

**Comment by Barbosik** [comment]
Aha... found it! It looks like cell position. It's out of range for Int16. It's because you're using shifted map position.

There are two solutions for this issue, you can use any:
1) Just set serverScrambleCoords = 0
or
2) Fix your border size in gameserver.ini, the center of the border should be at position 0, 0. 
It means that this border config is incorrect and will leads to such error:
```
borderLeft = 0
borderRight = 14000
borderTop = 0
borderBottom = 14000
```

And this one is correct and should not raise errors:
```
borderLeft = -7000
borderRight = 7000
borderTop = -7000
borderBottom = 7000
```

Under the hood: if you're using shifted border, the cell coordinate after scrambling may not fit to Int16 value range and in such case you will get error.

There is need to replace these borderLeft, borderTop, borderRight and borderBottom with borderWidth and borderHeight to avoid such issues

**Comment by SimonOrJ** [comment]
This is odd.  It doesn't seem to happen with official client.  However, it happens with unofficial clients, such as http://play.ogarul.tk/?ip=vps.simonorj.com:24270 .

This must be an issue with protocol 4 or the unofficial client.  Everything works fine when everyone uses the official client.  However, when the player on the unofficial client goesoutside around the position 14000, it starts giving the errors.

I will try the border tweak.  The current border size is 18000.

**Comment by Barbosik** [comment]
yes, it's because protocol 4 uses Int16. Official client uses protocol 8 with Int32 for cell coordinate, so it can use much wide range for cell coordinates.

**Comment by Barbosik** [comment]
At the moment you can correct border settings or disable serverScrambleCoords.
Later I will add fix for that.

**Comment by Barbosik** [comment]
just completed new collisions engine, now started to investigate your mod. Just want to optimize new engine for your mod. I see that currently your server has some lags. Needs to catch the bottle-neck.
Do you running the same version which you shared in zip?

**Comment by SimonOrJ** [comment]
It is the code that runs the server.  You can use `git diff origin/master instantmerge` to check the changes I made for the server.

**Comment by SimonOrJ** [comment]
The coordinate fix works well.  I've made the top/left borders -9000 and bottom/right borders 9000, and it seems to solve the problem.  This should be documented somewhere.

I've pulled the new commit that includes new collision engine.  I updated the zip file again.

**Comment by Barbosik** [comment]
Currently I implemented high-speed quad-tree based collision search algorithm.
I'm testing it now. At a glance works good. Now I'm able to run up to 500 bots :)
Need to solve some issues and it will be ready for commit soon.

**Comment by Barbosik** [comment]
fixed
