### ISSUE TITLE
File that handles cell color

### ISSUE THREAD

**Issue by tveloper** [Barbosik/MultiOgar#375]
Hello,

I am trying to use the chat login system, and I am trying to make certain color ADMIN only, so I want to exclude certain colors from the cell color list. Is there a file that handles all cell colors?

Thanks.

**Comment by Jhair2015** [comment]
color "ID" on console

**Comment by NatsuTheGreat** [comment]
That's not what he is looking for, @Jhair2015 

@tveloper Are you looking for the cell to be a certain color, or chat name to be a certain color. you can change both, I just need a specification.

**Comment by Jhair2015** [comment]
ok, sorry :)

**Comment by MastaCoder** [comment]
https://github.com/Barbosik/MultiOgar/blob/master/src/packet/ChatMessage.js#L27

**Comment by tveloper** [comment]
@NatsuTheGreat I have already accomplished changing the color using the `packet/ChatMessage.js` file.

When a cell is created, it gets a random color assigned, but I want to delete certain colors from the list.
For example, I don't want anybody to have the red cell color unless I set it manually using `color [ID]` on the console.

**Comment by NatsuTheGreat** [comment]
GameServer.js, getRandomColor();
