### ISSUE TITLE
Hotkeys 

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#376]
Hotkeys Don't work

**Comment by NatsuTheGreat** [comment]
Hot keys as in?

**Comment by Jhair2015** [comment]
Macro fast not is found on never client MultiOgar :/

**Comment by David1ali12** [comment]
thx @NatsuTheGreat  I just downgrade it new version doesn't support hotkeys.

**Comment by MastaCoder** [comment]
MultiOgar has a client?

**Comment by David1ali12** [comment]
@MastaCoder I mean server side it wasn't allowing the client to use hotkeys anyways I just downgrade it.

**Comment by MastaCoder** [comment]
You mean pause between each w or split?

**Comment by David1ali12** [comment]
I meant split @MastaCoder
