### ISSUE TITLE
Disconnected players are not disconnected after some time

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#38]
There is a bug with player disconnection (and a memory leak).  Someone reported that the server went down/stopped responding, so I took a look at what happened.

```
>st
[Console] Connected players: 62/64
[Console] Players: 62 - Bots: 0
[Console] Server has been running for 1210 minutes
[Console] Current memory usage: 1010.4/1094.4 mb
[Console] Current game mode: Free For All
[Console] Current update time: 286.290 [ms]  (extreme high lag)
>lp
[Console] Invalid Command!
>pl
[Console] Showing 62 players:
 ID     | IP              | P | NICK            | CELLS | SCORE  | POSITION
-------------------------------------------------------------------------------
    417 | REDACTED        | 8 | ----------------------------DEAD OR NOT PLAYING
    589 | REDACTED        | 8 | ----------------------------DEAD OR NOT PLAYING
    323 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    514 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    441 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    493 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    498 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    494 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    517 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    444 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    497 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    438 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    496 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    504 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    500 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    253 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    407 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    505 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    501 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    507 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    509 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    506 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    542 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    583 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    543 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    511 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    482 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    515 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    483 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    442 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    488 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    445 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    487 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    439 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    317 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    557 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    490 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    234 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    237 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    495 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    566 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    443 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    446 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    502 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    499 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    265 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    572 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    172 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    256 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    448 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    480 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    503 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    479 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    447 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    481 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    585 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    508 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    486 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    513 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    516 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    484 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
    512 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING
>exit
```

Last time this happened, I just restarted the server.  I did the same this time.  Something is not letting the server let go of these disconnected clients...

**Comment by Barbosik** [comment]
Hm, it looks like not supported clients. What client they used?
Also there is possible IP limit. You can edit IP limit in gameserver.ini.
By default serverIpLimit = 4. It means that only 4 players can connect from single IP, all new players from the same IP will be immediately disconnected.
It's added for bot protection. You can disable it by setting serverIpLimit = 0

**Comment by SimonOrJ** [comment]
I don't think that the disconnect is happening due to protocol 5. (I plan on removing it...)

Also, "[DISCONNECTED]" isn't too specific in case a person is botting by spawning in and refreshing the game.  I once caught an IP of a botter using that method...

**Comment by Barbosik** [comment]
Can you ask those players what client they using? Because 0 in the column P means that their client just connected and don't send any message. If they connected properly and was able to play, this column should be non-zero.

I will add more logs for connection, so you will be able to see all connections/disconnections in the log and the reason for disconnection.

Currently I completely rewritten physics in MultiOgar, now it much faster and cool :)
Almost all works ok. Need to clean the code and optimize some things to commit it

**Comment by SimonOrJ** [comment]
The P column updates to 0 when a player disconnects.  I have no way of asking people what client they use, but I know I only gave out the link to the official Agar.io (Protocol 8) or UnlimitedOgar.io (Unsupported protocol -> Protocol 4), so they should be only using those.

Thank you for all the work you put into this project :D

**Comment by SimonOrJ** [comment]
> I found that you added "|| this.protocol == 5", it will disconnect any player with protocol 5.

I've lifted protocol 5 ban.  I'll see what happens.

**Comment by Barbosik** [comment]
I don't think that ban protocol 5 is a good idea. Because protocol 6+ is used just by vanilla client. Some clients support it, but it's private. So, almost all alternative clients using protocol 5, or sometimes 4.

**Comment by SimonOrJ** [comment]
Yeah; I lifted it as in I'm allowing it.

**Comment by Barbosik** [comment]
I changed ban command for a little:
* blacklist.txt renamed to ipbanlist.txt (so check your .gitignore);
* "severUseBlacklist" renamed to "serverIpBanList";
* "pardon" command renamed to "unban" command to not confuse users;
* performed some refactoring on ban and kick command, now it bans all players with the same ip;
* now ban works even with serverIpBanList=0, but ip list will not be saved to the file (with serverIpBanList it just stored in the memory and will be lost on server restart)

Also I reworked playerlist command, now it shows IP even for disconnected players and shows the reason for disconnection for disconnected players

**Comment by Barbosik** [comment]
I found the reason for the issue with disconnected players. It's because some times disconnection didn't handled properly. I fixed it.
Also, I added serverTimeout variable, to kick players who don't respond for a long time (broken connections)

**Comment by SimonOrJ** [comment]
I've had 718 minutes of uptime, and not another single disconnect ghost showed up.  I'm sure it was the protocol check that caused it in combination of the bug you found. :)

**Comment by SimonOrJ** [comment]
Update: I lied.  One showed up.

`    223 | [DISCONNECTED]  | 0 | ----------------------------DEAD OR NOT PLAYING`

I just pulled the commit, so here's hoping that all works well :D

**Comment by Barbosik** [comment]
Use my latest fix, these connections (if they will appears) will be automatically killed after serverTimeout seconds. 
You can disable it by setting serverTimeout=0, but it may leads to some ghost connections, because network may not notify that connection is broken.

**Comment by Barbosik** [comment]
But don't set serverTimeout too small, because it will kick good players who has some network lag :)

**Comment by SimonOrJ** [comment]
I tried banning player ID 1.  It banned everyone. ._.

**Comment by Barbosik** [comment]
hm, I will check it

**Comment by Barbosik** [comment]
lol, I forgot to add ip check :)

**Comment by Barbosik** [comment]
fixed
