### ISSUE TITLE
Is it just me?

### ISSUE THREAD

**Issue by rjay222** [Barbosik/MultiOgar#382]
Alis.io skins are not saving. When you switch profiles or refresh the page the skins turn back to the default ones.

**Comment by SimonOrJ** [comment]
I'm afraid this has nothing to do with MultiOgar.

**Comment by NatsuTheGreat** [comment]
Yeah, it's that skin issue that Miniclip caused.

**Comment by cowpits** [comment]
Miniclip blocking skins on private servers, as of October 2016 update. I guess they do this because they want people to buy skins and not use them free or try before they buy. Annoying and i'm getting a lot of complaints about it.
