### ISSUE TITLE
`killall` breaks spectate feature

### ISSUE THREAD

**Issue by SimonOrJ** [Barbosik/MultiOgar#383]
When I ran `killall` (because bots made a cell impossibly big), spectating didn't work.  It continued to make the client face the center of the map.

**Comment by Megabyte918** [comment]
I couldn't reproduce this

**Comment by SimonOrJ** [comment]
Could it have something to do with the number of players on the server?

**Comment by Megabyte918** [comment]
I'm not sure... but maybe it had something to do with the size of the cell? For example when I make a cell 100000000 mass, it breaks the client and the screen goes white, then I have to do killall and reload the page and it returns back to normal. Could it have just been another side effect of the mass being too big for the client to handle?

**Comment by SimonOrJ** [comment]
hmm, reloading didn't help for me.  maybe it was just some random incident that required the exact conditions.

**Comment by SimonOrJ** [comment]
Turns out the spectate gets fixed after a while. I don't know what triggered the server to fix the spectating player position.
