### ISSUE TITLE
Easier way to modify

### ISSUE THREAD

**Issue by DaAwesomeRazor** [Barbosik/MultiOgar#387]
Mabye there should be some easier way to mod multi ogar. Mabye a plugins folder or something? I hate having to update multi-ogar and transfer my changes.

**Comment by Megabyte918** [comment]
what do you mean "having to update multiogar" there hasnt been any updates for the past 2 months :/

**Comment by NatsuTheGreat** [comment]
^^

**Comment by MastaCoder** [comment]
Plugins sounds like something from Ogar Unlimited, oh wait nevermind it is.

**Comment by Barbosik** [comment]
there is no need for plugin, because source code is available, so you can make your mod with no problem. 
You can use GIT to track your changes and update management
