### ISSUE TITLE
Older version with properly working extensions

### ISSUE THREAD

**Issue by rjay222** [Barbosik/MultiOgar#389]
# I KNOW THIS IS OLD

Extensions that allow you to tricksplit and double split by pressing one key don't work properly when using multiogar, while playing normally they do. Instead of double split you'll split once, instead of tricksplit you'll double split or something like that. This started to happen after some update a while ago. So what was the last version they used to work? And how do i get it?

**Comment by nuclearc** [comment]
you should remove split cooldown

**Comment by Jhair2015** [comment]
@nuclearc  how?

**Comment by Megabyte918** [comment]
@Jhair2015 like [this](https://github.com/Megabyte918/MultiOgar/commit/822cfe0f362a9c76202aecfb89af561878770b17)

**Comment by Jhair2015** [comment]
@Megabyte918  Sorry for the deconcentration, but that should change in this code

**Comment by rjay222** [comment]
@Megabyte918 Thank you worked

**Comment by Jhair2015** [comment]
@Megabyte918  Sorry, I get it lol xD
