### ISSUE TITLE
How does the XP system work in Agar private ?

### ISSUE THREAD

**Issue by dinhduynhat** [Barbosik/MultiOgar#391]
...

**Comment by nuclearc** [comment]
you must implement your own account system in both client and server

**Comment by MastaCoder** [comment]
^

**Comment by CalvinDKL** [comment]
Hello!
Please contact me on skype - calvin.leonhardt

**Comment by dinhduynhat** [comment]
@CalvinDKL  u have facebook account?

**Comment by Barbosik** [comment]
there is no xp on private servers. Because it requires user authentication but agar user ID is not available for private servers
