### ISSUE TITLE
[INVALID]

### ISSUE THREAD

**Issue by Firekix** [Barbosik/MultiOgar#393]
Hey is there anyway to use Ogar Unlimited Player bots in MultiOgar?
The bots are not competitive in multiogar..
Thank You

**Comment by NatsuTheGreat** [comment]
Go change the AI file.

**Comment by Firekix** [comment]
Plz can u say how to do that

**Comment by Firekix** [comment]
Plz can u say how to do that

**Comment by nuclearc** [comment]
1. go to https://github.com/Barbosik/MultiOgar/tree/master/src/ai
2. right click on BotPlayer.js
3.click 'Edit'
