### ISSUE TITLE
How to make macro like agar.io when tricksplited 16x for MultiOgar

### ISSUE THREAD

**Issue by NameYT** [Barbosik/MultiOgar#403]
I already Changed ejectCooldown from -9999999 and still when i click Ex = 16 x it only split 8x
So what i'm about to do?

**Comment by cowpits** [comment]
I have mine set to ejectCooldown = 1 and playerSpeed = 1.2
when splitting 16x using macro is very fast and ejecting mass using macro is like water. 
Try it on my server https://goo.gl/MKduPV

**Comment by Megabyte918** [comment]
Duplicate of #389 and #399

**Comment by Jhair2015** [comment]
@cowpits Could you help me create my server on ddns.net or the host you use? :)

Please!! :)

**Comment by NameYT** [comment]
@Jhair2015 Try hosting at codeanywhere i have hosted my own server 📦

**Comment by NatsuTheGreat** [comment]
This guy exaggerates way too much.

**Comment by MastaCoder** [comment]
> @Jhair2015 Try hosting at codeanywhere i have hosted my own server 📦

This is why good things never stay.
