### ISSUE TITLE
How to Get Popsplit 10000%

### ISSUE THREAD

**Issue by NameYT** [Barbosik/MultiOgar#404]
Hey @Barbosik How to Change It ? Does it have a settings so i can have 1000% PURE Perfect Popsplit?

**Comment by Jhair2015** [comment]
Configure Gameserver.js

**Comment by NameYT** [comment]
What To Change

**Comment by NameYT** [comment]
![image](https://cloud.githubusercontent.com/assets/20871314/20026662/e2ecba74-a339-11e6-9056-e895f0a849d5.png)
@Jhair2015 This is my server hosted it Contact me on skype : Gian Sambayan Maybe i can help you host ur own server that ur firneds can connect :) Just help me how to get 100000% POPSPLIT ANd What Settings to change :0

**Comment by NameYT** [comment]
@Jhair2015 @Barbosik 
![image](https://cloud.githubusercontent.com/assets/20871314/20026683/45021da8-a33a-11e6-9201-9c5438cad77b.png)I hosted my own server :) Codeanywhere.com is for free :) also what is the settings to change so i can get 1000% POPSPLIT?

**Comment by NatsuTheGreat** [comment]
1000%? Are you f***ing kidding me?

**Comment by Megabyte918** [comment]
lmao

**Comment by AlexandriteErikParacelsus** [comment]
Delete system 32 would help

**Comment by Jhair2015** [comment]
@AlexandriteErikParacelsus  Hahaha lol lmao :vv

**Comment by Y4ssine** [comment]
lol set playerMaxCells to 500 xD
