### ISSUE TITLE
is there anyway to do this on private server?

### ISSUE THREAD

**Issue by bean07** [Barbosik/MultiOgar#41]
[http://imgur.com/7QNBp3c](url)

**Comment by Barbosik** [comment]
what exactly?

**Comment by bean07** [comment]
looks the picture,he feed some mass and he shoot virus then the virus go a line

**Comment by Barbosik** [comment]
it's already works in MultiOgar

**Comment by bean07** [comment]
no its doesnt :(

**Comment by bean07** [comment]
i do it some days ago and when i feed virus there is no mass going to the virus

**Comment by MastaCoder** [comment]
Works for me.

**Comment by ItzLevvie** [comment]
^^ Same.

**Comment by bean07** [comment]
https://media.giphy.com/media/IDeH9eE8cyuIM/giphy.gif :|

**Comment by SimonOrJ** [comment]
Cannot reproduce: [Video](https://1drv.ms/v/s!Ai_k3C9fD8dygaMGo_ukbUbLjIJixA)

This uses the latest commit of MultiOgar at the time of this writing ("collisions refactoring").

**Comment by bean07** [comment]
fixed!

**Comment by Barbosik** [comment]
I fixed some mechanic, so now it works more cool :)
Especially, I recommend to try this behavior on experimental

**Comment by Influxx** [comment]
Tested - works good at a first glance. I notice there is some jittering going on, don't know if this is related to the latest commit. I will report here if I find anything else. Thanks!

**Comment by Barbosik** [comment]
no, it's not related to the latest commit. It's just issue with resolving rigid body collision (see function GameServer.resolveRigidCollision). It works not so good.

**Comment by NatsuTheGreat** [comment]
In order to have virus throw being done like agar.io you'd need the following:

- Spaces in between the shooting viruses. Right now we have the viruses overlapping.
- Proper angling:
     - Viruses will always shoot right when doing a virus throw except for one time that I will talk about. We could use **Math.PI / 2** for this.
- That condition is the virus will go any direction until it's fed 7+
- The last viruses of the virus throw will be big.
I had this all, but now I don't because of the new updateMoveEngine. I can show you a video for more understanding. [Here it is](https://youtu.be/Ms7I65eaXkA?t=427)

**Comment by Influxx** [comment]
Regarding virus shooting (related to Natsu's comment): I noticed that when you shoot a virus, and while the virus is moving, you can shoot it in a different direction if you aim at it from a different angle (for example when you are in 2 or more pieces). Didn't see this behaviour before last few commits.

**Comment by Barbosik** [comment]
Influxx, yes, on experimental virus has a new behavior, now you can fight off flying virus with your shot :) I think it's nice behavior, because player has a chance to defend from flying virus.
I didn't tested experimental virus on vanilla, but as I remember it works in the same way

**Comment by NatsuTheGreat** [comment]
I have noticed that too influxx.

**Comment by Influxx** [comment]
Hmm I see, I tested this on FFA mode however, not experimental, and noticed same behavior. It's pretty cool to have for experimental though :)
