### ISSUE TITLE
Is there a way to whitelist my server?

### ISSUE THREAD

**Issue by koda** [Barbosik/MultiOgar#424]
I have a server it has many people lots of people know the server ip and everytime lots of people join is there a way to whitelist the server where only certain people can join

**Comment by MastaCoder** [comment]
Change it so that the banlist is the allowed list. Add the IP's of the people allowed.

**Comment by koda** [comment]
How do i do that?

**Comment by koda** [comment]
??? can you please tell me how do i do that

**Comment by DaAwesomeRazor** [comment]
its in onClientSocketOpen or whatever its called in gameServer.js

**Comment by koda** [comment]
Is there a way to make the splitting slower because its too fast :\
