### ISSUE TITLE
Session stats

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#425]
Who know, does this server collecting these data?

![image](https://cloud.githubusercontent.com/assets/10178982/21153265/62f3f1e6-c172-11e6-8973-a676d510922a.png)

**Comment by MastaCoder** [comment]
I am 75% sure that is done Client side. (There really shouldn't be a reason for them to do it on the server!)

**Comment by SimonOrJ** [comment]
I am 100% sure that is done by the client software. (25% more than @MastaCoder's assumption!)

**Comment by MastaCoder** [comment]
Damn it 😆
