### ISSUE TITLE
Tracker

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#429]
How do I put my server on http://ogar-tracker.tk/ and how am I sure it is working?

**Comment by MastaCoder** [comment]
It's already set. You can turn it on through the gameserver.ini, under serverTracker

**Comment by GhostShot3** [comment]
Thanks MastaCoder

**Comment by GhostShot3** [comment]
But when I try to access my server via the tracker it does not work, but when I use ip 127.0.0.1 it works for me.

**Comment by MastaCoder** [comment]
It's because your IP is not portforwarded. Try this website https://portforward.com/ with your ISP or Modem to see how you can port forward. It's different for most homes.

**Comment by GhostShot3** [comment]
I need to open ports ?

**Comment by GhostShot3** [comment]
How to use this and i need to open ports ?

**Comment by GhostShot3** [comment]
I opened the ports 88 (server stats), 553 (gameserver)

**Comment by GhostShot3** [comment]
But it still does not work.

**Comment by MastaCoder** [comment]
If it doesn't work the port wasn't opened properly, or your ISP is blocking it. Keep trying 👍

**Comment by GhostShot3** [comment]
I  create my server with ogarmaster.
http://www.skrar.tk/
