### ISSUE TITLE
line split don't work 

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#43]
^^ says all

**Comment by Barbosik** [comment]
Could you explain what "line split" means?

**Comment by David1ali12** [comment]
look here 1:22 https://www.youtube.com/watch?v=hsNH85E020o

**Comment by David1ali12** [comment]
@Barbosik thanks your MutliOgar has  perfect physics. it alot of time I'm looking for this finally found it :) :+1:

**Comment by Chancerst** [comment]
:(
Vanilla Agar.io doesn't have line split.

**Comment by Barbosik** [comment]
actually vanilla has line split, but I'm not sure if it's possible to use it with vanilla client. I was used it on protocol 5 vanilla servers from my client.
I will check it

**Comment by MastaCoder** [comment]
@Barbosik I think the issue is the collisions. For some reason when the cells split and then are on top of each other or touching each other, it will cause them to move not creating a straight line.

**Comment by MastaCoder** [comment]
UPDATE. I'm using the latest version now and line splits work fine :+1: 

https://gyazo.com/e0ffe084ff37d9363251bdf46d1f1f3e

**Comment by NatsuTheGreat** [comment]
That's not line split.

**Comment by MastaCoder** [comment]
@NatsuTheGreat Agar does that?

**Comment by ItzLevvie** [comment]
Vertical Linesplit: https://youtu.be/FwOKY7U-pK8
Horizontal Linesplit: https://youtu.be/dCnYcSblNfk

**Comment by NatsuTheGreat** [comment]
@MastaCoder Yes, but that's not a line split.

**Comment by Barbosik** [comment]
partially fixed, but current rigid body collision resolution is not so good, so line is unstable - you cannot keep it for a long time

**Comment by MastaCoder** [comment]
This is possible with the thing that stops the cell movement when the mouse is in the center. (Well partially.) It used to be in Ogar but got removed.

**Comment by David1ali12** [comment]
@Barbosik is there anyway to use minions on my server without letting others to use it?

**Comment by Barbosik** [comment]
feeding minion is not supported

**Comment by Barbosik** [comment]
**MastaCoder:** line split works, and it should not leads to lags, but the line is unstable due to rigid body collision resolution, it has some small random fluctuations, so some cell shifted randomly up for a small offset and the line turns into a heap of cells. I'm not so friendly with rigid body collision algorithms. Probably there is need to consider cell velocity and penetration normal

**Comment by David1ali12** [comment]
damn can you add minions for it because some ppl like me Cant play without minions :smile:

**Comment by MastaCoder** [comment]
@Barbosik Alright I see, I'll see if there is anything I can do on my side. I'll pr if I find anything.

**Comment by NatsuTheGreat** [comment]
Cell velocity is what original agar.io uses. "onSplitVelocity" "onVirusSplitVelocity" both values are 2000.

**Comment by bean07** [comment]
its not work yet @Barbosik

**Comment by Barbosik** [comment]
**NatsuTheGreat**: there is no need to set cell velocity. Just call setBoost(distance, angle) and the speed will be calculated automatically. The speed will be exactly the same as vanilla

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bqhgpq

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bqhozn
