### ISSUE TITLE
how to put a different ip for gametrackers?!

### ISSUE THREAD

**Issue by systemroot** [Barbosik/MultiOgar#435]
i want to use proxy's for some security reasons. 
my proxy is up, fully configured and working 100% i can connect my server from it, 

so my question, how to put a different "fake" ip for gametrackers? i have found about port by changing https://github.com/Barbosik/MultiOgar/blob/master/src/GameServer.js#L1807
but isn't the same for ip :/ so can i get some help?!

Thank You.

**Comment by MastaCoder** [comment]
You can't do it through the gameserver. You're going to have to find a way on the VPS to send out requests under a different IP. This is because the trackers check the IP is being sent from, the server doesn't "send an IP"

**Comment by systemroot** [comment]
clear enough, thank you!
