### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by deniskrop** [Barbosik/MultiOgar#437]
I am unable to find any documentation or comments for this project to help me get started. Can someone please point me in the right direction, or share their comments for this script if there are no public ones right now? Thanks!

**Comment by SimonOrJ** [comment]
What do you want to do?  The installation is [right here](https://github.com/Barbosik/MultiOgar#install).  That's how you can get started.

If you want to edit the source files, you'll have to disassemble the code yourself.  You may need preliminary knowledge on Node.js before you can do so.

**Comment by deniskrop** [comment]
@SimonOrJ  I want to add additional features, such as skin rotation. I have knowledge of Node.js, but am having trouble with some things due to lack of documentation. If you (or anyone that reads this) can help, I can hire you, email me at dfiverr@gmail.com

**Comment by deniskrop** [comment]
I want to add additional features, such as skin rotation. I have knowledge of Node.js, but am having trouble with some things due to lack of documentation. I was hoping someone could possibly have documentation they made themselves to share.

**Comment by MastaCoder** [comment]
Skin rotation is client sided just to let you know. The server is used to transmit information about the cell, rendering and other such stuff are done on the client itself.

**Comment by deniskrop** [comment]
@MastaCoder  I would like to add skin rotation to all the Players, so everyone can see each others rotation, not just the current Player. Can that be done just on the client?

**Comment by MastaCoder** [comment]
Yep.

**Comment by deniskrop** [comment]
@MastaCoder Thank you, but what would I use for other Players, I know for the current player I can use mouseX and mouseY, but for other players? Current rotation code (works for the current player that is playing the game, but doesn't show rotation of other players):

                        var dx = rawMouseX - (canvasWidth / 2); // get the mouse x position on the screen
                        var dy = rawMouseY - (canvasHeight / 2); // get the mouse Y position on the screen
                        var theta; // the radeon angle that the current player needs to be rated by
                        // the following two if statements are made to accommodate some skins which need need flipping when they are turning
                        if (rawMouseX > canvasWidth / 2) {
                            // mouse is on right side
                            ctx.scale(1, -1); // Flip the canvas context, since it needs to be flipped when its looking right
                            theta = (-Math.atan2(dy, dx) - Math.PI / 2);
                        }
                        if (rawMouseX < canvasWidth / 2) {
                            // mouse in on left side
                            theta = (Math.atan2(dy, dx) - Math.PI / 2);
                        }
                        ctx.rotate(theta);

Any clues would be highly appreciated. Thank you!

**Comment by MastaCoder** [comment]
I don't think I can really tell without knowing the whole script. Skin rotation as well, I have never tried. (yet)

**Comment by deniskrop** [comment]
@MastaCoder Any way I can get in contact with you?

**Comment by deniskrop** [comment]
@MastaCoder  What values would I use to determine the rotation on the client, for other players? I am trying to figure out how to do it on the client only, you said its possible on the client, but with what values? I am using the Cigar.io client, but really it can be done with any client right? Thank you.

**Comment by MastaCoder** [comment]
It should be just have them turn towards the point of mouse. But I don't think their is a way to move it towards something, I'm pretty sure it's rotate? (Judging by http://stackoverflow.com/questions/17411991/html5-canvas-rotate-image)

So you'll have to find ways to get the cell to rotate using some sort of formula towards the mouse positions. (Haven't tried ANY of this, so I can't confirm if I'm even right!)
