### ISSUE TITLE
Can't seem to spawn in when I hit play.

### ISSUE THREAD

**Issue by wassupmyagarios** [Barbosik/MultiOgar#449]
I had noticed some odd things added, such as quests and my position in the leaderboard. However, when I hit play on the menu to my server, I can't spawn in. I can't spectate either. Help please?

**Comment by ItzLevvie** [comment]
Add patch from https://github.com/ItzLevvie/MultiOgar-Edited/commit/77d2633abd919f820f589985ff372fbb874619bd

**Comment by wassupmyagarios** [comment]
@ItzLevvie now whenever I play, I hit escape and it doesn't let me hit play again

**Comment by wassupmyagarios** [comment]
@ItzLevvie now it doesn't work at all .-.

**Comment by cowpits** [comment]
i made a video on that on my youtube channel, make sure to do the patch. and restart your server. Also, after you do the patch make sure you logout of your agar.io account or you won't be able to play on private servers.

**Comment by wassupmyagarios** [comment]
@cowpits what is your YouTube name?

**Comment by ItzLevvie** [comment]
^^ https://www.youtube.com/channel/UCTi738lFHsRmNdEWwWyADhA

**Comment by cowpits** [comment]
@ItzLevvie thanks. or youtube.com/cowpits lol and the video https://www.youtube.com/watch?v=m0nruKe1ILM

**Comment by wassupmyagarios** [comment]
Nevermind, thanks.
