### ISSUE TITLE
Can you make new protocol for my client?

### ISSUE THREAD

**Issue by lulzyyy** [Barbosik/MultiOgar#45]
I'm the owner of http://c0nsume.me Could you make new protocol to communicate with my client? If yes, then I will implement your ogar to my servers. I tried to understand your code in updateNodes.js but it's too difficult for me... you can find my server code at https://github.com/lulzyyy/lulzyOgar and if you need I'll send you some client code

**Comment by Barbosik** [comment]
why it didn't support existing protocol? Protocol 6 is pretty good documented, it's clean, supports compression and optimized for best performance.

**Comment by lulzyyy** [comment]
ok I understand.

**Comment by lulzyyy** [comment]
Could you just tell me how to modify my updateNodes function in client to make it workproperly with protocol 6?

` function updateNodes(view, offset) 
	{
	  if (serverProtocol == 1)
	  {
        timestamp = +new Date;
        var code = Math.random();
        ua = false;
        var queueLength = view.getUint16(offset, true);
        offset += 2;
        for (i = 0; i < queueLength; ++i) {
            var killer = nodes[view.getUint32(offset, true)],
                killedNode = nodes[view.getUint32(offset + 4, true)];
            offset += 8;
            if (killer && killedNode) {
                killedNode.destroy();
                killedNode.ox = killedNode.x;
                killedNode.oy = killedNode.y;
                killedNode.oSize = killedNode.size;
                killedNode.nx = killer.x;
                killedNode.ny = killer.y;
                killedNode.nSize = killedNode.size;
                killedNode.updateTime = timestamp;
            }
        }
        for (var i = 0; ;) {
            var nodeid = view.getUint32(offset, true);
            offset += 4;
            if (0 == nodeid) break;
            ++i;
            var size, posY, posX = view.getInt16(offset, true);
            offset += 2;
            posY = view.getInt16(offset, true);
            offset += 2;
            size = view.getInt16(offset, true);
            offset += 2;
            for (var r = view.getUint8(offset++), g = view.getUint8(offset++), b = view.getUint8(offset++),
                     color = (r << 16 | g << 8 | b).toString(16); 6 > color.length;) color = "0" + color;
            var colorstr = "#" + color,
                flags = view.getUint8(offset++),
                flagVirus = !!(flags & 1),
                flagAgitated = !!(flags & 16);
            flags & 2 && (offset += 4);
            flags & 4 && (offset += 8);
            flags & 8 && (offset += 16);
            for (var char, name = ""; ;) {
                char = view.getUint16(offset, true);
                offset += 2;
                if (0 == char) break;
                name += String.fromCharCode(char);
            }
			
			for (var t, skinText = ""; ;) { ////////////////////////////////////////////
                t = view.getUint16(offset, true);
                offset += 2;
                if (0 == t) break;
                skinText += String.fromCharCode(t);
            }
			
            var node = null;
            if (nodes.hasOwnProperty(nodeid)) {
                node = nodes[nodeid];
                node.updatePos();
                node.ox = node.x;
                node.oy = node.y;
                node.oSize = node.size;
                node.color = colorstr;
            } else {
                node = new Cell(nodeid, posX, posY, size, colorstr, name, skinText);
                nodelist.push(node);
                nodes[nodeid] = node;
                node.ka = posX;
                node.la = posY;
            }
            node.isVirus = flagVirus;
            node.isAgitated = flagAgitated;
            node.nx = posX;
            node.ny = posY;
            node.nSize = size;
            node.updateCode = code;
            node.updateTime = timestamp;
            node.flag = flags;
            name && node.setName(name);
            if (-1 != nodesOnScreen.indexOf(nodeid) && -1 == playerCells.indexOf(node)) {
				if (!isSpectating)
					document.getElementById("overlays").style.display = "none";
                playerCells.push(node);
                if (1 == playerCells.length) {
                    nodeX = node.x;
                    nodeY = node.y;
                }
            }
        }
        queueLength = view.getUint32(offset, true);
        offset += 4;
        for (i = 0; i < queueLength; i++) {
            var nodeId = view.getUint32(offset, true);
            offset += 4;
            node = nodes[nodeId];
            null != node && node.destroy();
        }
        !isSpectating && ua && 0 == playerCells.length && showOverlays(false)
	  }`

**Comment by lulzyyy** [comment]
Could you just tell me how to modify my updateNodes function in client to make it workproperly with protocol 6? 

`function updateNodes(view, offset) 
	{
	  if (serverProtocol == 1)
	  {
        timestamp = +new Date;
        var code = Math.random();
        ua = false;
        var queueLength = view.getUint16(offset, true);
        offset += 2;
        for (i = 0; i < queueLength; ++i) {
            var killer = nodes[view.getUint32(offset, true)],
                killedNode = nodes[view.getUint32(offset + 4, true)];
            offset += 8;
            if (killer && killedNode) {
                killedNode.destroy();
                killedNode.ox = killedNode.x;
                killedNode.oy = killedNode.y;
                killedNode.oSize = killedNode.size;
                killedNode.nx = killer.x;
                killedNode.ny = killer.y;
                killedNode.nSize = killedNode.size;
                killedNode.updateTime = timestamp;
            }
        }
        for (var i = 0; ;) {
            var nodeid = view.getUint32(offset, true);
            offset += 4;
            if (0 == nodeid) break;
            ++i;
            var size, posY, posX = view.getInt16(offset, true);
            offset += 2;
            posY = view.getInt16(offset, true);
            offset += 2;
            size = view.getInt16(offset, true);
            offset += 2;
            for (var r = view.getUint8(offset++), g = view.getUint8(offset++), b = view.getUint8(offset++),
                     color = (r << 16 | g << 8 | b).toString(16); 6 > color.length;) color = "0" + color;
            var colorstr = "#" + color,
                flags = view.getUint8(offset++),
                flagVirus = !!(flags & 1),
                flagAgitated = !!(flags & 16);
            flags & 2 && (offset += 4);
            flags & 4 && (offset += 8);
            flags & 8 && (offset += 16);
            for (var char, name = ""; ;) {
                char = view.getUint16(offset, true);
                offset += 2;
                if (0 == char) break;
                name += String.fromCharCode(char);
            }
			
			for (var t, skinText = ""; ;) { ////////////////////////////////////////////
                t = view.getUint16(offset, true);
                offset += 2;
                if (0 == t) break;
                skinText += String.fromCharCode(t);
            }
			
            var node = null;
            if (nodes.hasOwnProperty(nodeid)) {
                node = nodes[nodeid];
                node.updatePos();
                node.ox = node.x;
                node.oy = node.y;
                node.oSize = node.size;
                node.color = colorstr;
            } else {
                node = new Cell(nodeid, posX, posY, size, colorstr, name, skinText);
                nodelist.push(node);
                nodes[nodeid] = node;
                node.ka = posX;
                node.la = posY;
            }
            node.isVirus = flagVirus;
            node.isAgitated = flagAgitated;
            node.nx = posX;
            node.ny = posY;
            node.nSize = size;
            node.updateCode = code;
            node.updateTime = timestamp;
            node.flag = flags;
            name && node.setName(name);
            if (-1 != nodesOnScreen.indexOf(nodeid) && -1 == playerCells.indexOf(node)) {
				if (!isSpectating)
					document.getElementById("overlays").style.display = "none";
                playerCells.push(node);
                if (1 == playerCells.length) {
                    nodeX = node.x;
                    nodeY = node.y;
                }
            }
        }
        queueLength = view.getUint32(offset, true);
        offset += 4;
        for (i = 0; i < queueLength; i++) {
            var nodeId = view.getUint32(offset, true);
            offset += 4;
            node = nodes[nodeId];
            null != node && node.destroy();
        }
        !isSpectating && ua && 0 == playerCells.length && showOverlays(false)
	  }
}`

**Comment by lulzyyy** [comment]
What should I change in my updateNodes function in client to make it work properly with protocol 6?

`function updateNodes(view, offset) 
	{
        timestamp = +new Date;
        var code = Math.random();
        ua = false;
        var queueLength = view.getUint16(offset, true);
        offset += 2;
        for (i = 0; i < queueLength; ++i) {
            var killer = nodes[view.getUint32(offset, true)],
                killedNode = nodes[view.getUint32(offset + 4, true)];
            offset += 8;
            if (killer && killedNode) {
                killedNode.destroy();
                killedNode.ox = killedNode.x;
                killedNode.oy = killedNode.y;
                killedNode.oSize = killedNode.size;
                killedNode.nx = killer.x;
                killedNode.ny = killer.y;
                killedNode.nSize = killedNode.size;
                killedNode.updateTime = timestamp;
            }
        }
        for (var i = 0; ;) {
            var nodeid = view.getUint32(offset, true);
            offset += 4;
            if (0 == nodeid) break;
            ++i;
            var size, posY, posX = view.getInt16(offset, true);
            offset += 2;
            posY = view.getInt16(offset, true);
            offset += 2;
            size = view.getInt16(offset, true);
            offset += 2;
            for (var r = view.getUint8(offset++), g = view.getUint8(offset++), b = view.getUint8(offset++),
                     color = (r << 16 | g << 8 | b).toString(16); 6 > color.length;) color = "0" + color;
            var colorstr = "#" + color,
                flags = view.getUint8(offset++),
                flagVirus = !!(flags & 1),
                flagAgitated = !!(flags & 16);
            flags & 2 && (offset += 4);
            flags & 4 && (offset += 8);
            flags & 8 && (offset += 16);
            for (var char, name = ""; ;) {
                char = view.getUint16(offset, true);
                offset += 2;
                if (0 == char) break;
                name += String.fromCharCode(char);
            }
			
			for (var t, skinText = ""; ;) {
                t = view.getUint16(offset, true);
                offset += 2;
                if (0 == t) break;
                skinText += String.fromCharCode(t);
            }
			
            var node = null;
            if (nodes.hasOwnProperty(nodeid)) {
                node = nodes[nodeid];
                node.updatePos();
                node.ox = node.x;
                node.oy = node.y;
                node.oSize = node.size;
                node.color = colorstr;
            } else {
                node = new Cell(nodeid, posX, posY, size, colorstr, name, skinText);
                nodelist.push(node);
                nodes[nodeid] = node;
                node.ka = posX;
                node.la = posY;
            }
            node.isVirus = flagVirus;
            node.isAgitated = flagAgitated;
            node.nx = posX;
            node.ny = posY;
            node.nSize = size;
            node.updateCode = code;
            node.updateTime = timestamp;
            node.flag = flags;
            name && node.setName(name);
            if (-1 != nodesOnScreen.indexOf(nodeid) && -1 == playerCells.indexOf(node)) {
				if (!isSpectating)
					document.getElementById("overlays").style.display = "none";
                playerCells.push(node);
                if (1 == playerCells.length) {
                    nodeX = node.x;
                    nodeY = node.y;
                }
            }
        }
        queueLength = view.getUint32(offset, true);
        offset += 4;
        for (i = 0; i < queueLength; i++) {
            var nodeId = view.getUint32(offset, true);
            offset += 4;
            node = nodes[nodeId];
            null != node && node.destroy();
        }
        !isSpectating && ua && 0 == playerCells.length && showOverlays(false)
	}`

**Comment by Barbosik** [comment]
no offense. By using your own protocol you're inventing the wheel and step on a rake. Just use existing things and all will be much easier

**Comment by lulzyyy** [comment]
Could you tell me how to change my updateNodes function of the client to make it work properly with protocol 6? Please :(

http://pastie.org/private/1xzss1yfbwn3jcnwtiht9w

**Comment by Barbosik** [comment]
I recommend to rewrite it with using BinaryReader: https://github.com/Barbosik/MultiOgar/blob/master/src/packet/BinaryReader.js

It works faster and allows to write clean code without these offset, view, and other redundant things.

With using BinaryReader, you can use this code:
```
function updateNodes(message) 
{
    var reader = new BinaryReader(message);
    reader.skipBytes(1); // skip message id (it's 16)

    var eatCount = reader.readUInt16();
    for (var i = 0; i < eatCount; i++) {
        var killer = reader.readUInt32();
        var killedNode = reader.readUInt32();

        // === [insert your code here to process cell eat] ===

    }
    while (true) {
        var nodeid = reader.readUInt32();
        if (nodeid == 0) 
            break;
        var posX = reader.readInt32();
        var posY = reader.readInt32();
        var size = reader.readUInt16();
        var flags = reader.readUInt8();

        var flagVirus = (flags & 0x01) != 0;
        var flagAgitated = (flags & 0x10) != 0;
        var flagEjected = (flags & 0x20) != 0;

        var color = null;
        if (flags & 0x02)
        {
            var r = reader.readUInt8();
            var g = reader.readUInt8();
            var b = reader.readUInt8();
            color = r << 16 | g << 8 | b;
        }
        var skinText = null;
        if (flags & 0x08)
        {
            var skinText = reader.readStringZeroUtf8();
        }
        var name = null;
        if (flags & 0x08) {
            var name = reader.readStringZeroUtf8();
        }

        // === [insert your code here to process cell update] ===

    }
    var delCount = reader.readUInt16();
    for (var i = 0; i < delCount; i++) {
        var nodeId = reader.readUInt32();

        // === [insert your code here to process cell remove] ===

    }
}
```

But note that argument is NOT **view** and **offset**, but message. Just pass full message that is received from websocket.

**Comment by lulzyyy** [comment]
Thanks for advice but after some experiments It's working with protocol 4 after some modification

`UpdateNodes.prototype.writeUpdateItems4 = function (writer) {
    var scrambleX = this.playerTracker.scrambleX;
    var scrambleY = this.playerTracker.scrambleY;
    var scrambleId = this.playerTracker.scrambleId;

    for (var i = 0; i < this.updateNodes.length; i++) {
        var node = this.updateNodes[i];
        if (node.nodeId == 0)
            continue;
        
        var cellX = node.position.x + scrambleX;
        var cellY = node.position.y + scrambleY;
        var cellName = node.getName();
		var skinName = node.getSkin();
        
        // Write update record
        writer.writeUInt32((node.nodeId ^ scrambleId) >>> 0);         // Cell ID
        writer.writeInt16(cellX >> 0);                // Coordinate X
        writer.writeInt16(cellY >> 0);                // Coordinate Y
        writer.writeUInt16(node.getSize() >>> 0);     // Cell Size (not to be confused with mass, because mass = size*size/100)
        writer.writeUInt8(node.color.r >>> 0);         // Color R
        writer.writeUInt8(node.color.g >>> 0);         // Color G
        writer.writeUInt8(node.color.b >>> 0);         // Color B
        
        var flags = 0;
        if (node.spiked & 1)
            flags |= 0x01;      // isVirus
        if (false)
            flags |= 0x10;      // isAgitated
        if (node.cellType == 3)
            flags |= 0x20;      // isEjected
        writer.writeUInt8(flags >>> 0);                  // Flags
        
        writer.writeStringZeroUnicode(cellName);
		writer.writeStringZeroUnicode(skinName);        // Name
    }
    writer.writeUInt32(0);                              // Cell Update record terminator
};`

Thanks!

**Comment by Barbosik** [comment]
it's incorrect, use protocol 5 if you want to get skin name

**Comment by lulzyyy** [comment]
I implemented your ogar, check out test server on http://c0nsume.me/ I modified code a bit but almost everything is the same

**Comment by Barbosik** [comment]
it doesn't work, it seems that your client doesn't support private servers

**Comment by lulzyyy** [comment]
yea but I modified your server code and my client works only with my modified version.

**Comment by lulzyyy** [comment]
but thanks for advice' I'll do it

**Comment by Barbosik** [comment]
yes, because you're doing it wrong, with such change the server will not be able to works with normal clients (with good protocol implementation).
If something is going wrong with client, you cannot fix it with modification on server. Because it will break other clients.

**Comment by Influxx** [comment]
Hi Barbosik, thanks for the amazing work you've done!

Could you show us how to implement protocol 6 with the following client ?
https://github.com/ItzLevvie/agario-client

It's the most readable client code so far, and would be nice to have protocol 6 working on it!

**Comment by lulzyyy** [comment]
My client is using protocol 5 now, but it still doesn't work ;/

http://pastie.org/private/89l2wafqbmns2bq2yhtu9a

**Comment by Barbosik** [comment]
it seems that your client doesn't support /?ip=xxx
So, I cannot connect to check what is wrong

**Comment by lulzyyy** [comment]
http://c0nsume.me/private4.php?ip=vps.simonorj.com:24270

**Comment by Barbosik** [comment]
it's obfuscated, so it's hard to read the code, so I don't see what is going on. But according to the error message, you implemented it with mistake.

**Comment by lulzyyy** [comment]
`var size, posY, posX = view.getInt32(offset, true);
            offset += 2;
            posY = view.getInt32(offset, true);
            offset += 2;
            size = view.getUint16(offset, true);
			
            offset += 2;
            for (var r = view.getUint8(offset++), g = view.getUint8(offset++), b = view.getUint8(offset++),
                     color = (r << 16 | g << 8 | b).toString(16); 6 > color.length;) color = "0" + color;
            var colorstr = "#" + color,
                flags = view.getUint8(offset++),
                flagVirus = !!(flags & 1),
                flagAgitated = !!(flags & 16);
				
				flags & 2 && (offset += 4);

            var skinText = "";
            if (flags & 4) {
               for (; ;) { // skin name
                   t = view.getUint8(offset, true) & 0x7F;
                   offset += 1;
                   if (0 == t) break;
                   skinText += String.fromCharCode(t);
               }
            }
            for (var char, name = ""; ;) { // nick name
                char = view.getUint16(offset, true);
                offset += 2;
                if (0 == char) break;
                name += String.fromCharCode(char);
            }`

**Comment by lulzyyy** [comment]
**var size, posY, posX = view.getInt32(offset, true);
            offset += 2;
            posY = view.getInt32(offset, true);
            offset += 2;
            size = view.getUint16(offset, true);
			
            offset += 2;
            for (var r = view.getUint8(offset++), g = view.getUint8(offset++), b = view.getUint8(offset++),
                     color = (r << 16 | g << 8 | b).toString(16); 6 > color.length;) color = "0" + color;
            var colorstr = "#" + color,
                flags = view.getUint8(offset++),
                flagVirus = !!(flags & 1),
                flagAgitated = !!(flags & 16);
				
				flags & 2 && (offset += 4);

            var skinText = "";
            if (flags & 4) {
               for (; ;) { // skin name
                   t = view.getUint8(offset, true) & 0x7F;
                   offset += 1;
                   if (0 == t) break;
                   skinText += String.fromCharCode(t);
               }
            }
            for (var char, name = ""; ;) { // nick name
                char = view.getUint16(offset, true);
                offset += 2;
                if (0 == char) break;
                name += String.fromCharCode(char);
            }**

This is part of updateNodes function.

**function onWsOpen() {
        var msg;
        delay = 500;
        wjQuery("#connecting").hide();
        console.log("socket open");
        msg = prepareData(5);
        msg.setUint8(0, 254);
        msg.setUint32(1, 5, true); // PROTOCOL 5
        wsSend(msg);
        msg = prepareData(5);
        msg.setUint8(0, 255);
        msg.setUint32(1, 1332175218, true);
        wsSend(msg);
        sendNickName();
		$('#conmsg').html("<b>CONNECTED!</b>");
    }**

**Comment by lulzyyy** [comment]
Why the F*** I can't paste this code properly wtf github... sorry

**Comment by lulzyyy** [comment]
Ok code is normal, deobfuscated

**Comment by Barbosik** [comment]
here is mistake:
```
            var size, posY, posX = view.getInt32(offset, true);
            offset += 2;
            posY = view.getInt32(offset, true);
            offset += 2;
            size = view.getUint16(offset, true);
            offset += 2;
```

should be:
```
            var size, posY, posX = view.getInt32(offset, true);
            offset += 4;
            posY = view.getInt32(offset, true);
            offset += 4;
            size = view.getUint16(offset, true);
            offset += 2;
```

**Comment by lulzyyy** [comment]
http://c0nsume.me/private4.php?ip=vps.simonorj.com:24270 there's still something wrong...

**Comment by ItzLevvie** [comment]
Could be because of the mouse packet?

Update it like this: https://github.com/ItzLevvie/agario-client/commit/91607322fce301b1cb9aec093322b5aec3d392d0#diff-35baaccf96d971ceef1f4bdf71bb2d7aR510

**Comment by lulzyyy** [comment]
noooo everything is ok my bad

**Comment by lulzyyy** [comment]
where is leaderboard?

**Comment by lulzyyy** [comment]
ok everything is working fine. Skins also work. I added SimonJ Server to private server list on http://c0nsume.me

You can add my client to your readme. To connect to your server use
http://c0nsume.me/private4.php?ip=IP:PORT

**Comment by lulzyyy** [comment]
I started 24/7 server with Multi Ogar without any modification (only vanilla sized map) and I will update server files everyday. 
http://c0nsume.me/private4.php?ip=164.132.48.230:600

**Comment by Barbosik** [comment]
ok. You can enable tracker, just set serverTracker = 1 in gameserver.ini and your servers will be listed here: http://ogar.mivabe.nl/master

**Comment by lulzyyy** [comment]
ok. btw. If i set map size to vanilla, how many viruses and food should I put there? Because I think there's too much food and viruses

**Comment by lulzyyy** [comment]
now it's like this 

foodSpawnAmount = 50
foodStartAmount = 500
foodMaxAmount = 2500
foodMass = 1
foodMassGrow = 1
foodMassGrowPossiblity = 50
foodMassLimit = 4
virusMinAmount = 50
virusMaxAmount = 150

**Comment by Barbosik** [comment]
I think it should be good for vanilla size (14100x14100). But there is need to test it

**Comment by lulzyyy** [comment]
and one more question. what node.js version do you use? Because I use 4.4.5

**Comment by Barbosik** [comment]
I even don't know :) Just installed first that I found :)
Just checked: 0.12.7

**Comment by lulzyyy** [comment]
LOL;D get version 4.4.5

**Comment by Influxx** [comment]
I am running 5.9.0 and can confirm it's working just fine. I will test latest node version and report my findings here.

PS: a useful tool for managing node versions is nvm (node version manager): https://github.com/creationix/nvm

**Comment by Influxx** [comment]
Works perfect with latest version of node (6.2.2).

**Comment by ItzLevvie** [comment]
I use 7.0.0 on top of a custom built JXCore with a faster ws module

**Comment by Influxx** [comment]
Which ws module would that be, ItzLevvie?

There is no 7.0 version btw, 6.2.2 is latest.

**Comment by ItzLevvie** [comment]
https://nodejs.org/download/nightly/v7.0.0-nightly201606205bddc9a741/

**Comment by Influxx** [comment]
It's alpha, not good for production, but thanks for the link :)

**Comment by ItzLevvie** [comment]
I know :P

**Comment by Dramex** [comment]
@Barbosik when i edit my client as you said, its got this problem :
RangeError: Offset is outside the bounds of the DataView

**Comment by Barbosik** [comment]
It mens that you implemented protocol incorrectly. Server protocol implementation tested very deep on my client which support any protocol.

**Comment by Dramex** [comment]
and what is better way to upgrade my client without problems and support MultiOgar skins
my client handle the skins clientside, but they must put their skin name in their name, and players want the name different from skin name. 
and in the latest version of MultiOgar, i get this problem 
RangeError: Offset is outside the bounds of the DataView
after 30min server uptime, i think some players name cause this problem, and i dont know what to do

**Comment by Barbosik** [comment]
@Dramex: 
_>>i think some players name cause this problem_

I think it's may be because some players set skin with non-ascii letters. Your client should process it correctly. But it's really improper use of skin name. I will block such skin names in future versions.
