### ISSUE TITLE
Problem minimap

### ISSUE THREAD

**Issue by malekksa505** [Barbosik/MultiOgar#476]
hello

I have a problem with my server MultiOgar, which is a small map but when I play I do not specify my location across the map but it does not fit with the Map

example

https://img4.file-upload.com/i/00171/j128dfvcd1sk.png

**Comment by malekksa505** [comment]
@Barbosik @Luka967 @MastaCoder

**Comment by malekksa505** [comment]
up <<<

**Comment by malekksa505** [comment]
Uppp

**Comment by MastaCoder** [comment]
Upp!! Bump bump!!

**Comment by malekksa505** [comment]
help me @MastaCoder
What do I do about this problem

**Comment by MastaCoder** [comment]
doesn't relate to the project.
no idea what that minimap is.
dead project.
