### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by GhostShot3** [Barbosik/MultiOgar#485]
![sdasdsdasd](https://user-images.githubusercontent.com/18537420/27521472-bffafb04-59f3-11e7-8d42-fa407552e7e3.png)

**Comment by plazo123** [comment]
@GhostShot3 
send game server.js and websocketserver.js and have you modified 
seee version of node

**Comment by plazo123** [comment]
you might wanna check out https://github.com/Megabyte918/MultiOgar-Edited
a better version of ogar 
Barbosik stoped this project since 2016

**Comment by Sicmda** [comment]
package.json

{
         ~~
         ~~        **↓ change to 1.1.0**
        "ws": "**latest**",
         ~~
         ~~
}
