### ISSUE TITLE
Lag.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#5]
Alright I have something. So the packet change should not affect the quality, but if we add 30+ bots now, the games moves slow. I think this is caused by the re write of playertracker by luka. "Massive performance update" I tried ogar after that pull request was merged and it went slow, didn't before. So lets try to reverse that.

**Comment by Barbosik** [comment]
I tested it with 500 cells on the view area and it works ok with no lag. But I didn't tested bots.
Don't confuse server lag and client lag. New client has lags with such amount of cells on the screen. But this is not server lags.

Also note that each bot also consumes cpu. So if you want to eliminate lags, use lightweight and fast bots implementation. I don't working on the bot code. So if you want you can reuse bot code from another ogar clones.

**Comment by NatsuTheGreat** [comment]
Any leightweight SMART bots?

**Comment by Barbosik** [comment]
It was caused by node.js timer issues. I fixed it.
