### ISSUE TITLE
skin protocol is error?

### ISSUE THREAD

**Issue by xinyuweb** [Barbosik/MultiOgar#51]
http://play.ogarul.tk/ is ok! but MultiOgar not work! skin is 'undefined'
![111](https://cloud.githubusercontent.com/assets/5715519/16177512/811980d2-3662-11e6-9125-15a923567a9c.PNG)

**Comment by David1ali12** [comment]
same here it does not support the skins  for some reason.

**Comment by ItzLevvie** [comment]
^^ Are you using custom skins?

**Comment by David1ali12** [comment]
both dont work normal and custom, :d

**Comment by Barbosik** [comment]
ogarul uses protocol 4, as I know there is no way to use skin for protocol 4. Some protocol 4 clients may use hand made extensions, but it's undocumented and will works only with specific server. Protocol 4 also doesn't support large maps. I have no idea why protocol 4 still used in some clients. It's not so hard to change it to protocol 5 - just a small change for 2-3 lines of code.

**Comment by David1ali12** [comment]
how can I update my client protocol to version 5?

**Comment by xinyuweb** [comment]
where can i find the protocol 5 client?

**Comment by Barbosik** [comment]
David1ali12: how to fix, see here: https://github.com/Barbosik/MultiOgar/issues/45

xinyuweb: for example http://ogar.mivabe.nl/?ip=127.0.0.1:443

**Comment by Influxx** [comment]
Hi Barbosik, thanks for the amazing work you've done!

Could you show us how to implement protocol 6 with the following client ?
https://github.com/ItzLevvie/agario-client

It's the most readable client code so far, and would be nice to have protocol 6 working on it!

**Comment by Megabyte918** [comment]
@LegitSoulja, read through this, this may have been why your server was acting up when you tried to increase the map size
