### ISSUE TITLE
What could I have done wrong?

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#52]
>TypeError: GameServer.removeNode: attempt to remove invalid node!
    at GameServer.removeNode (C:\Users\\Downloads\MultiOgar-master\src\GameServer.js:452:15)
    at Mode.FFA.onPlayerSpawn (C:\Users\\Downloads\MultiOgar-master\src\gamemodes\FFA.js:55:16)
    at PacketHandler.setNickname (C:\Users\\Downloads\\MultiOgar-master\src\PacketHandler.js:224:34)
    at PacketHandler.handleMessage (C:\Users\\Downloads\MultiOgar-master\src\PacketHandler.js:71:18)
    at GameServer.onClientSocketMessage (C:\Users\\Downloads\\MultiOgar-master\src\GameServer.js:271:22)
    at WebSocket.onMessage (C:\Users\\Downloads\\MultiOgar-master\src\GameServer.js:236:20)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.onbinary (C:\Usersnode_modules\ws\lib\WebSocket.js:823:10)
    at C:\Users\node_modules\ws\lib\Receiver.js:537:18

**Comment by Barbosik** [comment]
what is steps to reproduce?

**Comment by NatsuTheGreat** [comment]
As I see, spawning. From ejected mass?

**Comment by NatsuTheGreat** [comment]
It's some problem with removing ejected mass. :/

**Comment by Barbosik** [comment]
yes, it means that removeNode called for node which is aready removed or just not added with call to addNode. I think it's because it's already removed.

Did you catch it on master branch or on your mod?

**Comment by NatsuTheGreat** [comment]
I think it's because of addNode. I updated my mod to latest multiogar yesterday.

**Comment by Barbosik** [comment]
you can just check node.isRemoved before call to removeNode. If it's true it means that it's already removed, so you should not call removeNode.
And note that you should not call removeNode at all, it should be called from GameServer only

**Comment by NatsuTheGreat** [comment]
Yep the culprit was addNode. node.owner was missing. Probably a mishap from me updating yesterday.

**Comment by NatsuTheGreat** [comment]
And sorry to bother you, but where is the code for the cells freezing when the cursor is in the middle?

**Comment by Barbosik** [comment]
there is no specific code, just all moving logic together works in such way

**Comment by NatsuTheGreat** [comment]
Oh, okay. What is the variable that gets the center of your screen? Is it centerPos?

**Comment by Barbosik** [comment]
If your mod has custom collision check code, just remove all these checks. The cell should just implement simple and fast function canEat(cell) that's it. All eat logic will be performed from GameServer

**Comment by NatsuTheGreat** [comment]
I'm just trying to implement a freezing system, like agar.io had before.

**Comment by Barbosik** [comment]
what "freezing system"? I don't remember it

**Comment by NatsuTheGreat** [comment]
https://gyazo.com/3af6c45bcf1a693b91c78347106b1702

Basically something like that, but cells only freeze when the cursor is in the middle.

**Comment by Barbosik** [comment]
it's not system, it's just movement physics behavior

**Comment by NatsuTheGreat** [comment]
Yeah, I used the wrong words.
