### ISSUE TITLE
Disconnected player bug.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#53]
Problems with disconnected playercell: Collision is ignored, eating range is smaller, doesn't eat ejected mass cells or viruses at all.

**Comment by NatsuTheGreat** [comment]
Also players get kick over time...

**Comment by David1ali12** [comment]
same problem with me some times I get kicked please fix

**Comment by NatsuTheGreat** [comment]
The problem is Connection time out in playertracker.js.

**Comment by ItzLevvie** [comment]
Did you try setting serverTimeout to 0?

**Comment by NatsuTheGreat** [comment]
0 Probably wouldn't do the job.

```
if (!this.isCloseRequested && this.gameServer.config.serverTimeout) {
        var dt = (time - this.socket.lastAliveTime) / 1000;
        if (dt >= this.gameServer.config.serverTimeout) {
            this.socket.close(1000, "Connection timeout");
            this.isCloseRequested = true;
        }
    }
```

I think it should be -1?

**Comment by ItzLevvie** [comment]
i never had any problems with setting it to 0, no disconnections on my protocol 7, 6, 5 or 4 clients

**Comment by NatsuTheGreat** [comment]
Oh alright, my mistake.

**Comment by NatsuTheGreat** [comment]
@Barbosik Can you help with the player disconnection problem?

**Comment by Barbosik** [comment]
if you have disconnections, it seems that you have high lags, at least 30 seconds. Server automatically kick the players with so high lags.
You can disable automatic kick for players with high lag by setting serverTimeout = 0

**Comment by NatsuTheGreat** [comment]
I fixed the timeout thing, I am worrying about a disconnected player cell bug. Like the play disconnects, his cells are there, but the cells don't collide, they can't eat ejected mass nor can they eat viruses. Fix it please?

**Comment by Barbosik** [comment]
Ok, I will check it.

Could you please describe your disconnections more details?
How do you get it? What client do you using?

**Comment by NatsuTheGreat** [comment]
It's not a disconnection problem, it's this: I close my tab, reopen it. Then I find the disconnected cells and I like to popsplit them, virus them, eat them, feed them, etc. But I can't do that now because the disconnected cell doesn't eat ejected mass or viruses. It's eating radius seems to be half of what is was. I am using agar.io/?ip=ip:port.

**Comment by Barbosik** [comment]
Hm, it's not eating radius. It's because quad tree was not updated after remerge.
Could you please check it on the latest version. I just commited some fix which should resolve the same bug for virus. So, your issue also may be fixed.

**Comment by NatsuTheGreat** [comment]
It fixed the eating range, but ejected mass and viruses still fly through the cell.

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bipzl8

**Comment by NatsuTheGreat** [comment]
Same with ejected mass.

**Comment by Barbosik** [comment]
it's for disconnected player?

**Comment by NatsuTheGreat** [comment]
Yes, that astronaut is the disconnected player. :)

**Comment by Barbosik** [comment]
are you sure that you're tested the latest version with no mods?

**Comment by NatsuTheGreat** [comment]
The latest version doesn't have those bugs but the cell can move/merge like without disconnection. I don't use mods btw, it's just a modified version.

**Comment by Barbosik** [comment]
I just tested it, works ok for disconnected player. So, if it's reproduced just with your mod, then something is wrong in your changes

**Comment by NatsuTheGreat** [comment]
The cell can move and everything though. :/

**Comment by Barbosik** [comment]
it's after your modifications? Can you reproduce it on the latest version without modifications?

**Comment by NatsuTheGreat** [comment]
That is on your latest version. The cell can eat properly, but it can move and merge.

**Comment by Barbosik** [comment]
Sorry, but I don't understand. "but it can move and merge" - it's normal game behavior, so what is wrong?

**Comment by NatsuTheGreat** [comment]
The movement should be happening when the play is disconnected

**Comment by Barbosik** [comment]
no, when player is disconnected, the server just set it's mouse to the center. All movement for disconnected player will be the same as for connected player, but with take into account that the mouse position at the center. That's it.

**Comment by NatsuTheGreat** [comment]
If you shoot a virus at a disconnected player in agar.io, the cells will explode but then they freeze after wards,

**Comment by Barbosik** [comment]
ok, fixed
