### ISSUE TITLE
fix this It can pass maxmass ! 

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#55]
http://imgur.com/fCO8b5T
my cell mass passed maxmass idk why

**Comment by David1ali12** [comment]
Also note that how virus spawn in real agar https://www.youtube.com/watch?v=DzmeUeO4w-M 1:29 
that would be nice to add

**Comment by Barbosik** [comment]
steps to reproduce?

**Comment by David1ali12** [comment]
in real agar when u have 16 cells it would let it to pass 22500 mass

**Comment by Barbosik** [comment]
If you have issue, just write how to reproduce it and what is expected, what is actual and why it's wrong.

**Comment by David1ali12** [comment]
don't let it pass 22500 when u have 16 cells .

**Comment by Barbosik** [comment]
okay

**Comment by Barbosik** [comment]
fixed

**Comment by David1ali12** [comment]
it also fixed merge well done

**Comment by Megabyte918** [comment]
isn't the opposite?
