### ISSUE TITLE
Is there any way to not lag when multiboxing?

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#61]
I like multiboxing but after a couple of minutes it says the server is still running perfectly smooth. But... I am lagging none-stop.

**Comment by Barbosik** [comment]
What is cpu load for server process? (node)

It may be related to client performance. If you're using a lot of food, vanilla client may start to lag

**Comment by NatsuTheGreat** [comment]
> What is cpu load for server process? (node)

I don't know what you mean there exactly, can you clarify?
I am using FFA.
```
spawnInterval = 1
foodSpawnAmount = 10
foodStartAmount = 2000
foodMaxAmount = 3000
```
^^
My food values. 

Map:
```
borderWidth = 14142.135623730952
borderHeight = 14142.135623730952
```

**Comment by Barbosik** [comment]
If you're using windows, just open task manager and look for CPU column for process "node". It shows how much cpu consumed by process.

**Comment by NatsuTheGreat** [comment]
Let me check it out :)

At first I was using JxCore, I couldn't find the node core.

Now I have tested with node. JxCore made my overall CPU crazy with 80+ (went above 90...)
With node, my overall CPU is 80 and below. Client seems to be using 477 MB or memory. The cpu for node stays around 20 (not usual)

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bix5qc

**Comment by Barbosik** [comment]
it's not related to the server. Chrome just eats half of your cpu. It's client lag. You're need to reduce food amount/bots, because your client is not able to handle such amount of circles :)
You can disable skins and names in the client. It will helps significantly.

**Comment by NatsuTheGreat** [comment]
I didn't have any bots. It was just two of my tabs. (Both my private server). I really like the skins though, I don't wanna disable them.

**Comment by NatsuTheGreat** [comment]
Google chrome wants to update too, :P

**Comment by Barbosik** [comment]
what client you're using? vanilla works pretty good if you will not use a lot of food.

**Comment by NatsuTheGreat** [comment]
I am using vanilla. agar.io/?ip=port

**Comment by NatsuTheGreat** [comment]
Should I modify mainLoop? I don't think I like the timers.

**Comment by NatsuTheGreat** [comment]
I've replaced the timeout with **setImmediate**

**Comment by Barbosik** [comment]
You can find commented process.nextTick near some setTimeout.
You can replace these setTimeout with process.nextTick or setImmediate (it's the same but more new).
It will works a little more smooth. 
But do not replace other setTimeout (without commented porcess.nextTick), because it may leads to much worse performance and high cpu load.

The problem with process.nextTick is that it doesn't supported on new node.js versions, but setImmediate is not available on old node.js version. So I used setTimeout instead of process.nextTick.

**Comment by NatsuTheGreat** [comment]
I am using node 6.2.1

**Comment by NatsuTheGreat** [comment]
setTimeout is supported.

**Comment by Barbosik** [comment]
In any case these replacing setTimeout with process.nextTick or setImmediate cannot improve performance. It's just helps to maintain a more accurate time intervals. setTimeout works not so bad.

First setTimeout is used to avoid high cpu load and lags:
```
    var ts = new Date().getTime();
    var dt = ts - this.timeStamp;
    if (dt < timeStep - 5) {
        setTimeout(this.timerLoopBind, ((timeStep-5) - dt) >> 0);
        return;
    }
    if (dt < timeStep - 1) {
        setTimeout(this.timerLoopBind, 0);
        return;
    }
```

if you replace it, it will leads to high cpu load, it's bad for garbage collector. So it will leads to worse performance

**Comment by Barbosik** [comment]
setTimeout is supported on all versions, this is the reason why I used it insted of process.nextTick / setImmediate.

**Comment by NatsuTheGreat** [comment]
Vanilla's map values are actually 11180 x 11180

**Comment by Barbosik** [comment]
no, it's about 14000

**Comment by NatsuTheGreat** [comment]
Their config says 11180

**Comment by NatsuTheGreat** [comment]
http://prntscr.com/bixs54

**Comment by NatsuTheGreat** [comment]
Any way of getting the food to grow without lag? It grows the food without a timeout.

**Comment by NatsuTheGreat** [comment]
I am thinking decrements? Or increments?

**Comment by Barbosik** [comment]
I think it's random. For example their server sends the following border info:
```
[TRACE] Border: 14072.9264491945; 14196.5278575354
```

But the real map size is 14151;  10060. it's random sometimes 14000, sometimes 13000...

**Comment by NatsuTheGreat** [comment]
11180 is from their GameConfiguration.json file.

**Comment by Barbosik** [comment]
my previous measurement has mistake. Here is fixed:

Server reported size:
```
[TRACE] Border: 14097.6494630609; 14121.6311990065
```

Real size:
```
14116; 14144
```

**Comment by NatsuTheGreat** [comment]
Imma make it 11180 anyway. Less lag :P

**Comment by NatsuTheGreat** [comment]
>Any way of getting the food to grow without lag? It grows the food without a timeout.

**Comment by Barbosik** [comment]
larger map = less lags. Small map = high lags. It's because lags happens when a lot of cells near each other. When the distance between cells is high, lag is minimal.

**Comment by NatsuTheGreat** [comment]
But if I decrease amount cells and viruses, I don't have much lag, right?

**Comment by Barbosik** [comment]
yes

**Comment by NatsuTheGreat** [comment]
Yep, done that. :)

**Comment by NatsuTheGreat** [comment]
Done it, my friend join, lag is unbelievable.

**Comment by NatsuTheGreat** [comment]
and when you play alone, food doesn't spawn were you passed by. i mean it does, but very little. yOu created quadtrees? Like quadrants? Maybe we could make it spawn randomly between the quadrants

**Comment by Influxx** [comment]
Right now `spawnFood()` uses `getRandomPosition()` so food can spawn anywhere, hence it doesn't fill up the "holes" left by player cell movement. If you try making food spawn where food is the least dense, it would have an impact on performance, unless @Barbosik knows of a smart way to do it :)

**Comment by NatsuTheGreat** [comment]
Yeah I knew it would have impacts on performance :/

**Comment by NatsuTheGreat** [comment]
@Barbosik Bots seem to be really slowing my server down from "perfectly smooth" to "extreme high lag" 65.36 ms+. When I get rid of the bots, it's back to 20-

**Comment by Barbosik** [comment]
Just set spawnInterval = 25 and it will solve your issue

**Comment by NatsuTheGreat** [comment]
Ever since I did that, my server is laggy crap.

**Comment by Barbosik** [comment]
if it still lags with spawnInterval = 25, then your foodSpawnAmount is too high
