### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#65]
![image](https://cloud.githubusercontent.com/assets/19770308/16257857/e69fb91e-3895-11e6-9c2b-d1113c855d94.png)

Yee. I can't connect vanilla agar.io client.
Please check it. :)

**Comment by Barbosik** [comment]
It's vanilla client issue. Other clients works ok

**Comment by xinyuweb** [comment]
you can open :[](http://cells.happyfor.me)

**Comment by xinyuweb** [comment]
http://cells.happyfor.me

**Comment by Barbosik** [comment]
they fixed it
