### ISSUE TITLE
Mini map doesn't work probally

### ISSUE THREAD

**Issue by Dramex** [Barbosik/MultiOgar#66]
Hi, if you use client with mini map its doesn't show your real place

try using :
http://ogar.mivabe.nl?ip=127.0.0.1:50000

Or your own client with minimap script

for your multiogar demo servers : 
http://ogar.mivabe.nl/?ip=164.132.48.230:600
http://ogar.mivabe.nl/?ip=vps.simonorj.com:24270	

Thank you !

**Comment by Influxx** [comment]
Set serverScrambleCoords to 0 in the config.

**Comment by Dramex** [comment]
@Influxx i tried both 0 and 2, same problem

**Comment by Influxx** [comment]
The border structure changed with commit https://github.com/Barbosik/MultiOgar/commit/80be17e5f7fe0e97ba42bab287c750ae2a9f08f7

You will need to update the client to account for it.

**Comment by Barbosik** [comment]
ogar.mivabe.nl has some mistakes in border bound calculations for minimap. So it needs to be fixed.
ogar.mivabel.nl calculates border size incorrectly for minimap, so it cannot show minimap properly even with serverScrambleCoords = 0.

**Comment by Dramex** [comment]
It was working with me fine with ogar, and ogarserv.

and i tried about 5 minimaps, all of them have same problems

**Comment by Barbosik** [comment]
it was worked because ogar and ogarserv using shifted border. It's incorrect.

**Comment by Dramex** [comment]
i have this minimap, could you change it for me becouse i got confused what to changed

```
		var pointSize = 5;
		var mapx = 10 + (nodeX/rightPos)*100 - pointSize*0.5;
		var mapy = 80 + (nodeY/bottomPos)*100 - pointSize*0.5;
		
		ctx.globalAlpha = .4;
		if ( showDarkTheme==true ){
			ctx.fillStyle = "#DDDDDD";
		}else{
			ctx.fillStyle = "#000000";
		}
		ctx.fillRect(10, 80, 100, 100);
		
		ctx.globalAlpha = 1;		
		if ( showDarkTheme==true ){
			ctx.fillStyle = '#FFFFFF';
		}else{
			ctx.fillStyle = '#112233';
		}		
		ctx.fillRect(mapx,mapy,pointSize,pointSize);
		ctx.globalAlpha = 1;
		ctx.font = "16px Ubuntu";
		ctx.fillText(Math.round(nodeX/1000)+' , '+Math.round(nodeY/1000), 10, 200);
```

**Comment by Barbosik** [comment]
this code is incomplete. You can use code from this script: https://greasyfork.org/en/scripts/13140-secret-agario-script/code

window.mini_map - canvas to render minimap
window.mini_map_tokens - it's cells info, each token consists of x, y and size for cell

```
function miniMapRender() {
        var canvas = window.mini_map;
        var ctx = canvas.getContext('2d');
        ctx.clearRect(0, 0, canvas.width, canvas.height);
        for (var id in window.mini_map_tokens) {
            var token = window.mini_map_tokens[id];
            var x = token.x * canvas.width;
            var y = token.y * canvas.height;
            var size = token.size * canvas.width;

            ctx.beginPath();
            ctx.arc(
                x,
                y,
                size,
                0,
                2 * Math.PI,
                false
            );
            ctx.closePath();
            ctx.fillStyle = token.color;
            ctx.fill();

            if (options.enableCross && -1 != current_cell_ids.indexOf(token.id))
                miniMapDrawCross(token.x, token.y, token.color);

            if (options.enableAxes && -1 != current_cell_ids.indexOf(token.id))
                miniMapDrawMiddleCross()

            if (id_players[id] !== undefined) {
                // Draw you party member's crosshair
                if (options.enableCross) {
                    miniMapDrawCross(token.x, token.y, token.color);
                }

                ctx.font = size * 2 + 'px Arial';
                ctx.textAlign = 'center';
                ctx.textBaseline = 'middle';
                ctx.fillStyle = 'black';
                ctx.fillText(id_players[id] + 1, x, y);
            }
        };
    }
```

**Comment by Dramex** [comment]
Hmm, i still have the problem 

could you see the full code here : http://3rb.io/gr.js
and the problem here http://3rb.io server name TEST SERVER

sorry about that, i really need your help :(

**Comment by Dramex** [comment]
Yes thats solved it, Thank you <3
