### ISSUE TITLE
My server is randomly freezing.

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#67]
My server freezes randomly over time. And my console ignores anything I type.

**Comment by Barbosik** [comment]
what is your config?

**Comment by NatsuTheGreat** [comment]
My gameserver.ini?

**Comment by Barbosik** [comment]
Do you really think that I know telepathy? 
I don't know nothing about your case. 
It means that:
* I don't know what gameserver.ini you're using.
* I don't know what hardware you're using.
* I don't know if you're using original sources from master branch, or modified.
I even don't know what did you mean with "server freezes randomly over time".

Basically, your issue sounds like "somewhere, something is going wrong, somehow".
So, how I can help?

**Comment by NatsuTheGreat** [comment]
I never said you know telepathy. Jesus christ.

// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverIpLimit: Controls the maximum connection amount from single IP (use 0 to disable)
// serverTracker: Set to 1 if you want to show your server on the tracker http://ogar.mivabe.nl/master (check that your server port is opened for external connections before setting it to 1)
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// serverStatsPort: Port for the stats server. Having a negative number will disable the stats server.
// serverStatsUpdate: Amount of seconds per update for server stats
// serverLogLevel: Logging level of the server. 0 = No logs, 1 = Logs the console, 2 = Logs console and ip connections
// serverScrambleCoords: Toggles scrambling of coordinates. 0 = No scrambling, 1 = scrambling. Default is 1.
// serverMaxLB: Controls the maximum players displayed on the leaderboard.
// serverChat: Allows the usage of server chat. 0 = no chat, 1 = use chat.
serverMaxConnections = 64
spawnProtection = 1
serverIpLimit = 2
serverPort = 50000
serverTracker = 0
serverGamemode = 0
serverBots = 0
serverViewBaseX = 1920
serverViewBaseY = 1080
serverStatsPort = 88
serverStatsUpdate = 60
serverLogLevel = 1
serverMaxLB = 10
serverChat = 1

// [Border]
// Border size (vanilla values are 14142.135623730952)
borderWidth = 11180
borderHeight = 11180

// [Spawn]
// Each interval is 1 tick (50 ms)
// foodMass: vanilla 1, size 10
// foodMassLimit: vanilla 4, size 20
spawnInterval = 1
foodSpawnAmount = 100
foodStartAmount = 2000
foodMaxAmount = 2000
foodMass = 1
foodMassGrow = 0
foodMassGrowPossiblity = 90
foodMassLimit = 4
virusMinAmount = 30
virusMaxAmount = 70
virusStartMass = 100
virusFeedAmount = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells (vanilla mass 13.69, size 37)
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 13.69
ejectMassLoss = 15
ejectSpawnPlayer = 50

// [Player]
// playerStartMass: start mass (vanilla 10.24, size 32 - minimum player size)
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerBotGrowEnabled: If 0, eating a cell with less than 17 mass while cell has over 625 wont gain any mass
// playerMassAbsorbed: Fraction of a player cell that gets absorbed upon eating (i.e., 1 = 100%, 0.8 = 80%, etc)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur
// playerDisconnectTime: The amount of seconds it takes for a player cell to be removed after disconnection (If set to -1, cells are never removed)
// playerSpeed: Player speed multiplier (1=normal speed, 2=twice faster)
playerStartMass = 43
playerBotGrowEnabled = 1
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 10
playerMaxNickLength = 15
playerSpeed = 1
playerDisconnectTime = -1

// [Gamemode]
// Custom gamemode settings
// tourneyTimeLimit: Time limit of the game, in minutes.
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyTimeLimit = 20
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by NatsuTheGreat** [comment]
The bots seem to be the ones crashing my server.

**Comment by Barbosik** [comment]
```
spawnInterval = 1
```

this will leads to lags. Change it at least to 20, but 40 will be better

**Comment by NatsuTheGreat** [comment]
I kinda want my entities spawning fast. Can I get rid of spawnInterval?

**Comment by Barbosik** [comment]
fast spawning = high lags

Also, I noticed that your ini file is outdated. Some variables is missing.
You can decrease field of view for spectators in order to reduce server load from spectators:
By default it's 0.4:
```
serverSpectatorScale = 0.4
```

It's current vanilla value. Old vanilla used 0.25.
Small value = high lags from spectators.
High value = low lags, but it reduces visible area for spectators.
You can set 0.5-0.6 it will reduce lags if you have a lot of spectators

**Comment by NatsuTheGreat** [comment]
I got rid of variables, and not using the completely latest version. And what if I have just a few or one spectator? And wouldn't higher values mean more node updating to do?

**Comment by Barbosik** [comment]
The most heavy is free-roam spectators. They have low field of view, so they can see a lot of cells. You can fix it with high serverSpectatorScale

**Comment by NatsuTheGreat** [comment]
Why does fast spawning cause lag though? :/

**Comment by Barbosik** [comment]
because each spawn operation is long and requires a lot of calculations.
If you set foodSpawnAmount = 100, it means that 100 food cells should be spawned in 1 tick.
If you set spawnInterval = 1, it means that spawn happens each tick (25 times per second).
So, your values leads to spawn 2500 food cells for every second.

**Comment by NatsuTheGreat** [comment]
Ehh I see.

**Comment by NatsuTheGreat** [comment]
So back to me server freezing. I just turn on bots and randomly, I don't even know when, the server freezes.

**Comment by Barbosik** [comment]
first of all, remove your gameserver.ini. Then start and stop the server. It will create default gameserver.ini. Try with default values. Is it reproduced?

**Comment by NatsuTheGreat** [comment]
Yes, it just froze.

**Comment by Barbosik** [comment]
what hardware you're using?

**Comment by NatsuTheGreat** [comment]
My mod.

**Comment by Barbosik** [comment]
There is a lot of changes, so it's incompatible with mods developed for original Ogar branch

**Comment by NatsuTheGreat** [comment]
Well my mod is MultiOgar.

**Comment by Barbosik** [comment]
I have no idea what is wrong in your mod. If you show the changes, I can look it. But without source it's impossible to say what is wrong

**Comment by NatsuTheGreat** [comment]
It's the bots that cause the crash, but our AI files are identical.

**Comment by Barbosik** [comment]
if it's identical, it should not crash

**Comment by NatsuTheGreat** [comment]
I think I know the problem.

**Comment by NatsuTheGreat** [comment]
Yep that seems to fix it.

**Comment by Barbosik** [comment]
with no mods, I can run up to 500 bots, almost with no lags. I tested 1000 bots it also works good, but with some smooth lags.

**Comment by NatsuTheGreat** [comment]
I have 860 bots on right now. The update is 135 MS

**Comment by NatsuTheGreat** [comment]
1000 bots = 255 MS update XD

**Comment by Barbosik** [comment]
it's too high. For smooth gameplay you need max 40-50 ms

**Comment by NatsuTheGreat** [comment]
Just tested with the latest version, it's the same story. It exceeds 250 MS with 1000 bots

**Comment by NatsuTheGreat** [comment]
Mine exceed 600, but it was running fairly well. The bots get big faster, start mass is 43.

**Comment by NatsuTheGreat** [comment]
I have a question, what if I only have an interval for spawning viruses? The virus spawning seems to be the long calculations. Not the food spawning.

**Comment by Barbosik** [comment]
current change is incomplete, I just prepare source code to replace slow trigonometric funtions with fast vector calculations

**Comment by Barbosik** [comment]
virus and food spawned at the same interval

**Comment by NatsuTheGreat** [comment]
Yes. And I wanted to know if giving the virus spawning the interval, but having the food spawn without an interval somehow reduce lag.

**Comment by Barbosik** [comment]
Food spawning is the most laggy operation, it should not be spawned with no interval, because it will leads to high lags.

**Comment by Barbosik** [comment]
More interval for spawn = less lags. If you set spawnInterval to 1, you will get extremely high lags

**Comment by Barbosik** [comment]
This is the reason why your server freezing. Just set spawnInterval = 25 and all will be ok

**Comment by NatsuTheGreat** [comment]
Alright, thanks for your time. Just to not waste issue space, can you make the bots stop sticking at the border?
