### ISSUE TITLE
too fast with agarplus

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#68]
Idk why when I use agarplus its too fast its fine with other client or any other protocol 
the fps is faster than it should be how to fix ? 
you can test my server 134.119.17.230:443

**Comment by Influxx** [comment]
Agarplus has many FPS tweaks that's why it's smoother / faster.

If you think player speed is too fast, you can change the playerSpeed multiplier in the config.

**Comment by David1ali12** [comment]
alright thx for info :smile:
