### ISSUE TITLE
not fixed 

### ISSUE THREAD

**Issue by David1ali12** [Barbosik/MultiOgar#69]
the big piece of cell  split not the small pieces split , thats make splitrun so hard :/

**Comment by NatsuTheGreat** [comment]
I like that more.

**Comment by David1ali12** [comment]
dude  I cant realtime asf

**Comment by NatsuTheGreat** [comment]
client.cells.sort

^^ Try removing that.

**Comment by David1ali12** [comment]
where is that ?

**Comment by NatsuTheGreat** [comment]
splitCells() in gameServer.

**Comment by Barbosik** [comment]
you're asked to change split from small cell to big one. I implemented it. So, what is wrong?

**Comment by Barbosik** [comment]
it seems that vanilla use split with order by cell age. I fixed it.
Try it now.

**Comment by David1ali12** [comment]
Alright thx
