### ISSUE TITLE
Error when changing gamemode to Teams or to other gamemodes.

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#7]
```
TypeError: Cannot read property 'playerTracker' of undefined
    at GameServer.updateLeaderboard (C:\Users\Amal\Desktop\MultiOgar-master\src\GameServer.js:388:44)
    at GameServer.mainLoop (C:\Users\Amal\Desktop\MultiOgar-master\src\GameServer.js:401:10)
    at wrapper [as _onTimeout] (timers.js:275:11)
    at Timer.listOnTimeout (timers.js:92:15)
```

Screenshot:

![3](https://cloud.githubusercontent.com/assets/11600822/15802073/949727dc-2a9f-11e6-85d7-1e8405981be7.png)

**NOTE: You can fix it by using this code, at https://github.com/OgarProject/Ogar/issues/579#issuecomment-219527197. However, the latest OgarProject doesn't use this code as it's handled somewhere in the updateClients function**

**Comment by F0RIS** [comment]
I can say more: from all modes works only FFA and Experimental. And same error i getting in original Ogar project. Seem that this issue came from there.

**Comment by Barbosik** [comment]
I added temp fix with check to avoid this error, but leaderboard will be empty. I will fix it later

**Comment by Barbosik** [comment]
fixed
