### ISSUE TITLE
 Where they lodge the skin?

### ISSUE THREAD

**Issue by NoiseControllers** [Barbosik/MultiOgar#71]

**Comment by Barbosik** [comment]
Please explain your issue:
1) Steps to reproduce
2) Expected result
3) Actual result
4) What is wrong

**Comment by NoiseControllers** [comment]
< shark > Fish
not work
where you should put the url of the skin

**Comment by Barbosik** [comment]
hm, I will check it

you can also use chat command to change skin.
Just type in the chat: /skin %shark
You should have no cells in order to change skin. For example use it from spectator mode

**Comment by Barbosik** [comment]
just tested it:
```
<shark>Fish
```

works ok. Do not use spaces between < and >

**Comment by NoiseControllers** [comment]
https://gyazo.com/c268af809a983e247dc9ba84df39aaa7

**Comment by Barbosik** [comment]
it seems like client issue. What client you're using?

**Comment by NoiseControllers** [comment]
own client, I thought that, it worked as ogar -unlimited
https://github.com/AJS-development/Ogar-unlimited/blob/master/src/customskins.txt

Thank you anyway

**Comment by Barbosik** [comment]
Just tested it on agar.io and ogar.mivabe.nl - works ok
