### ISSUE TITLE
Too many viruses

### ISSUE THREAD

**Issue by F0RIS** [Barbosik/MultiOgar#72]
Made git clone, started server, set my mass and saw this.

![image](https://cloud.githubusercontent.com/assets/10178982/16336079/48f4100a-3a13-11e6-9634-fdb98949a677.png)

 It seems that viruses count from start going to virusMaxAmount = 50

**Comment by Barbosik** [comment]
fixed

**Comment by lulzyyy** [comment]
Please increase also viruses and food amount as you increased map size.

For example (I set it on my server):
// [Spawn]
// Each interval is 1 tick (40 ms)
// foodMinSize: vanilla 10 (mass = 10*10/100 = 1)
// foodMaxSize: vanilla 20 (mass = 20*20/100 = 4)
foodMinSize = 10
foodMaxSize = 20
foodMinAmount = 1000
foodMaxAmount = 2000
foodSpawnAmount = 50
foodMassGrow = 1
spawnInterval = 20

// virusMinSize: vanilla 100 (mass = 100*100/100 = 100)
// virusMaxSize: vanilla 140 (mass = 140*140/100 = 196)
virusMinSize = 100
virusMaxSize = 140
virusMinAmount = 40
virusMaxAmount = 120
