### ISSUE TITLE
Cells splits at 21 mass instead of 36 mass

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#73]
**In vanilla Agar.io you've to be at least 36 mass in-order to split.**

43 mass (main cell) -> 21 mass (1st split) 

![image](https://cloud.githubusercontent.com/assets/11600822/16347191/477d4310-3a43-11e6-9582-c4e8700d42b1.png)

**In MultiOgar you've to be at least 21 mass in-order to split instead of 36 mass.**

42 mass (main cell) -> 21 mass (1st split) -> 10 mass (2nd split)

![image](https://cloud.githubusercontent.com/assets/11600822/16347947/7bbed414-3a47-11e6-8486-712d206bc81b.png)

NOTE: I'm using the latest MultiOgar as of this commit (https://github.com/Barbosik/MultiOgar/commit/a67fef5f14de52a3be7d98e71b5c6afd76f4227d)

**Comment by Barbosik** [comment]
yes, the minimum size for split and for eject in vanilla is the same It's size=60. But in currently in MultiOgar you can split with size 52. It's very interest question why vanilla uses 60, may be it's related with mass penalty which is used in vanilla for eject. Currently MultiOgar doesn't use any mass penalty, you can eject mass, eat it and your mass will be the same as before eject.

**Comment by Barbosik** [comment]
There is better way. We can set mass in the following way:
```
playerStartSize = massToSize(43)
```
but it requires to add support for it in ini parser

**Comment by Barbosik** [comment]
fixed

**Comment by MastaCoder** [comment]
@Barbosik I think we should add it, helps keep people from just ejecting into a corner, waiting for someone to spawn, and eat them like nothing happened.
