### ISSUE TITLE
Direction of viruses

### ISSUE THREAD

**Issue by Prime55** [Barbosik/MultiOgar#79]
Viruses always go to the right when they hit a lot of mass. This doesn't happen in MultiOgar.
See [this video](https://www.youtube.com/watch?v=B9b8XMM7tjU) at 0:57.

**Comment by NatsuTheGreat** [comment]
It's actually right. Math.PI / 2.

**Comment by Prime55** [comment]
@NatsuTheGreat Oh, i meant right.

**Comment by Barbosik** [comment]
MultiOgar virus works exatly the same as on the video.
Virus split direction depends on direction of ejected mass. 
So, if ejected mass was ejected from right to left, then virus will split from right to left, it doesn't depend on virus movement direction.

**Comment by Barbosik** [comment]
**NatsuTheGreat:** no, there is no Math.PI / 2. It's not the case.
And vanilla doesn't uses angles at all. Basically Math.PI / 2 is just Vector.X in vector arithmetic, it's usually used when vector length cannot be determined.

**Comment by Barbosik** [comment]
If you have video from vanilla where virus splits to the right from ejected mass which ejected to the left direction it looks like vanilla bug. It's not fair for gameplay.
