### ISSUE TITLE
Some left over code when removing the anti-team features

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#8]
All of these can be found in entities/EjectedMass.js

![1](https://cloud.githubusercontent.com/assets/11600822/15801918/b90a9a8a-2a9b-11e6-8472-11dadf1da75a.png)

![2](https://cloud.githubusercontent.com/assets/11600822/15801919/bac1c574-2a9b-11e6-8c18-f7df84a480cb.png)

**Comment by Barbosik** [comment]
fixed
