### ISSUE TITLE
can u please provide gitclone address of multiogar

### ISSUE THREAD

**Issue by fayizan** [Barbosik/MultiOgar#80]
I think title is enough

**Comment by Barbosik** [comment]
How can I do it?

**Comment by ItzLevvie** [comment]
https://github.com/Barbosik/MultiOgar.git

**Comment by fayizan** [comment]
thanks I cloned but why it is soo lagging..?

**Comment by Barbosik** [comment]
just tested, it seems that this one works ok:
```
git clone git://github.com/Barbosik/MultiOgar.git
```

**Comment by fayizan** [comment]
Try My server play.ogarul.tk/?ip=139.59.4.192:443

**Comment by Barbosik** [comment]
added git://github.com/Barbosik/MultiOgar.git to readme

**Comment by Barbosik** [comment]
**fayizan**: if your server lagging, it has bad network connection (high latency or limited speed for example). It's not related to the MultiOgar code. It's hardware issue

**Comment by fayizan** [comment]
sry @Barbosik  its my iinternet which caused me lag,Multiogar is soo smooth
