### ISSUE TITLE
When reach the Virus

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#81]
![1](https://cloud.githubusercontent.com/assets/19770308/16362289/e4a65d5e-3be5-11e6-8c01-0d2506c5b5f4.png)
Yee.

Simply, Vanilla Agar.io has two little big cell beside much larger cell.
But Multi-Ogar has one little big cell beside much larger cell.

I think we can't have many pop split chance because this.

**Comment by Barbosik** [comment]
I also noticed that behavior. Currently MultiOgar uses virus throw code from Ogar. It needs to be fixed in order to fix pop-split. 
But there is need for a good video with enabled mass from vanilla server which shows how a big cell throws on a virus. Do you have it?

**Comment by Chancerst** [comment]
@Barbosik I don't have it.
But that is same when that cell reached the virus. ( i saw vanilla agar.io )
I will record when i have time.

**Comment by Chancerst** [comment]
@Barbosik 
![agar io](https://cloud.githubusercontent.com/assets/19770308/16370682/ab29f3dc-3c7c-11e6-9ff4-d53709ee590b.png)
Vanilla Agar.io
![multiogar](https://cloud.githubusercontent.com/assets/19770308/16370685/b1aa6110-3c7c-11e6-8c38-91b7b00dfda5.png)
Multi-Ogar

correctly, when the cell split one time,(22000) Vanilla has two little big cell, But Multi-Ogar has one little big cell.
so i think we can't have many popsplit chance.

(i couldn't have record chance, so i upload image.)

**Comment by Chancerst** [comment]
I think it's fixed.
So i close this issue
