### ISSUE TITLE
Did you add the new skins? (image)

### ISSUE THREAD

**Issue by Tokoagar** [Barbosik/MultiOgar#83]
Title can tell you what I mean but here is the screenshot

https://cdn.discordapp.com/attachments/155683663617458176/196749623589601281/unknown.png

**Comment by Tokoagar** [comment]
Here's one https://configs-web.agario.miniclippt.com/live/v4/117/FunShine_Bear.png

**Comment by Barbosik** [comment]
server doesn't store any skin, so there is no way to add skin. Server just send skin name provided by user. What skin will be shown for skin name provided by user depends on the client.

**Comment by Tokoagar** [comment]
ok
