### ISSUE TITLE
Why was Anti-teaming removed?

### ISSUE THREAD

**Issue by darknight99x** [Barbosik/MultiOgar#85]
It's a really useful feature, was something wrong with it?

**Comment by Barbosik** [comment]
to make mass calculations clean and fast with no kludges and hidden bugs

**Comment by Influxx** [comment]
Anti teaming is really useless (in my opinion). We're better off without it.

Also, I think the food mass grow is unnecessary to have as a feature. Or at least, have it disabled by default. I can't remember the last time I've seen food grow in vanilla agar.io.

**Comment by Barbosik** [comment]
**Influxx**: the food is the main performance bottle-neck in MultiOgar. Actually you can spawn 1000 bots and it will works with no lags with small amount of food on the map.
