### ISSUE TITLE
Update command?

### ISSUE THREAD

**Issue by Megabyte918** [Barbosik/MultiOgar#86]
Hello, I was wondering if you could add an update command for MultiOgar? theres so many commits and so many updates all the time, I hate having to download a fresh zip of the files and copy and paste my configs every time theres an update. It gets really annoying after a while :( 
It would be alot easier to use the update command then to download a zip every time. Is there any way this could be implemented? Thanks for your time

**Comment by Influxx** [comment]
Why don't you just use git? I think an update command is useless when we have git.
You should not download a zip file, you should git clone and then pull in the updates.

**Comment by Barbosik** [comment]
there is a lot of ways to update with git, with scripts and other. I don't think that some kludges to update code will be good idea, because it will works for one case, but will not work for other. And I don't want to add a bunch of code just to support your way to update. Just use standard tools for such purposes.

**Comment by Megabyte918** [comment]
How do I use git to update? Im kindof new to github i just joined like 4 and a half months ago, ive only really gotten used to making pr's and issues and all of that stuff but ive never really used "git" before

**Comment by MastaCoder** [comment]
I believe from what I remember you type in git and the URL of the repo in CMD or terminal in the directory so it downloads anything new? Not sure though.

**Comment by Barbosik** [comment]
to get MultiOgar code just run the command:
```
git clone git://github.com/Barbosik/MultiOgar.git
```

to get the latest changes, just run the command:
```
git pull
```

**Comment by Influxx** [comment]
When you have made edits to the config file or other files, you will need to discard your changes before you can `git pull` the latest commits. Make sure to keep a backup of your discards so you can restore them after you pull. To discard changes, run:
```
~ git clean -df
~ git checkout -- .
```

**Comment by Megabyte918** [comment]
That actually seems pretty ez
