### ISSUE TITLE
Recombine Time Issue

### ISSUE THREAD

**Issue by hartsindale** [Barbosik/MultiOgar#89]
It seems playerRecombineTime only works for values 30 and 0, and none in the inbetween, how can this be fixed?

If the recombine time is 1, it takes longer than 1 second, and same for 0.3, the recombine time is huge.

**Comment by Barbosik** [comment]
For instant merge, just set playerRecombineTime = 0
Otherwise playerRecombineTime defines minimum recombine time.
Actual time depends on the cell mass.

**Comment by dark84s** [comment]
I'm having the same problem.
cell age. How do I use the normal way?
