### ISSUE TITLE
When using the skin functionality

### ISSUE THREAD

**Issue by ItzLevvie** [Barbosik/MultiOgar#9]
![image](https://cloud.githubusercontent.com/assets/11600822/15801981/8cda4cf6-2a9d-11e6-97b1-433ed06f0935.png)

If you change "client" to "null" in https://github.com/Barbosik/MultiOgar/blob/master/src/GameServer.js#L733, it seems to fix the issue for me.

![image](https://cloud.githubusercontent.com/assets/11600822/15802032/00bce2ea-2a9f-11e6-9225-fa61ef09953e.png)

**NOTE: For this to work, you'll have to remove some codes from https://github.com/Barbosik/MultiOgar/issues/8, because those were the left over anti-teaming code which isn't needed due to its features being completely removed from the entire code and will spew out some errors if you left it there.**

**Comment by Barbosik** [comment]
fixed
