### ISSUE TITLE
Autoupdate feature AND make the server work from specific client only

### ISSUE THREAD

**Issue by Dramex** [Barbosik/MultiOgar#91]
Hi, 

i have 10 servers, and its hard to make them uptodate, becouse you make changes per day
so if you would like to add autoupdate feature its will be good :)
and please when you do it create new ini file that will not update itself, to make us put our edited configuration in it.

second thing, i saw a nice feature in ogar-unlimited, i  make it in my own multiogar which is make the server connect from specific client .. example code :  

```
		var origin = ws.upgradeReq.headers.origin;
		if (origin != "http://client.io") {
            console.log("\u001B[33mClient tried to connect from  [origin "+origin+"]!\u001B[0m");
            ws.close(1000, "not from the origin");
            return;
		}
```
so its nice to have the origin in config like ogar-unlimited :+1: 
`allowonly = ""
`

last thing, i tried to reach you for private thing and i didn't found any contact details, could you send me a massage at my email please ea@ea.sa :)

**Comment by Barbosik** [comment]
1) Use git pull command to update

2) it's stupid idea, because user can set any string for origin header. It's just informative string. So, why they should set it to some specific value?
