### ISSUE TITLE
client?

### ISSUE THREAD

**Issue by xinyuweb** [Barbosik/MultiOgar#92]
What is this client?very nice,can  you share it to me?
![68747470733a2f2f692e696d6775722e636f6d2f4e78517853585a2e706e67](https://cloud.githubusercontent.com/assets/5715519/16471505/b8dc9aec-3e8f-11e6-945f-7d44de6283b7.png)

**Comment by lulzyyy** [comment]
Don't share it. Give some tips to optimize the client and let the people do it themselves.

**Comment by Barbosik** [comment]
it's my own private client. I just set serverSpectatorScale = 0.05 to spectate entire map in free roam.
But I don't recommend to set such value on the server, because it will leads to server lags if a lot of player will try to spectate full map simultaneously.

**Comment by xinyuweb** [comment]
I just learn Optimized code! fps 61,cells 1700+! How to do it?please,give me some tips or core  code!!!

**Comment by NatsuTheGreat** [comment]
Yeah, I'd love tips. :P

**Comment by Barbosik** [comment]
Read about LOD: https://en.wikipedia.org/wiki/Level_of_detail
You don't need to render circle with by 100 points if it's physical size on display is just 10 pixels.
For example, if physical size of circle is < 4, you can render it just as rectangle. It will looks the same for so small physical size.
You can calculate physical size with using current scale and cell radius (size).

The most complicated thing is text. There is need to use 10-16 fixed size fonts. According to needed physical font size you can choose nearest font size and scale it to needed size. Also you can check if text is too small, you can just don't render it, because user will not be able to read it if it's size just 1-2 pixels

**Comment by xinyuweb** [comment]
Please give some code, Please!!!

**Comment by MastaCoder** [comment]
lol.

**Comment by Barbosik** [comment]
Here is interesting screenshot:
MultiOgar server with 100000 foods on the map and 300 viruses, map size 14142x14142.

7500+ cells in spectate view area! 
Here is a lot of viruses on the screen, each virus has complex moving animation for spikes. I didn't used LOD for virus animation, so there is just 30 fps, but works very very smooth, much better than vanilla client :)

MultiOgar 1.2.4 works with no lags at all - perfectly smooth! :)

![Screenshot](http://i.imgur.com/FLbuPLC.png)

**Comment by NatsuTheGreat** [comment]
>MultiOgar 1.2.4 works with no lags at all - perfectly smooth! :)

With the same settings?

**Comment by Barbosik** [comment]
**NatsuTheGreat**: yes, 100000 food, 300 viruses, but there is no bots :)

**Comment by NatsuTheGreat** [comment]
Can you check it out with bots? I'm on my phone right now.

**Comment by Barbosik** [comment]
With bots it lags :)
But it's playable for one player :)
Here is high lag - 100 ms, because your mass grows very fast with such amount of food, and there are for about 20000 cells on the client screen.
Vanilla client just show "Your computer too slow" and lags with 1 frame per 3-5 seconds :)

**Comment by NatsuTheGreat** [comment]
Okay, thanks.

**Comment by xinyuweb** [comment]
this client is very nice!!! plz,share it. or .give some code.....

**Comment by nulcearc** [comment]
@Barbosik is it wirtten on Java/C/C++/C#?= or JavaScript?

**Comment by lulzyyy** [comment]
the question is - what hardware do you have? because everyone has different hardware and for example, for me may be less fps ...

**Comment by xinyuweb** [comment]
chat and leaderboard i used html.
How to Optimize function drawOneCell?

**Comment by Megabyte918** [comment]
this is pretty neat

**Comment by Barbosik** [comment]
**lulzyyy**: quad-tree cannot help to render cells fast. It's mostly useless for client. It's used for fast collision search. So, there is just one thing on the client side, where it can be used - detect cells collision to show cell touch animation. That's it

You cannot use html if you want to improve performance. You should use OpenGL, and work with vertices and textures directly.

**Comment by Barbosik** [comment]
**nulcearc**: it's written in C# and OpenGL

**Comment by Barbosik** [comment]
May be later I will release client, it will be free and under GNU GPL license which doesn't not allow to use it for commercial purposes.

**Comment by David1ali12** [comment]
Can you   release a client with minions that it sends speicial key to server and the server will allow it to run minions like uuid it will allow to connect like 200 minions per proxy like OgarFeeder
