### ISSUE TITLE
Map Location

### ISSUE THREAD

**Issue by Chancerst** [Barbosik/MultiOgar#94]
![image](https://cloud.githubusercontent.com/assets/19770308/16490365/45f79894-3f14-11e6-9c77-185f92c774bb.png)
](url)
I can't use backgroud location and minimap.
Please fix it.

**Comment by Barbosik** [comment]
there is nothing to fix on server side. 
It's client issue. You can try to set serverScrambleCoords = 0, for some clients it can help. 

When scrambling is enabled, you should not be able to get correct coordinates. It's anti-bot protection.

**Comment by Chancerst** [comment]
@Barbosik it still doesn't work.
Grid location is work, but map location is different.
How i fix it?

**Comment by Barbosik** [comment]
I have no idea, because it's client bug.

**Comment by Barbosik** [comment]
Look at this issue: https://github.com/Barbosik/MultiOgar/issues/66
At the moment minimap were fixed on ogar.mivabe.nl

**Comment by Chancerst** [comment]
@Barbosik Can i change border calculate source in agarplus soure file?

**Comment by Barbosik** [comment]
I do not have nothing to do with agarplus. Ask to agarplus authors.

**Comment by Megabyte918** [comment]
@Chancerst The minimap works on the Ogario extension if you want to use that

**Comment by Chancerst** [comment]
@Megabyte918 I put agarplus source in html file.
so it seems like senpai-agar.
I don't know what server pack use by senpai.
Senpai works grid location and minimap corrently..
Can you fix border calculate? (Then i give you the problem file)

**Comment by CalvinDKHD** [comment]
@Chancerst  Please contact me on skype - calvin.leonhardt
