### ISSUE TITLE
Can you add minions/suicide bots to the game please.

### ISSUE THREAD

**Issue by WolfOGG** [Barbosik/MultiOgar#95]

**Comment by Tmuru321** [comment]
waitting :v

**Comment by lulzyyy** [comment]
[http://giphy.com/gifs/the-office-no-steve-carell-12XMGIWtrHBl5e](url)

**Comment by lulzyyy** [comment]
http://giphy.com/gifs/the-office-no-steve-carell-12XMGIWtrHBl5e

**Comment by Barbosik** [comment]
lulzyy: :)

**Comment by Barbosik** [comment]
no, I don't want to add minions to the server. Vice versa - protections will be added to prevent using it.
The only way to use minions is to set serverScrambleCoords = 0
