### ISSUE TITLE
Can You Please Add http://stats.ogarul.tk Server Tracker

### ISSUE THREAD

**Issue by fayizan** [Barbosik/MultiOgar#96]
@Barbosik  stats.ogarul.tk is so simple and easy to trace server could please add this server tracker feature 

![screenshots_2016-07-01-08-00-11](https://cloud.githubusercontent.com/assets/19163419/16510229/e45a3e0e-3f61-11e6-96a7-4fdb089e3800.png)

Thank you

**Comment by lulzyyy** [comment]
that pings doe

**Comment by Barbosik** [comment]
Where can I find info about tracker interface?

**Comment by fayizan** [comment]
@Barbosik,Here it is

https://github.com/AJS-development/OgarUL-Plugin-Library/tree/master/Statistics

**Comment by fayizan** [comment]
@Barbosik could it be added..?

**Comment by Barbosik** [comment]
If I understand correctly AJS team want to track only their servers and don't wan't to see others on their tracker

**Comment by Barbosik** [comment]
Unfortunately they don't want to list other servers than ogarul: http://stats.ogarul.tk/ban/
So, I cannot add it's support
