### ISSUE TITLE
Sorry, but has this issue been fixed? 

### ISSUE THREAD

**Issue by NatsuTheGreat** [Barbosik/MultiOgar#99]
It's an issue with ```playerlist```. IDs arrange incorrectly. Check it [here](http://prntscr.com/bnr3fm)

**Comment by SimonOrJ** [comment]
It looks like the table is sorted with largest scorer at the top randomly.  This is a weird issue.

**Comment by Barbosik** [comment]
hm, I cannot reproduce it, what node version you're using?

**Comment by Barbosik** [comment]
added sorting
